marko-js/marko

bin/markoc.js
compiler/taglibs/taglib-loader.js
hot-reload/index.js
runtime/helpers.js

There are several use-cases where you’d want .html files instead of .marko files. So I’ve added support for „.marko.html“ files.

Add support for .marko.html templates

---

compiler/ParseTreeBuilderHtml.js

This template fails compilation:
```
<script>
var x = '${x}?y=z&a=';
var x = '${x}?y=z&a=';
</script>
```
While this one compiles:
```
<script>
var x = '${x}?y=z&a=';
</script>
```
Debugging points to an overly-permissive regular expression used to locate HTML entities.  This patch modifies the expression to be stricter about what it matches.

be less permissive when looking for entities to decode

---

compiler/ParseTreeBuilderHtml.js
test/compiler-tests.js
test/fixtures/templates/compiler/entities/expected.js
test/fixtures/templates/compiler/entities/template.marko

This tightens the entity matching regular expression to explicitly handle numeric and hexadecimal entities separately from named entities.  It also adds a simple test that entities are being properly matched.

further tighten entity-matching regex, add basic test for entity matching

---

compiler/taglibs/Taglib/index.js
compiler/taglibs/taglib-loader/loader-taglib.js
compiler/taglibs/taglib-lookup.js
taglibs/caching/marko-taglib.json
taglibs/core/marko-taglib.json
taglibs/html/marko-taglib.json
test/fixtures/taglib-duplicate/foo-renderer.js
test/fixtures/taglib-duplicate/marko-taglib.json
test/fixtures/taglib-duplicate/taglib-duplicate/bar-renderer.js
test/fixtures/taglib-duplicate/taglib-duplicate/marko-taglib.json
test/taglib-lookup-test.js

__Problem:__
Some developers have run into issues because the same module was installed multiple times in their project with different versions. Currently, Marko just walks up the directory tree to discover and load taglibs and it will happily load multiple versions of the same taglib and this can lead to unexpected results.
__Solution:__
Improve the logic of assigning an ID to a taglib such that only one version of a taglib is loaded. The taglib ID will now match the "name" found in the `package.json` found next to the `marko-taglib.json` (if it exists) and we also now allow an ID to be assigned using the `taglib-id` property in a `marko-tag.json` file. Taglibs closer to a template (in the directory tree) will take precedence over taglibs farther away.

Fixes #73 - Prevent same taglib from being loaded multiple times

---

README.md

The utility function `getLength()` for loop status variables was previously undocumented.

doc reference for getLength() of loop status-var

---

runtime/helpers.js

This should resolve issues with circular dependency rendering. Previously, whenever this function was called, it would throw an error because `typeof renderFunc` was always `undefined`. With this fix, `rendererFunc` will (in valid cases) be a function.

Fixed a typo for rendererFunc in helpers.js

---

docs/javascript-api.md
runtime/loader.js
runtime/marko-runtime.js
test/api-tests.js

- Allow loading of template from template source on server-side
- Fix documentation for JavaScript API
- Allow `writeToDisk` option to be passed to load function (e.g. `require('marko').load(templatePath, {writeToDisk: false})`)

Make loading template from String template source easier

---

.gitignore
compiler/taglib-loader/scanTagsDir.js
test/taglib-loader-test.js

With this change, a compile-to-js file such as `index.coffee` can be used in place of the hard coded `index.js` when it comes to custom marko tags.
Refs #235

scan for index/renderer files based on available extensions

---

compiler/Builder.js
compiler/util/parseJavaScript.js
test/fixtures/parseFor/autotest/forEach-invalid-option2/expected.json
test/fixtures/render/autotest/error-bad-expression/test.js
test/fixtures/render/autotest/error-invalid-for-attr-separator/template.marko
test/fixtures/render/autotest/error-invalid-for-attr-separator/test.js
test/fixtures/render/autotest/error-invalid-for-attr/template.marko
test/fixtures/render/autotest/error-invalid-for-attr/test.js
test/fixtures/render/autotest/error-invalid-for-props/template.marko
test/fixtures/render/autotest/error-invalid-for-props/test.js
test/fixtures/render/autotest/error-invalid-if-attr/template.marko
test/fixtures/render/autotest/error-invalid-if-attr/test.js
test/fixtures/render/autotest/error-invalid-if-else-attr/template.marko
test/fixtures/render/autotest/error-invalid-if-else-attr/test.js
test/fixtures/render/autotest/error-invalid-if-else-if-attr/template.marko
test/fixtures/render/autotest/error-invalid-if-else-if-attr/test.js
test/fixtures/render/autotest/error-invalid-if-else-if-else-attr/template.marko
test/fixtures/render/autotest/error-invalid-if-else-if-else-attr/test.js
test/fixtures/walker/autotest/remove-attrs/expected.json

Changes includes
- Better error reporting Ex: Unexpected identifier: (['red', 'blue', 'green'] foo)
- 'If statement' was not parsing the javascript expression, it is fixed now
- Added more negative tests
- Fixed the existing tests which broke due to changes with this PR

better error reporting during compilation of template

---

docs/language-guide.md

the if="conditional" attribute syntax is deprecated in v3

v3 attribute conditional syntax in language guide

---

compiler/CodeGenerator.js
test/autotests/render/error-thrown-in-generator/custom-tag-hyphen-attrs/custom-tag.js
test/autotests/render/error-thrown-in-generator/custom-tag.js
test/autotests/render/error-thrown-in-generator/marko.json
test/autotests/render/error-thrown-in-generator/template.marko
test/autotests/render/error-thrown-in-generator/test.js

Ideally, all our errors in generating code would be developer friendly and added through `context.addError`, however, not every case is covered currently.  
This pull request catches errors from code generators, adds context about the node (including line number in the template when available), and rethrows the error while maintaining the original stack trace.
In the ideal case it looks something like this:
```
Error: Something Happened! -- Generating code for <custom-tag> tag (test/autotests/render/error-thrown-in-generator/template.marko:2:4)
```
Even in cases where we don't have the line number, you at least have a better idea of what might be causing the error.  The following is what the error @seangates encountered earlier would have looked like:
```
Error: 
Unexpected token ): (+)
^ …
```

Add node context to errors thrown from a code-generator function

---

taglibs/core/macro-tag.js
test/autotests/render/error-macro-no-name/marko.json
test/autotests/render/error-macro-no-name/template.marko
test/autotests/render/error-macro-no-name/test.js
test/autotests/render/macro-no-args/expected.html
test/autotests/render/macro-no-args/template.marko

`<macro>` now expects its first attribute to be its name (regardless of whether it has arguments or not), if there are no attributes or the first attribute has a value (ex. `test=123`), then it throws an error.
✅ good:
```xml
<macro greeting>
Hello!
</macro>
<macro greeting()>
Hello!
</macro>
<macro greeting(name)>
Hello ${name}!
</macro>
```
:x: bad:
```xml
<macro async=true>
Uh-oh!
</macro>
<macro test=123 greeting(name)>
Uh-oh ${name}!
</macro>
<macro>
Uh-oh!
</macro>
```

<macro> must have a name

---

package.json

Added `--include-all-sources` option to istanbul command. This reduces coverage from around 87% to 83%, but it should be more accurate because it includes untested files - for example `bin/markoc.js`. Also  changed the script to reuse `npm run jshint` from below for linting.

improve npm test script

---

package.json
taglibs/async/async-fragment-tag.js
test/autotests/async-render/async-fragment-client-reorder-mixed/expected-events.json
test/autotests/async-render/async-fragment-client-reorder-nested/expected-events.json
test/autotests/async-render/async-fragment-client-reorder/expected-events.json
test/autotests/async-render/async-fragment-timeout-message/expected.html
test/autotests/async-render/async-fragment-timeout-message/template.marko
test/autotests/async-render/async-fragment-timeout-message/test.js
test/autotests/async-render/async-fragment-timeout/expected-events.json
test/autotests/async-render/async-fragment-timeout/expected.html
test/autotests/async-render/async-fragment-timeout/template.marko
test/autotests/async-render/async-fragment-timeout/test.js

- Adds additional event info (finished/timedout) to the data emitted from <async-fragment> tags. 
- Ensures that renderBody() is not called again if the fragment has already finished (timed out).
- Fixes `npm run test-async`
- Removes a redundant `async-fragment` timeout related test

Asyncfragment info

---

compiler/Parser.js
test/autotests/render/shorthand-classes-many-classes/expected.html
test/autotests/render/shorthand-classes-many-classes/template.marko
test/autotests/render/shorthand-classes-many-classes/test.js

Only set `prevClassName` when the `className` has been pushed to `finalClassNames`, otherwise future `className` values will be appended to a class that doesn't get included in the final output.  This effectively limits the number of classes to 2.

fixes #307

---

docs/custom-taglibs.md

Documented exclusion of folder or node module from marko.json autodiscovery;

Documentation: Excluding Directory or Package

---

README.md

-use retina image for logo
-center logo with html
-move "Try Marko Online" to first paragraph
-move badges below first paragraph
The only way to reliably test this was by putting it on my fork master, so you can see here https://github.com/yomed/marko. Spacing is a bit worse on mobile, but there's only so much customization you can do before github takes over. Let me know of any concerns.
Desktop:
Mobile (iPhone 6 size):

update readme header

---

compiler/CodeGenerator.js
compiler/CompileContext.js
compiler/ast/HtmlElement.js
compiler/ast/Text.js
runtime/helpers.js
test/autotests/render/escape-script/expected.html
test/autotests/render/escape-script/template.marko
test/autotests/render/escape-script/test.js
test/autotests/render/script-tag-entities/expected.html
test/autotests/render/script-tag-entities/test.js

This PR changes out the escape function that is used when generating code within the context of the `<script>` tag. The escape function used within the context of the `<script>` tag will only escape `'</'` to prevent an ending script tag.

Fixes #322 - Autoescaping doesen't work in <script> tag context

---

compiler/CodeGenerator.js
compiler/CompileContext.js
docs/language-guide.md
test/autotests/render/bodyText/expected.html
test/autotests/render/marko-compiler-options-preserve-whitespace-nested/expected.html
test/autotests/render/marko-compiler-options-preserve-whitespace-nested/template.marko
test/autotests/render/marko-compiler-options-preserve-whitespace-nested/test.js
test/autotests/render/whitespace-marko-preserve-whitespace-attr/expected.html
test/autotests/render/whitespace-marko-preserve-whitespace-attr/template.marko
test/autotests/render/whitespace-marko-preserve-whitespace-attr/test.js
test/autotests/render/whitespace-pre-code/expected.html
test/autotests/render/whitespace-pre-code/template.marko
test/autotests/render/whitespace-pre-code/test.js

Currently when a node/tag is marked with "preserve-whitespace", the whitespace is being preserved for only directly nested text. The expected behavior should be that whitespace should be preserved for all directly nested text and any text nested at any level below the node.
[Issue #345](https://github.com/marko-js/marko/issues/345)

Fixes issue #345 - Whitespace preservation should apply to all nested text

---

compiler/ast/HtmlAttribute.js
docs/language-guide.md
test/autotests/render/attr-empty/expected.html
test/autotests/render/attr-empty/template.marko

Previously there was a difference in the way empty string (`""`) was handled when it was a literal value.  It now uses the raptor-util behavior for both literals and dynamic values.
Fixes #327
**The tests will fail until raptorjs/raptor-util#4 is merged and published**

use the raptor-util behavior for both literals and dynamic values

---

docs/language-guide.md

`while` was introduced in v3, but was missing from the docs. I copied this from the "what's new" page, and then modified it to the same format as the `for` loop documentation.

add docs for while loop

---

README.md

Adds concise syntax example to README.md for applying rendering logic with separate tags.
To make sure the concise syntax is really equivalent to the HTML template I ran this example. I think it makes sense to include it for other new users as another quick introduction to the Marko syntax and the alternative way of applying rendering logic. I would have found it helpful.

add concise syntax example to README.md

---

docs/async-taglib.md
taglibs/async/await-tag.js
test/async-render-test.js
test/autotests/async-render/await-error/expected-events.json
test/autotests/async-render/await-error/test.js
test/autotests/async-render/await-timeout/expected-events.json

Opening this for feedback & discussion.  This PR adds `await:error` and `await:timeout` events.  I will add documentation for these before we merge.
To allow applications to listen for errors that occur in an `<await>` tag, even if the error is handled by the template. For logging purposes and such.

Add events for timeout and error

---

test/autotests/widgets-browser/widget-getEl/template.marko
test/autotests/widgets-browser/widget-getEl/test.js
test/autotests/widgets-browser/widget-jQuery-proxy/template.marko
test/autotests/widgets-browser/widget-jQuery-proxy/test.js
widgets/Widget.js

Bug on jQuery Proxy when w-id contains dash/hyphen, see issue #391 
Bug on jQuery Proxy when w-id contains dash/hyphen (e.g `w-id="submit-button"`)
This PR contains fix for issue #391 
None

Bug on jQuery Proxy when w-id contains dash/hyphen

---

taglibs/async/await-tag.js

As discussed in #439, the `Promises/A+` specification explicitly defines `.then` as accepting at least two arguments: `onResolved` and `onRejected`. The `.catch` method is defined by ECMAScript for *native* implementations, but third-party libraries are under no obligation to include it (though *most* do, for convenience and compatibility).
In the interest of caution, this only calls `.then(undefined, onRejected)` if neither `.catch` nor `.fail` is a function. However, in my opinion, it would be completely safe to remove those two calls altogether, as any implementation which is even *remotely* compliant will handle this as expected.

The `<await>` tag should attempt `.then(undefined, ...)` when resolving a thenable if neither `.catch` nor `.fail` is a function

---

test/autotest.js

The autotest `compareHelper` now normalizes the ending newline of both the `expected` and `actual` strings to avoid test failures when `expected.*` is saved on a POSIX-compliant (non-Windows) OS.

Fixes #446 - Normalize the `expected` and `actual` strings during autotests

---

docs/javascript-api.md
runtime/deprecate.js
runtime/marko-runtime.js

Deprecate `renderSync(data)` and `render(data, callback)` in their current forms.  Use `renderToString` instead as v4 will return a `RenderResult` instead of a string.
With this notice in place, there shouldn't be any breaking changes when moving from v3 to v4 that don't already warn you in the current version.

add warnings for using render methods when you want string output

---

widgets/taglib/getRequirePath.js

Fixes a regression which caused the compiler to `require()` both 'require-self-ref' and '~/test/util/patch-module'. This didn't affect the test suite (which already `require()`s both of those modules), but does throw errors when running `marko` as a module. For example:
```
npm install https://github.com/marko-js/marko
./node_modules/.bin/markoc ./template.marko
```
If `require-self-ref` is also installed:
```
Failed to compile "template.marko". Error: Error: Cannot find module '/path/to/node_modules/marko/test/util/patch-module'
```
Otherwise:
```
Failed to compile "template.marko". Error: Error: Cannot find module 'require-self-ref'
```

Remove direct require of test utils from within the compiler

---

widgets/index.js

The widget runtime uses a custom `.concat` method, but the native array `.concat` method returns a new array without modifying the original, which results in `window.$widgets` being an empty array and the init code being lost if the widgets are initialized before the runtime registers its custom method.

Fixed bug where widgets initialized before the runtime is loaded are lost

---

runtime/dom-insert.js

../widgets/util - don't have  $__destroyWidgetForEl and $__destroyElRecursive functions
Fixed infinite loop in replaceChildrenOf function

Some small fixes in dom-insert.js

---

runtime/helpers.js
test/autotests/compiler/attr-escape/expected.js
test/autotests/compiler/attr-escape/template.marko
test/autotests/render/class-attr-array/expected.html
test/autotests/render/class-attr-array/template.marko

This fix will ensure that an empty array does not output a an empty class attribute: `class=""`.
- modified helpers.js line 55 adds ` || null` when the array is empty (because a joined empty array is falsy);
- fixed tests to accommodate
I was attempting to use arrays for class names because of the utility of concatenating them together was taken up by Marko. But, when the array was ever empty, I would have the `class=""` throughout my app, and my tests. This issue added unnecessary bloat. Therefore, the motivation for this fix.

Fix for class attribute so empty arrays are null;

---

docs/koa.md

Koa 2.0.1 is released as `latest` version, so, these docs needs to be updated. Also added gzip example to feature Koa + Marko streaming flexibility.

Updated Koa docs to version 2.0 signature

---

docs/huncwot.md
docs/server-side-rendering.md
docs/structure.json

A piece of documentation describing how to use Marko alongside [Huncwot](https://github.com/zaiste/huncwot). I'd be happy to hear your feedback.
I'm building a library similar to Express and Koa called Huncwot. I'm planning to use Marko as its default (and only) view engine. Huncwot is inspired by Clojure's ring with routes as (pure) functions returning *data* describing responses. In this pull request I'm describing how to use Marko with Huncwot.
Server-side integration example using Huncwot is simpler and requires less code for the same result as in Koa or Express.

Proposition: add docs for Marko + Huncwot integration

---

components/util-browser.js

Marko global defaults and user globals aren't merged. If user globals exists the `defaults` are ignored.
Look at https://github.com/marko-js/marko/issues/677
- [] I have added tests to cover my changes.
Tests suite doesn't works on windows! I will open an issue for this.

extend marko globals with defaults

---

express.js

This fixes the issue with `res.marko` not getting properly patched due to recent changes.
This change allows the module that is calling `require('marko/express')` to be used when requiring the actual module that performs the patching (`./src/express` or `./dist/express` depending on whether debug mode is enabled). This ensures that the correct instance of express used by the app is getting patched.
Recent changes to the project structure caused `res.marko` to not get properly patched onto express. As a result, tests executed via `marko-devtools` failed to start properly.
- [] I have added tests to cover my changes.

Use parent module to require express patch

---

src/browser-refresh.js
src/hot-reload.js

Add silent option to browser-refresh and hot-reload.
https://github.com/marko-js/marko/issues/709
N/A

Fixes #709 - Add silent option to browser-refresh and hot-reload

---

src/components/taglib/TransformHelper/handleRootNodes.js
test/autotests/compiler/style-empty/expected.js
test/autotests/compiler/style-empty/template.marko

I think we also need to make a change on the [lasso side](https://github.com/lasso-js/lasso/blob/01dde2dbae025762a98fc09e2306c249eeeb2c19/lib/dependencies/dependency-resource.js#L54-L56): If `code` is an empty string, it doesn't use it and instead tries to read from the filesystem.

fixes issue 658 by removing empty style blocks

---

src/components/taglib/TransformHelper/handleRootNodes.js
src/runtime/dependencies/index.js
test/autotests/compiler/metadata/test.js

put package (browser.json) deps before others and parent deps before child deps

Change dependency ordering

---

src/components/Component.js
src/taglibs/async/noop-render.js
src/taglibs/async/package.json
src/taglibs/svg/marko.json
test/autotests/components-pages/diff-body-root/template.marko
test/autotests/components-pages/diff-body-root/tests.js
test/autotests/components-pages/diff-body/template.marko
test/autotests/components-pages/diff-body/tests.js
test/autotests/components-pages/diff-head-root/template.marko
test/autotests/components-pages/diff-head-root/tests.js
test/autotests/components-pages/diff-head/template.marko
test/autotests/components-pages/diff-head/tests.js
test/autotests/components-pages/diff-html/template.marko
test/autotests/components-pages/diff-html/tests.js
test/autotests/components-pages/diff-title/template.marko
test/autotests/components-pages/diff-title/tests.js

Relies on the following PRs:
https://github.com/patrick-steele-idem/warp10/pull/3
https://github.com/lasso-js/lasso/pull/211

Fixes #755 - Allow diffing of HTML, head, and body.

---

src/components/taglib/component-tag.js

Location was missing a `src/` since the structure was updated in https://github.com/marko-js/marko/commit/a602f3cd466ec14468cd8a90e7334299077c329c

updating location of bindComponent helper

---

src/compiler/CompileContext.js
src/compiler/config.js
test/autotests/render/escape-at-tag/expected.html
test/autotests/render/escape-at-tag/template.marko
test/autotests/render/escape-at-tag/test.js
test/util/runRenderTest.js

When `escapeAtTags` options is being passed to the compiler - it will escape `<@whatever></@whatever>` tags with `<at_whatever></at_whatever>`.
During tests, if we isolate tested component from its nested dependencies, we may find ourselves in place where we have `<@whatever></@whatever>` tag sitting not within a custom component element.
*Desired result*: if we're isolating dependencies during tests, we want to render the transclusion code as it is.
- [ x ] My code follows the code style of this project.
- [ - ] I have updated/added documentation affected by my changes.
- [ x ] I have read the **CONTRIBUTING** document.
- [ x ] I have added tests to cover my changes.
- [ x ] All new and existing tests passed.

Added `escapeAtTags` option to compiler in order to render `<@tags>` as they are;

---

src/taglibs/core/import-tag.js
test/autotests/compiler/import-tag-conflict/expected.js
test/autotests/compiler/import-tag/expected.js

Currently when using the import tag to import es6 modules with default exports you instead get the entire exports object like `{ default: ..., }`.
This change checks to see if the default export is set and tries to use it if possible like so:
```js
import myThing from './myfile.js'
```
becomes
```js
var module_myThing = require('./myfile.js')
var myThing = module_myThing.default || module_myThing
```
Resolves https://github.com/marko-js/marko/issues/802.
Currently users have to manually access the default export which is not in line with the modules spec.

Add better interop for importing modules with default exports

---

docs/installing.md

It looks like the marks-cli automatically installs node modules.
Currently in the docs it mentions that after `marko create hello-world` that users must install dependencies. It looks like this is now handled automatically and should be removed from the docs.
Consistency/accuracy of docs.

Remove uneeded command from installation docs

---

docs/components.md
src/components/Component.js
test/autotests/components-browser/input-global/index.marko
test/autotests/components-browser/input-global/test.js

Add ability to override the current out.global by setting new $global property on input.
The change here is small but allows updating the global context without discarding the marko component or using hidden properties like `___global`.
Fixes https://github.com/marko-js/marko/issues/815

Add ability to update globals by setting new input.

---

test/server-tests-runner/cli.js

Increase the allowed time for tests to run with mocha. Some tests were occasionally exceeding the 2s threshold.
During my past few PR's occasionally the CI build's have been failing due to timeouts in mocha.

Increase mocha timeout to avoid CI build's failing

---

src/compiler/Parser.js
src/components/taglib/TransformHelper/assignComponentId.js
src/components/taglib/TransformHelper/handleScopedAttrs.js
test/autotests/render-deprecated/component-aria-key/expected.html
test/autotests/render-deprecated/component-aria-key/template.marko
test/autotests/render-deprecated/component-aria-key/test.js
test/autotests/render/component-aria-key/expected.html
test/autotests/render/component-aria-key/template.marko
test/autotests/render/component-aria-key/test.js
test/autotests/render/component-elId/expected.html
test/autotests/render/component-getElId/expected.html

- fixes scoped/keyed attributes with dashes causing compile-time error (`aria-described-by:scoped`)
- maintains behavior prior to the current beta with a `key` being used alongside `component.elId` or `component.getElId`
```marko
<label for=component.getElId('name')>Name</label>
<input key="name"/>
```
_Disclaimer: Contributions via GitHub pull requests are gladly accepted from their original author. Along with any pull requests, please state that the contribution is your original work and that you license the work to the project under the project's open source license. Whether or not you state this explicitly, by submitting any copyrighted material via pull request, email, or other means you agree to license the material under the project's open source license and warrant that you have …

Key scope fix

---

src/runtime/html/index.js

The main change is to move the following block above any requires:
```javascript
exports.t = function createTemplate(path) {
return new Template(path);
};
```
This avoids issue with circular dependency which broke the hot-reload code because the `t` function was not exported right away.

Fixes #848 browser-refresh does not reload marko files if a static reference is held

---

express.js
src/express.js

Some environments (like jest) don't implement it
I'd like to run tests with jest for an app that using marko.
Tests are failing for some reason, help is appreciated

Fallback to regular require if `module.parent.require` is unavailable

---

test/autotests/render/error-invalid-else-tag-attr-with-if/template.marko
test/autotests/render/error-invalid-else-tag-attr-with-if/test.js
test/autotests/render/error-invalid-else-tag-attr/template.marko
test/autotests/render/error-invalid-else-tag-attr/test.js
test/autotests/render/error-invalid-else-tag-if-attr/template.marko
test/autotests/render/error-invalid-else-tag-if-attr/test.js

I've added tests for parts of the `<else>` tag that were missing coverage.
Adds tests for the following:
- `else` tag with invalid attribute 
- `else` tag with invalid `if` attribute
- `else` tag with attribute in addition to `if` attribute
Improving coverage per #468 

add error tests for else tag

---

src/components/util-browser.js

In some case in this place, without this check, delete will remove necessary numeric keys. This is a possible fix for #893 issue

Fix for #893 issue

---

src/taglibs/core/util/parseFor.js
test/autotests/parseFor/forEach-status-var/input.txt

Added optional white space between the  equal symbol in separator, status-var and iterator of parseFor.
#904

bug: loop status-var not compiling everytime #904

---

docs/server-side-rendering.md

The links for express, hapi, koa, huncwot in the Server-Side Rendering Doc were not working. Appended '.md' to them. They now work.
Was browsing the docs, found a broken link. Fixed it.

Update Docs: Fix framework integrations' doc links

---

src/components/jquery.js
src/components/legacy/defineWidget-legacy-browser.js
src/components/ready.js
test/deprecated-components-browser/index.test.js

In Marko 4, we removed `this.$` and `this.ready` from the component prototype.  However, since many widgets were using these in Marko 3 (and Marko Widgets 6), we added support for `marko/jquery` and `marko/ready`to ease the transition.
Enabling these however, patched _all_ components.  This PR includes them by default for legacy widgets only.

add jquery to legacy widgets

---

src/morphdom/index.js
test/components-browser/fixtures/remove-last-multi-root-component/child.marko
test/components-browser/fixtures/remove-last-multi-root-component/index.marko
test/components-browser/fixtures/remove-last-multi-root-component/test.js
test/components-pages/fixtures/remove-last-multi-root-component/components/child/index.marko
test/components-pages/fixtures/remove-last-multi-root-component/components/root/index.marko
test/components-pages/fixtures/remove-last-multi-root-component/template.marko
test/components-pages/fixtures/remove-last-multi-root-component/tests.js

Prevent attempted to remove dom elements twice (once at component level and once by morphdom).
See https://github.com/marko-js/marko/issues/939 .

Fix issue with multiple top level elements being removed twice.

---

src/components/taglib/TransformHelper/convertToComponent.js
test/deprecated-components-browser/fixtures/widget-bind-different-roots/index.js
test/deprecated-components-browser/fixtures/widget-bind-different-roots/template.marko
test/deprecated-components-browser/fixtures/widget-bind-different-roots/test.js

Tiny PR to support legacy widgets binding to different roots conditionally.
```marko
<if(data.interactive)>
<button w-bind>
Interactive
</button>
</if>
<else>
<div w-bind>Non-interactive</div>
</else>
```

allow conditionally binding to different roots in a legacy widget

---

src/components/legacy/defineWidget-legacy-browser.js

Currently when using a legacy component it is required that jQuery exists.
This change makes jQuery optional.

Make jquery optional for legacy components.

---

src/runtime/vdom/AsyncVDOMBuilder.js

The current error message is not clear about what actually happened.
https://github.com/marko-js/marko/issues/942

Improve error message for async rendering.

---

docs/lasso.md

Updated the documentation of Lasso page.
If I am using the latest lasso and lasso-marko, custom lasso tag is not working. We need to install lasso-marko-taglib to make it to work.
I wasted little bit of my time wasting in it. I thought I would document it so that It would be helpful for others. Thanks for @mlrawlings to pointing out this.
Not Applicable.
_Disclaimer: Contributions via GitHub pull requests are gladly accepted from their original author. Along with any pull requests, please state that the contribution is your original work and that you license the work to the project under the project's open source license. Whether or not you state this explicitly, by submitting any copyrighted material via pull request, email, or other means you agree to license the material under the …

Updated the docs to use lasso-marko-taglib.

---

src/compiler/taglib-loader/loadTaglibFromProps.js

A small typo for an error message in `taglib-loader`.

Fix typo for an error message

---

src/compiler/ast/TemplateRoot.js
src/components/taglib/TransformHelper/handleComponentEvents.js
test/__util__/BrowserHelpers.js
test/__util__/create-marko-jsdom-module.js
test/autotest.js
test/components-browser/fixtures-deprecated/widget-rerender-init-order/components/app-rerender-init-order-child/index.js
test/components-browser/fixtures-deprecated/widget-rerender-init-order/index.js
test/components-browser/fixtures-deprecated/widget-rerender-init-order/test.js
test/components-browser/fixtures/event-attach-el-once/test.js
test/components-browser/fixtures/event-attach-el/test.js
test/components-browser/fixtures/event-detach-remove-nested-component-last/index.marko
test/components-browser/fixtures/event-detach-remove-nested-component-middle/index.marko
test/components-browser/fixtures/global-rerender-nested/test.js
test/components-browser/fixtures/global-rerender/test.js
test/components-browser/fixtures/implicit-component-keys/test.js
test/components-browser/fixtures/implicit-component/test.js
test/components-browser/fixtures/input-global/test.js
test/components-browser/fixtures/lifecyle-hooks-nested-no-id/test.js
test/components-browser/fixtures/lifecyle-hooks-nested-with-id/test.js
test/components-browser/fixtures/lifecyle-hooks-parent-child-ordering/test.js
test/components-browser/fixtures/lifecyle-hooks-root/test.js
test/components-browser/fixtures/widget-dom-events/test.js
test/components-browser/fixtures/widget-rerender-init-order/components/app-rerender-init-order-child/component.js
test/components-browser/fixtures/widget-rerender-init-order/test.js
test/components-browser/fixtures/widget-rerender-reuse-stateful/components/hello/index.marko
test/components-browser/fixtures/widget-rerender-reuse-stateful/test.js
test/components-browser/index.test.js
test/components-browser/template.component-browser.js
test/components-browser/template.marko

This is building on the changes @DylanPiercey made to get ready for running all our client-only tests in hydrate mode as well.
We'll be going through the each of the failing tests to determine why the test is failing.  
For some of these tests, it's because the assertions need to be different due to the difference in lifecycle (specifically, in hydrate mode, some of the lifecycle happens on the server before mounting in the client).  Other tests might require changes to the testing harness.  There might be a few that don't make sense to run in hydrate mode (maybe?).
We do expect that some of these tests are actual failures though.  For the purposes of this PR, those will be skipped for the time being and we'll address those in future PRs (I already have a branch that addresses some of the …

Hydrate tests

---

src/components/event-delegation.js
src/components/util-browser.js

Verified that this way of getting the runtimeId was not working and this is a
way to have no problems with this.
When injecting marko modules through AJAX (including another marko runtime) there is a collision on the `runtimeId` value. This fixes the event problems by forgetting about runtimeId and just setting the eventKey to a timestamp.
_Disclaimer: Contributions via GitHub pull requests are gladly accepted from their original author. Along with any pull requests, please state that the contribution is your original work and that you license the work to the project under the project's open source license. Whether or not you state this explicitly, by submitting any copyrighted material via pull request, email, or other means you agree to license the material under the project's open …

Fix event collision with multiple runtimes.

---

src/components/legacy/defineWidget-legacy-browser.js
src/components/legacy/renderer-legacy.js

Currently `onBeforeUpdate` is called after updating on legacy components in the compatibility layer.
This changes it to be emitted after rendering but before updating the dom.
Improves legacy compatibility.

Fix onBeforeUpdate call timing for legacy components.

---

src/components/registry-browser.js

Prior to Marko 4.7, if you were using `lasso`, the following was how you would specify components that Marko could not be discovered through static analysis:
_browser.json_
```json
{
"dependencies": [
"require: path/to/component"
]
}
```
`require:` puts the required dependency into the bundle, but doesn’t load it.  And you need use require it using the lasso generated paths.  Marko currently uses lasso paths as component ids, but it shouldn’t rely on this and it also meant that we were very tied to lasso - certain features didn’t work well with other bundlers.
Marko 4.7 moves away from this coupling, but the intention was not to break existing behavior.  This PR adds back support for loading by lasso-specific urls, but logs a deprecation warning.
`lasso-marko@2.4.0` was released at the …

allow loading components by lasso paths, but mark as deprecated

---

test/components-pages/fixtures/preserve-no-update-for-loop/components/root/index.marko
test/components-pages/fixtures/preserve-no-update-for-loop/template.marko
test/components-pages/fixtures/preserve-no-update-for-loop/tests.js
test/components-pages/fixtures/preserve-transcluded-content-on-state-change/components/toggle-button/index.marko
test/components-pages/fixtures/preserve-transcluded-content-on-state-change/template.marko
test/components-pages/fixtures/preserve-transcluded-content-on-state-change/tests.js
test/components-pages/fixtures/preserve-transcluded-key-on-state-change/components/child/index.marko
test/components-pages/fixtures/preserve-transcluded-key-on-state-change/components/container/index.marko
test/components-pages/fixtures/preserve-transcluded-key-on-state-change/components/root/index.marko
test/components-pages/fixtures/preserve-transcluded-key-on-state-change/template.marko
test/components-pages/fixtures/preserve-transcluded-key-on-state-change/tests.js

Updates the failing test cases from #952 #947 and #912 to work with `it-fails`.
These tests were sitting in branches and with our new ability to add failing test cases it made sense to bring them into master.

Add failing test cases from branches.

---

.gitignore
.npmrc
.travis.yml
package-lock.json
src/components/init-components-browser.js
test/components-pages/fixtures/getRenderedWidgets/tests.js
test/express/versions/express-4/package-lock.json
test/express/versions/express-5/package-lock.json

Currently if you run `require('marko/components').init(serverDefs)` multiple times it will error due to using the initial cache of start/end comment nodes. In this PR after the start/end nodes are used they are removed from the lookup which allows subsequent runs to index the new component boundaries. 
This is a regression from around 4.5 where this was technically supported.

Cleanup comment node cache for multiple inits.

---

src/compiler/ast/HtmlElement/vdom/HtmlElementVDOM.js
src/runtime/html/helper-attrs.js
src/runtime/html/helpers.js
src/runtime/vdom/AsyncVDOMBuilder.js
src/runtime/vdom/helper-attrs.js
src/runtime/vdom/helpers.js
test/render/fixtures/dynamic-tag-object-class-style/expected.html
test/render/fixtures/dynamic-tag-object-class-style/template.marko
test/render/fixtures/dynamic-tag-object-class-style/test.js
test/render/fixtures/spread-attribute-class-style-html-tag/expected.html
test/render/fixtures/spread-attribute-class-style-html-tag/template.marko

- Fixes a regression in `<${dynamic}>` tags for object/array class/style attributes:
```marko
$ const style = { color:'blue' };
<${tagName} style=style/>
```
- Allows dynamic attributes defined using `...spread` to include object/array class/style (#933):
```marko
$ const attrs = { style:{ color:'blue' } };
<tag ...attrs/>
```
- Fixes issue where object/array class/style attributes could not be used with `...spread` (#1007):
```marko
$ const attrs = {};
<tag class=["oops"] ...attrs/>
```
_Disclaimer: Contributions via GitHub pull requests are gladly accepted from their original author. Along with any pull requests, please state that the contribution is your original work and that you license the work to the project under the project's open source license. Whether or not you state this …

Dynamic class style

---

docs/marko-vs-react.md

The React and Marko examples are not in 100% parity with each other. It gives the impression that the React example requires more boilerplate than the Marko one. This ensures that the two examples are using the same method and argument names and does the same _kind_ of thing (passing functions into `on-click` properties for example).
The hope is this makes it easier to compare the two frameworks and see their differences.
_Disclaimer: Contributions via GitHub pull requests are gladly accepted from their original author. Along with any pull requests, please state that the contribution is your original work and that you license the work to the project under the project's open source license. Whether or not you state this explicitly, by submitting any copyrighted material via pull request, …

Improve parity between React and Marko example

---

src/components/taglib/TransformHelper/handleScopedAttrs.js
test/components-browser/fixtures/preserve-nodes-update-scoped-elements/index.marko
test/components-browser/fixtures/preserve-nodes-update-scoped-elements/test.js
test/components-compilation/fixtures-html/key-suffix/expected.js
test/components-compilation/fixtures-html/label-for/expected.js

Currently if you have a `:scoped` attribute on an element that scoped attribute will be used as the default key for the element.
IE:
```marko
<label for:scoped="my-input"/>
```
Transforms into:
```marko
<label for:scoped="my-input" key="my-input"/>
```
This causes an issue in a common case where you have a `<label for:scoped` and `<input id:scoped`. This causes both elements to have the same key and cause the matching in the diffing algo to throw away one of them on re-renders.

No longer set scoped attributes as default keys.

---

src/compiler/CompileContext.js
src/compiler/ast/CustomTag.js
src/compiler/ast/HtmlElement/html/StartTag.js
src/compiler/ast/HtmlElement/vdom/HtmlElementVDOM.js
src/runtime/helper-assign.js
test/render/fixtures/spread-attribute-no-mutate/components/test.marko
test/render/fixtures/spread-attribute-no-mutate/expected.html
test/render/fixtures/spread-attribute-no-mutate/template.marko
test/render/fixtures/spread-attribute-order-custom-tag/expected.html
test/render/fixtures/spread-attribute-order-html-tag/expected.html

The spread attribute had been implemented using the `merge` helper, but it works differently to `Object.assign` which is more a `1:1` mapping to the spread concept.  Due in part to this, we were inadvertently causing the spread attributes to have other attributes merged into them - actually mutating the object.
This PR introduces an `assign` helper and uses that instead to merge spread and normal attributes together.  This cleans up the output a bit but also makes the logic around ensuring that we don't mutate simpler.
Fixes #1078 
_Disclaimer: Contributions via GitHub pull requests are gladly accepted from their original author. Along with any pull requests, please state that the contribution is your original work and that you license the work to the project under the project's open …

Fixes #1078 - don't mutate spread attributes

---

src/components/renderer.js
test/components-browser/fixtures/transclusion-rerender-stateful-shared-key/components/container/index.marko
test/components-browser/fixtures/transclusion-rerender-stateful-shared-key/components/counter/index.marko
test/components-browser/fixtures/transclusion-rerender-stateful-shared-key/index.marko
test/components-browser/fixtures/transclusion-rerender-stateful-shared-key/test.js
test/components-browser/fixtures/transclusion-rerender-stateful/test.js

Fixes Issue #1022: Because keys can be repeated in Marko, a component has a KeySequence that keeps track of the number of times a key has been rendered.  This gets reset each time the component is re-rendered, but in the case of transcluded content, the owner component (the component in which a node is defined) is not the only cause of re-renders.  The immediate parent can cause a rerender and in this case, the owner component's KeySequence picks up where it left off, generating incorrect keys.
In practice, this means nodes get thrown away that shouldn't be.  And this is especially problematic when the node that gets thrown away is a stateful component as its internal state gets lost.
This PR fixes this issue by using the immediate parent's KeySequence instead of the owner component's. …

fixes #1022 - transcluded keys don't match, stateful component not preserved

---

src/components/taglib/TransformHelper/assignComponentId.js
test/compiler/fixtures-html/macros/expected.js
test/compiler/fixtures-html/simple/expected.js
test/compiler/fixtures-vdom/simple/expected.js
test/components-browser/fixtures/widget-preserve-all-state-when-rendered-in-loop/index.marko

The fix in #1067 did not cover the `for()` attribute:
```
<div for(x in array)/>
```
Now it does.

fix all for loop types

---

src/compiler/util/parseJavaScript.js
test/components-compilation/fixtures-html/nodejs-8-async-await/expected.js
test/parseFor/fixtures/forEach-invalid-option2/expected.json
test/render/fixtures/error-bad-expression/test.js
test/render/fixtures/error-invalid-else-if-tag/test.js
test/render/fixtures/error-invalid-for-attr/test.js
test/render/fixtures/error-invalid-for-props/test.js
test/render/fixtures/error-invalid-for-range-step/test.js
test/render/fixtures/error-invalid-for-range-to-expr/test.js
test/render/fixtures/error-invalid-for-range/test.js
test/render/fixtures/error-invalid-if-attr/test.js
test/render/fixtures/error-invalid-if-else-attr/test.js
test/render/fixtures/error-invalid-if-else-if-attr/test.js
test/render/fixtures/error-invalid-if-else-if-else-attr/test.js
test/render/fixtures/error-invalid-if-else-if-else-tag/test.js
test/render/fixtures/error-invalid-if-else-if-tag/test.js
test/render/fixtures/error-invalid-if-tag/test.js
test/render/fixtures/error-invalid-unless-tag/test.js

Removes added parenthesis for parsed javascript nodes that Marko doesn't understand.
This was making Marko Prettyprint output additional parenthesis. Also it bloats the output a small amount.

Remove extra parenthesis from compiled javascript.

---

src/compiler/ast/Node.js

Switch to use the node [`util.inspect` symbol](https://nodejs.org/api/util.html#util_util_inspect_custom) for ast nodes.
This symbol is supported in node 6+. Technically this PR could also support node 4, however this still works in node 4 it just doesn't print as pretty. Because it still works I opted to not clutter the codebase for a legacy version of node.
This fixes this deprecation warning `(node:45125) [DEP0079] DeprecationWarning: Custom inspection function on Objects via .inspect() is deprecated`.

Fix node inspect deprecation warning.

---

src/components/Component.js
test/components-browser/fixtures-deprecated/get-el-nested-component/components/child.marko
test/components-browser/fixtures-deprecated/get-el-nested-component/template.marko
test/components-browser/fixtures-deprecated/get-el-nested-component/test.js

Somewhere in 4.5 we removed the ability to get a child components element from `getEl` without deprecating it. This changes brings it back with a deprecation warning.
Fixes #1112

Add back abiity to get child component element from getEl

---

src/runtime/helpers.js
src/runtime/html/helpers.js
src/runtime/vdom/VElement.js
test/render/fixtures/custom-element-assign-props/expected.html

Some object.assign calls made it into the browser code. This removes them.

Remove object.assign from browser code.

---

docs/components.md

Removed two instances of duplicated words, "to to" and "so so"
Found two typos in the components.md document.
Remove them
Typos are bad!
- [ x ] I have read the **CONTRIBUTING** document and have signed (or will sign) the CLA.
- [ x ] I have updated/added documentation affected by my changes.
- [ x ] I have added tests to cover my changes.

Fixed typos in components.md

---

src/compiler/ast/CustomTag.js
src/compiler/ast/HtmlElement/index.js
test/components-browser/fixtures/prevent-input-mutation-repeated-at-tags/components/menu/index.marko
test/components-browser/fixtures/prevent-input-mutation-repeated-at-tags/components/menu/marko-tag.json
test/components-browser/fixtures/prevent-input-mutation-repeated-at-tags/index.marko
test/components-browser/fixtures/prevent-input-mutation-repeated-at-tags/test.js

This PR removes the optimization that reused a spread attribute object if it is the only attribute.
This caused issues around repeated @tags which change the input after this optimization takes place and causes the original input to be mutated.
Partial fix of #1134

Prevent input mutation when repeated attribute tags and spread attributes

---

src/morphdom/index.js
src/taglibs/core/include-tag.js
test/components-pages/fixtures/preserve-looped-attribute-tag/components/child/index.marko
test/components-pages/fixtures/preserve-looped-attribute-tag/components/child/marko-tag.json
test/components-pages/fixtures/preserve-looped-attribute-tag/components/root/index.marko
test/components-pages/fixtures/preserve-looped-attribute-tag/components/root/marko-tag.json
test/components-pages/fixtures/preserve-looped-attribute-tag/template.marko
test/components-pages/fixtures/preserve-looped-attribute-tag/tests.js

In this PR the include tag is updated to get the proper owner component.
Fragments being matched also use an unmodified key.
Partially fixes #1134.

Fix issue with include tag hydration.

---

src/compiler/Parser.js
src/compiler/util/enableTagParams.js
src/components/taglib/TransformHelper/convertToComponent.js
test/compiler/fixtures-html/split-component-root-tag-params-error/components/name/index.marko
test/compiler/fixtures-html/split-component-root-tag-params-error/components/name/marko-tag.json
test/compiler/fixtures-html/split-component-root-tag-params-error/template.component-browser.js
test/compiler/fixtures-html/split-component-root-tag-params-error/template.marko
test/compiler/fixtures-html/split-component-root-tag-params-error/test.js
test/components-pages/fixtures/implicit-component-root-tag-params/components/hello-implicit-component/index.marko
test/components-pages/fixtures/implicit-component-root-tag-params/components/name/index.marko
test/components-pages/fixtures/implicit-component-root-tag-params/components/name/marko-tag.json
test/components-pages/fixtures/implicit-component-root-tag-params/template.marko
test/components-pages/fixtures/implicit-component-root-tag-params/tests.js

Currently we just check if there is a component class when we determine if something is an implicit component. This breaks down with tag params which are typically always stateful and pass new data back up to the parent (the parent renderBody needs to be sent down to the browser).
This PR adds a check for tagParams and bails out of being an implicit component if they exist.
For split components this now throws an error since that typically doesn't make sense with tag params.

Prevent implicit components with tag params

---

src/components/taglib/TransformHelper/getComponentFiles.js

Add support for file name to contain [mobile]

Add support for file name to contain [some word]

---

src/components/Component.js

This PR updates the component rendering logic to preserve a `out["__subtree_context__"]` variable across renders. This is not meant to be used in user land but is used by the upcoming [`<context>`](https://github.com/marko-js/tags/pull/6) tag in [marko-js/tags](https://github.com/marko-js/tags). Currently it is impossible to implement this behavior in user land without this patch, however we do not want to tie Marko to this specific context implementation right away and so it will be trialed in [marko-js/tags](https://github.com/marko-js/tags).
Note:
This PR does not have any tests as those exist in the [marko-js/tags](https://github.com/marko-js/tags) repo.

Provide hidden hook for `<context>` tag.

---

docs/components.md
src/components/ComponentDef.js
test/components-browser/fixtures/scoped-link/component.js
test/components-browser/fixtures/scoped-link/index.marko
test/components-browser/fixtures/scoped-link/test.js

If you add a '#' at the beginning of a scoped attribute the generated id will start with a '#'
I added this functionality because when you use external libraries sometime you need scoped attribute starts with a '#'
```
<div>
<a href:scoped="#anchor">Go to anchor</a>
<div id:scoped="anchor"></div>
</div>
```

added scoped link feature

---

src/compiler/util/parseJavaScript.js
src/taglibs/core/invoke-tag.js
src/taglibs/core/marko.json
src/taglibs/core/root-transformer.js
src/taglibs/core/util/renderCallToDynamicTag.js
test/compiler/fixtures-html/invoke-if/expected.js
test/compiler/fixtures-html/invoke/expected.js
test/compiler/fixtures-html/invoke/template.marko
test/compiler/fixtures-html/render-body-call/expected.js
test/compiler/fixtures-html/render-body-call/template.marko

This builds on top of #1165 and adds the same [imperative rendering]() => [dynamic tag](
https://github.com/marko-js/marko/compare/scriptlet-imperative-rendering-migration?expand=1#diff-0caeb97613de4af96608ae0dd05369a3) transform within scriptlets where possible. This does not account for every scenario but the most prominent ones.
1. `$ input.renderBody(out)` => `<${input}/>`
2. `$ input.renderThing(out)` => `<${input.renderThing}/>`
3. `$ input.renderBody(out, attrs)` => `<${input} ...attrs/>`
4. `$ renderBody(out)` => `<${renderBody}/>`
5. `$ input.template.render({}, out)` => `<${input.template} ...{}/>`
6. `$ input.template.renderer({}, out)` => `<${input.template} ...{}/>`
7. `$ input.barRenderer({}, out)` => `<${{ render:input.barRenderer }} ...{}/>`
8. `$ input.barRenderer({}, …

Convert imperative rendering inside scriptlets to dynamic tags

---

src/compiler/ast/Node.js
test/compiler/fixtures-html/render-body-call/expected.js
test/compiler/fixtures-html/render-body-call/template.marko

Fix parsing `if` without braces:
```marko
$ if (x) doSomething();
```

fix parsing if statements without braces

---

src/compiler/ast/Scriptlet.js
src/taglibs/core/assign-tag.js
src/taglibs/core/var-tag.js
test/compiler/fixtures-html/class-tag/expected.js
test/render/fixtures-deprecated/assign-tag-with-attribute-placeholder/expected.html
test/render/fixtures-deprecated/assign-tag-with-attribute-placeholder/template.marko
test/render/fixtures-deprecated/assign-tag-with-attribute-placeholder/test.js
test/render/fixtures-deprecated/var-with-attribute-placeholder/expected.html
test/render/fixtures-deprecated/var-with-attribute-placeholder/template.marko
test/render/fixtures-deprecated/var-with-attribute-placeholder/test.js
test/vdom-compiler/fixtures/attrs-dynamic/expected.js

Fixes a regression from 4.13.12 where placeholders In `<var>` and `<assign>` tag attributes (eg: `<var x="${y}"/>`).

Fix regression with  function in var/assign tags

---

README.md

I corrected three things in the Readme that I perceive as grammar errors. 
1) This one I am most confident about. I believe the original author meant to say 'Marko also supports' instead of 'Marko also support'.
2) The original author use two adjectives back to back ('beautiful concise'). I believe this is incorrect. Either a comma must be inserted between the two adjectives or the first adjective must become an adverb.
3) I think 'HTML syntax' sounds better than 'The HTML syntax'.
I think having a more pleasing README helps build up a good first impression which helps build a user base. People think that a repo with a good README will have quality maintainers. (and quality maintainers are attracted to repos with good READMEs)
I agree to license this under the terms of this projects open …

Fix grammar errors in the Readme

---

src/compiler/Compiler.js
test/__util__/test-init.js
test/autotest.js

This PR adds support for 3 environment variables to change how our tests run and give us better insight.  All 3 are boolean attributes that, when truthy, trigger the following behavior:
- `MARKO_NO_MIGRATE` causes the migration stage to be skipped
- `EXPECT_DEPRECATED_FAILURES` marks all fixtures in a `*-deprecated` directory as expected to fail
- `COMPLAIN_THROWS` turns all deprecation warnings (which are normally suppressed during testing) into errors that will fail a test
This will disable migrations and expect deprecated tests to fail.  If there are unexpected failures, this means there are tests which are not marked as deprecated that are relying on migrations.  If there are unexpected passes, this means there is code outside the migration stage that is supporting these deprecated …

Env var helpers

---

src/components/legacy/defineRenderer-legacy.js
src/components/legacy/index-browser.js

Currently when calling `setProps` on legacy components they no longer update.

Fix regression with setProps in compatibility layer

---

.gitignore
package-lock.json
package.json
src/compiler/CompileContext.js
src/compiler/index.js
src/components/taglib/TransformHelper/convertToComponent.js
src/components/taglib/TransformHelper/handleLegacyBind.js
src/components/taglib/TransformHelper/index.js
src/components/taglib/widget-types-tag.js
src/taglibs/migrate/common/w-bind.js
test/__util__/patch-module.js
test/migrate/fixtures/w-bind-prompt-n/index.js
test/migrate/fixtures/w-bind-prompt-n/prompt-answers.js
test/migrate/fixtures/w-bind-prompt-n/prompts.js
test/migrate/fixtures/w-bind-prompt-n/snapshot-expected.marko
test/migrate/fixtures/w-bind-prompt-n/template.marko
test/migrate/fixtures/w-bind-prompt-y/index.js
test/migrate/fixtures/w-bind-prompt-y/prompt-answers.js
test/migrate/fixtures/w-bind-prompt-y/prompts.js
test/migrate/fixtures/w-bind-prompt-y/snapshot-expected.js
test/migrate/fixtures/w-bind-prompt-y/snapshot-expected.marko
test/migrate/fixtures/w-bind-prompt-y/template.marko
test/migrate/index.test.js
test/migrate/package.json

In this PR hooks are added to work closer with the [marko migrate](https://github.com/marko-js/cli/blob/master/packages/migrate/README.md) cli, especially around optional / cross file migrations.
Specifically a hook is added to get the compiler context while parsing and a noop function is added to the context which in marko migrate is overwritten to run additional migrations.
This PR also calls out to another optional `componentFile` migration when w-bind is detected with the widget file to migrate. Part of the `w-bind` transformer was moved into a migrator to allow getting the widget file in the migration stage.

Optional migrations & basic w-bind migration

---

src/taglibs/migrate/all-tags/widget-elId.js
test/migrate/fixtures/widget-el-id-scoped/snapshot-expected.marko
test/migrate/fixtures/widget-el-id-scoped/template.marko

Fixes a regression from #1190 where the `widget.elId('name')` migration was not including the `'name'`.

Fix widget el id migration

---

src/runtime/vdom/helper-attrs.js
test/render/fixtures/spread-attribute-undefined/expected.html
test/render/fixtures/spread-attribute-undefined/template.marko

Currently `<div ...undefined>` throws an error as it try's to check for `style` and `class` properties to normalize. I believe this is a regression from https://github.com/marko-js/marko/pull/1058. This PR adds a check for undefined values which fixes the issue.

Fix regression with undefined spread attributes

---

src/compiler/ast/UnaryExpression.js
src/taglibs/migrate/all-tags/control-flow-directives.js
src/taglibs/migrate/all-tags/include-directive.js
src/taglibs/migrate/all-tags/marko-init.js
src/taglibs/migrate/all-tags/w-body.js
src/taglibs/migrate/all-templates/render-calls.js
src/taglibs/migrate/include-tag.js
src/taglibs/migrate/layout-placeholder-tag.js
src/taglibs/migrate/layout-put-tag.js
src/taglibs/migrate/layout-use-tag.js
src/taglibs/migrate/util/import-tag.js
src/taglibs/migrate/util/renderCallToDynamicTag.js
src/taglibs/migrate/var-tag.js
test/codegen/fixtures/body-only-if/expected.js
test/components-compilation/fixtures-html-deprecated/component-include-attr/expected.js
test/components-compilation/fixtures-html/component-include-attr/expected.js
test/components-compilation/fixtures-html/include-input-whitespace-preserved/expected.js
test/components-compilation/fixtures-html/include-whitespace-preserved/expected.js
test/expression-toString/fixtures/UnaryExpression.js/expected.js
test/expression-toString/fixtures/UnaryExpression.js/input.js
test/expression-toString/fixtures/UnaryExpression/expected.js
test/expression-toString/fixtures/UnaryExpression/input.js
test/migrate/fixtures/var-tag/snapshot-expected.marko
test/migrate/fixtures/var-tag/template.marko
test/migrate/fixtures/w-body-attr-val/snapshot-expected.marko
test/migrate/fixtures/w-body-attr-val/template.marko
test/migrate/fixtures/w-body/snapshot-expected.marko

* Fixes control flow attributes on var tag.
* Fixes w-body to ensure that value exists.
* Ensures w-body and include properly enclose typeof expressions.
* Improves printing of unary expressions.
* Refactor `builder.htmlElement` calls to omit optional arguments.

Fix migrator regressions and misc refactoring

---

src/taglibs/migrate/all-tags/w-body.js
test/migrate/fixtures/w-body-attr-val/snapshot-expected.marko

This fixes a regression in w-body where passing the renderBody function directly (eg: `<div w-body=item.renderBody>`) stopped working.

Fix regression with w-body migration

---

src/components/taglib/TransformHelper/assignComponentId.js

This PR removes two pieces of unreachable leftover code from the `ref` attribute migration and the `invoke` tag migration.

Remove legacy invoke and ref code

---

src/components/registry-browser.js

Currently the dev mode `eval`'d component class name can cause a syntax error for components which start with and invalid identifier character (ie: `11-my-item`). This PR helps ensures that the first character is a valid and also wraps the eval in a try catch which falls back to the old behavior.

Fix debug mode eval class name

---

src/taglibs/migrate/util/import-tag.js
test/migrate/fixtures/include-tag/snapshot-expected.marko
test/migrate/fixtures/include-tag/template.marko

Currently when you have:
```
<include("./x")/>
<include("./x")/>
```
the migration stage will output
```
import X from "./x";
import X from "./x";
<${X}/>
<${X}/>
```
Which is invalid.
This PR dedupes these imports and also fixes that snapshot for the tests.

Migrate fix duplicated imports

---

src/taglibs/migrate/all-tags/dynamic-attributes.js
test/migrate/fixtures/dynamic-attributes/snapshot-expected.marko
test/migrate/fixtures/dynamic-attributes/template.marko
test/render/fixtures/attrs/expected.html
test/render/fixtures/script-nonce/expected.html

No matter where the dynamic `${attrs}` are defined, they always have lowest priority.  In the following example, both explicit `foo` and `bar` attributes would overwrite any values in `attrs`.
```marko
<div foo=123 ${attrs} bar=456>Hello World</div>
```
The current migration gives highest priority to these dynamic attributes rather than lowest.

fix dynamic attribute priority

---

src/compiler/CompileContext.js
src/compiler/Normalizer.js
src/components/taglib/components-transformer.js
src/taglibs/migrate/all-tags/w-for.js
src/taglibs/migrate/all-tags/w-id.js
src/taglibs/migrate/all-tags/w-on.js
src/taglibs/migrate/util/findBoundParent.js
test/compiler/fixtures-html/invoke/expected.js
test/components-browser/fixtures-deprecated/widget-transitive-event/test.js
test/components-browser/fixtures-deprecated/widget-transitive-get-el/test.js
test/migrate/fixtures/w-for/snapshot-expected.marko
test/migrate/fixtures/w-id/snapshot-expected.marko
test/migrate/fixtures/w-on/snapshot-expected.marko
test/migrate/fixtures/widget-el-id-scoped/snapshot-expected.marko

This also adds a new concept of "migration flags".  Migration flags are output in the migrated template as a tag (`<marko-migration-flags flag1 flag2 .../>`) and can influence how the template gets compiled.

Fixes #1219 - transitive widget getEl and events

---

src/taglibs/migrate/util/import-tag.js
test/migrate/fixtures/include-tag/snapshot-expected.marko
test/migrate/fixtures/include-tag/template.marko

Fixes a regression which caused invalid identifiers to be output when generating `import` tags during migration.
Fixes #1230

Fix regression with the include tag migration & parent paths

---

src/compiler/ast/Scriptlet.js
src/compiler/ast/TemplateLiteral.js
src/compiler/ast/Vars.js
test/migrate/fixtures/widget-in-attrs/snapshot-expected.marko
test/migrate/fixtures/widget-in-attrs/template.marko
test/vdom-compiler/fixtures/attrs-dynamic/expected.js

`Vars`, `TemplateLiteral` and `Scriptlet` ast nodes did not have a walker implemented which caused some migrations to not work as expected. This PR adds walkers to those nodes.

Fix walkers into some ast nodes

---

src/taglibs/migrate/include-tag.js
test/migrate/fixtures/include-tag/snapshot-expected.marko
test/migrate/fixtures/include-tag/template.marko

Currently the `<include>` migration adds a check for the argument to see if it is a string. This can cause issues if the argument has side effects, eg: `<include(a())/>` `a` is invoked multiple times.
This PR stores complex expressions like this in a var before doing any checks in the migration stage.

Fix regression when migrating include tags with side effects.

---

src/compiler/HtmlJsParser.js
test/migrate/fixtures/non-standard-template-literals/snapshot-expected.marko
test/migrate/fixtures/non-standard-template-literals/template.marko

Currently code using non standard template literals can have values such as `\n` double escaped:
```
<div class="a
b"/>
```
becomes
```
<div class=`a\\nb`/>
```
This PR fixes that issue.

Fix regression with escaped sequences in non standard template literals

---

src/compiler/ast/CustomTag.js
test/compiler/fixtures-html/at-tags-dynamic/expected.js
test/compiler/fixtures-html/at-tags/expected.js
test/compiler/fixtures-html/nested-tag-if-optimization/expected.js
test/compiler/fixtures-html/nested-tag-shorthand-simple-conditional/expected.js
test/compiler/fixtures-html/nested-tags/expected.js

Removes some code that no longer does anything after https://github.com/marko-js/marko/pull/1010/files#diff-896607a8098520717f9f544274619ca2L10 which switched to an alternative solution.

Remove unneeded hasRenderBody check

---

src/compiler/CompileContext.js
src/compiler/ast/HtmlElement/html/StartTag.js
src/runtime/html/helper-merge-attrs.js
src/runtime/html/helpers.js
test/render/fixtures-deprecated/dynamic-attrs-string/expected.html
test/render/fixtures-deprecated/dynamic-attrs-string/template.marko
test/render/fixtures-deprecated/dynamic-attrs-string/test.js

Previously passing a string as a dynamic attribute (`<div ${string}>`) would work on the server side (not client side). A recent migration made it so that this behavior broke server side as well. This PR adds this back on the server with a deprecation warning.

Fix regression with dynamic attributes as a string on server side

---

bin/markoc.js
browser-refresh.js
express.js
helpers/notEmpty.js
hot-reload.js
jquery.marko
node-require.js
ready.marko
src/compiler/Parser.js
src/taglibs/cache/marko.json
src/taglibs/core/marko.json

This PR deprecates some entry points (`jquery` and `ready`) as well as some core tags which will be removed in Marko 5. Comments are added for some additional migrations.

Deprecate some tags, and add notes for future deprecations

---

package-lock.json
package.json
src/compiler/ast/CustomTag.js
src/runtime/helpers.js
test/__util__/runRenderTest.js
test/compiler/fixtures-html/dynamic-tag/expected.js
test/compiler/fixtures-html/import-tag-template/expected.js
test/compiler/fixtures-html/include/expected.js
test/compiler/fixtures-html/invoke/expected.js
test/compiler/fixtures-html/macros/expected.js
test/compiler/fixtures-html/render-body-call/expected.js
test/compiler/fixtures-vdom/dynamic-tag-name/expected.js
test/compiler/fixtures-vdom/include/expected.js
test/compiler/fixtures-vdom/svg-dynamic-tag-name/expected.js
test/components-compilation/fixtures-html-deprecated/component-include-attr/expected.js
test/components-compilation/fixtures-html/auto-key-els/expected.js
test/components-compilation/fixtures-html/component-include-attr/expected.js
test/components-compilation/fixtures-html/include-input-whitespace-preserved/expected.js
test/components-compilation/fixtures-html/include-whitespace-preserved/expected.js
test/components-compilation/fixtures-html/macro-widget/expected.js
test/render/fixtures/dynamic-tag-arguments/components/layout.marko
test/render/fixtures/dynamic-tag-arguments/expected.html
test/render/fixtures/dynamic-tag-arguments/template.marko
test/render/fixtures/dynamic-tag-arguments/test.js

This PR makes it so that all arguments passed to the dynamic tag are prepended to the params available as tag params, that is:
```marko
<${input.renderBody}("a", "b") c d/>
```
When provided a render with params could receive:
```marko
<above-tag|firstArg, secondArg, attrs|>
</above-tag>
```
This means that it is possible via the dynamic tag to reimplement things like `<for|item, index, all|` in userland.
> Note: This is only possible and non breaking because previously `<${dynamic}(arguments)>` did not parse properly. This parsing issue has been resolved, adding support for this with custom tags is not possible as it will be breaking but is planned for Marko 5.

Implement modern arguments support for dynamic tags

---

src/compiler/ast/HtmlElement/html/generateCode.js
test/components-browser/fixtures/event-handler-function/index.marko
test/components-browser/fixtures/event-handler-function/test.js
test/components-compilation/fixtures-html/macro-widget/expected.js

Currently `data-marko` is serialized more than it is needed. It is only needed when we have SSR only / split components. This caused an issue where event handlers that were functions could not be serialized properly and failed to hydrate.
This PR fixes this by only serializing data-marko when needed.

Fix function as event handler when server side rendering

---

src/index.js

Moves the legacy dependencies api (used by older versions of `lasso-marko`) into a block that's guarded by `!process.env.BUNDLE`.  APIs inside this block use dynamic requires and are either intended for development or are legacy apis.  This is needed so that webpack does not throw warnings or errors when building a bundle for node.

move legacy api into guarded block so it's not included in a server bundle

---

src/taglibs/migrate/all-tags/legacy-nested-tag.js
test/migrate/fixtures/legacy-nested-tag/snapshot-expected.marko
test/migrate/fixtures/legacy-nested-tag/template.marko

Fixes false positive warning for legacy nested tags (`<a:b>` instead of `<@b>`) where dynamic tags were used that contained `:`.

Prevent logging false positive deprecations for legacy nested tags

---

src/runtime/html/AsyncStream.js
test/api/fixtures/render-await-client-reorder-unhandled-rejected-promise/template.marko
test/api/fixtures/render-await-client-reorder-unhandled-rejected-promise/test.js

Forward `error` events to the parent out with async content with `client-reorder` set.
Fixes: #1274

Forward error events from nested out of order async outs

---

README.md

Hello!
I've been interested in marko.js so I read README first... then found broken link on 'Examples' section.
Also, I found that several links' scheme is not https.
- Change link from http://markojs.com/docs/components/ (not found) to https://markojs.com/docs/class-components/
- Change several links' scheme from http to https

Modify wrong link to documentation on README

---

src/compiler/ast/HtmlElement/vdom/HtmlElementVDOM.js
test/compiler/fixtures-vdom/svg-title/expected.js
test/compiler/fixtures-vdom/svg-title/template.marko

There is currently a whitelist of tags which can be rendered in the SVG namespace if they are within an SVG. This list was missing `<title>`.
Fixes https://github.com/marko-js/marko/issues/1272

Fix issue with <title> namespace inside an svg

---

docs/class-components.md

`Methods` link got broken after the page name was recently updated.
https://github.com/marko-js/marko/issues/1287

fix broken methods link

---

src/components/ComponentDef.js
src/components/beginComponent.js
src/taglibs/core/marko-tag.js
src/taglibs/core/marko.json
test/components-pages/fixtures/old-hydrate-no-create-no-input/components/child-component/index.marko
test/components-pages/fixtures/old-hydrate-no-create-no-input/components/test-component/index.marko
test/components-pages/fixtures/old-hydrate-no-create-no-input/template.marko
test/components-pages/fixtures/old-hydrate-no-create-no-input/tests.js

Marko 4.9.0 introduced a change to hydration that can cause issues (#1043, #1085).  But the recommended solution (`<marko no-browser-rerender />`) is intended to revert to Pre 4.3.0 behavior and causes a re-render not to happen.
This PR adds the following option to the marko tag.  It is not intended to be used long-term only as a stop-gap.   This PR also adds a deprecation warning for both this new option and `no-browser-rerender`.
```marko
<marko deprecated-no-create-or-input-for-top-level-hydrate /> 
```

add option to revert to old hydrate (pre 4.9) behavior

---

src/compiler/ast/CustomTag.js
src/runtime/helpers.js
test/compiler/fixtures-html/dynamic-tag/expected.js
test/compiler/fixtures-html/import-tag-template/expected.js
test/compiler/fixtures-html/include/expected.js
test/compiler/fixtures-html/invoke/expected.js
test/compiler/fixtures-html/macros/expected.js
test/compiler/fixtures-html/render-body-call/expected.js
test/compiler/fixtures-vdom/dynamic-tag-name/expected.js
test/compiler/fixtures-vdom/include/expected.js
test/compiler/fixtures-vdom/svg-dynamic-tag-name/expected.js
test/components-browser/fixtures/dynamic-tag-no-update-html-attributes/index.marko
test/components-browser/fixtures/dynamic-tag-no-update-html-attributes/test.js
test/components-browser/template.marko
test/components-compilation/fixtures-html-deprecated/component-include-attr/expected.js
test/components-compilation/fixtures-html/auto-key-els/expected.js
test/components-compilation/fixtures-html/component-include-attr/expected.js
test/components-compilation/fixtures-html/include-input-whitespace-preserved/expected.js
test/components-compilation/fixtures-html/include-whitespace-preserved/expected.js
test/components-compilation/fixtures-html/macro-widget/expected.js

Currently if you have a dynamic tag that renders an html element with a `no-update` attribute the attribute will still be updated on new renders. This is a regression from https://github.com/marko-js/marko/blob/master/CHANGELOG.md#4110 (also happens for the include tag since it migrates to the dynamic tag).
This PR passes the properties (containing info like which attributes to preserve) through to the dynamic tag and resolves the issue.

Fix regression for no-update on dynamic tag html attributes

---

docs/webpack.md

loaders is incorrect syntax using latest webpack (4.29.6)

Update webpack property loaders to rules

---

src/components/Component.js
src/morphdom/index.js
test/components-browser/fixtures/adjacent-nested-fragments/components/text-display/index.marko
test/components-browser/fixtures/adjacent-nested-fragments/index.marko
test/components-browser/fixtures/adjacent-nested-fragments/test.js

Currently in situations where there are nested fragments that are siblings it is possible that a fragment will find the incorrect ending marker which can cause strange behavior after hydrating.
This PR resolves the issue by keeping track of the number of open fragments discovered while looking for the end marker.

Fix issue with hydrating nested fragments that are adjacent in the dom

---

src/components/taglib/TransformHelper/assignComponentId.js
test/compiler/fixtures-vdom/macro-in-loop/expected.js
test/compiler/fixtures-vdom/macro-in-loop/template.marko

Currently to keep track of automated keys within loops we automatically prepend a `for scope` key to all keys within the loop. This is unneccesary when a `<macro>` is inside a loop since it will be rendered within a new key namespace anyways.
This PR makes it so that `macro` acts as a boundary when checking to see if the current autokey should be combined with the `for scope`.

Remove redundant part of key path for nested macros

---

src/taglibs/migrate/all-tags/widget-in-attrs.js
test/migrate/fixtures/widget-in-attrs/snapshot-expected.marko
test/migrate/fixtures/widget-in-attrs/template.marko

Not migrated properly, throws an error:
```marko
<var wid=widget.elId()/>
```
This PR fixes it.

fix widget.elId as <var> attribute

---

src/taglibs/migrate/macro-tag.js
test/migrate/fixtures/legacy-macro-syntax/snapshot-expected.marko
test/migrate/fixtures/legacy-macro-syntax/template.marko

In addition to `<macro-body>` a special `renderBody` property used to be injected into the `<macro>` tag.  The migration did not account for this.
```marko
<macro test()>
$ renderBody(out);
</macro>
```

fix macro with injected renderBody migration

---

src/morphdom/specialElHandlers.js
test/morphdom/fixtures/button-element-disabled/expected.html
test/morphdom/fixtures/button-element-disabled/from.html
test/morphdom/fixtures/button-element-disabled/index.js
test/morphdom/fixtures/button-element-disabled/to.html
test/morphdom/fixtures/button-element-enabled/expected.html
test/morphdom/fixtures/button-element-enabled/from.html
test/morphdom/fixtures/button-element-enabled/index.js
test/morphdom/fixtures/button-element-enabled/to.html
test/morphdom/fixtures/input-element-disabled/index.js
test/morphdom/fixtures/input-element-enabled/index.js
test/morphdom/index.test.js

The morphdom implementation in Marko currently supports syncing a predefined set of elements properties (which can be found [here](https://github.com/marko-js/marko/blob/master/src/morphdom/specialElHandlers.js)). This PR adds the `disabled` property from `button` elements to this list.

Sync button disabled attribute

---

src/runtime/html/helper-merge-attrs.js
test/render/fixtures-deprecated/dynamic-attrs-string/expected.html
test/render/fixtures-deprecated/dynamic-attrs-string/template.marko

This PR solves a regression when using the legacy dynamic attribute syntax and passing a string value.
```marko
<div ${"x=1"}/>
```
would output
```marko
<divx=1/>
```
This PR fixes this to ensure that there is always a leading space.

Ensure space when dynamic attributes as string is provided

---

src/components/index.js
test/components-pages/fixtures-deprecated/widget-state-undefined/browser.json
test/components-pages/fixtures-deprecated/widget-state-undefined/components/app-foo/index.js
test/components-pages/fixtures-deprecated/widget-state-undefined/components/app-foo/template.marko
test/components-pages/fixtures-deprecated/widget-state-undefined/marko.json
test/components-pages/fixtures-deprecated/widget-state-undefined/template.marko
test/components-pages/fixtures-deprecated/widget-state-undefined/tests.js

For legacy widget state serialization we have some code which ensures that `undefined` properties are persisted. The loop here had a hoisted variable that could cause a previous element to have incorrectly applied the undefined properties.

Fix issue with Marko@3 widget hydration

---

src/compiler/ast/CustomTag.js
test/compiler/fixtures-html/spread-arguments/expected.js
test/compiler/fixtures-html/spread-arguments/template.marko

Improves argument parsing for dynamic tag and custom tags.
Allows support for `...spread` arguments.

Improve dynamic tag arguments parsing

---

src/hot-reload.js
src/node-require/index.js

Currently `marko.load` can cause issues with hot reloading, especially when `precompiled` files from `Marko CLI` are discovered (or if there is a naming conflict between a marko file and a js file).
This PR ensures that if you are using the require hook that any subsequently loaded template also uses the require hook and makes the `hot-reload` functionality also use the require hook if available.
Fixes #1282.

Fix hot reload

---

src/components/legacy/renderer-legacy.js

Currently with the legacy renderer it is possible to loose the current `componentDef` from the `ComponentsContext` which can cause issues with the dynamic tag (and potentially other issues).
This PR updates the legacy renderer to be more inline with the modern one.

Fix issue with lost component def in legacy renderer

---

src/taglibs/migrate/all-tags/w-body.js
test/migrate/fixtures/w-body/snapshot-expected.marko
test/migrate/fixtures/w-body/template.marko

Improves the output of the `w-body` migration when the `body-only-if(true)` directive is found (this is a common pattern in Marko 3 to avoid having to have a container for the renderBody).
If `body-only-if(true)` is discovered, the parent tag is now omitted from the migrated output.

Improve w-body migration

---

src/runtime/components/Component.js
test/components-browser/fixtures/destroy-cleanup/component.js
test/components-browser/fixtures/destroy-cleanup/index.marko
test/components-browser/fixtures/destroy-cleanup/test.js

When using a library that touches the dom, you might need to cleanup references on destroy, but if the library's cleanup function removes dom nodes, this would cause an issue as Marko gets the list of nodes it needs before the destroy handler is called.  This PR changes the order so that Marko determines which nodes to remove after the destroy handler is called.

fix destorying a component that has already removed some top-level nodes

---

src/compiler/ast/UnaryExpression.js
test/codegen/fixtures/body-only-if/expected.js
test/components-compilation/fixtures-html-deprecated/component-include-attr/expected.js
test/components-compilation/fixtures-html/component-include-attr/expected.js
test/components-compilation/fixtures-html/include-input-whitespace-preserved/expected.js
test/components-compilation/fixtures-html/include-whitespace-preserved/expected.js
test/expression-toString/fixtures/UnaryExpression/expected.js
test/render/fixtures/unary-expression/expected.html
test/render/fixtures/unary-expression/template.marko
test/render/fixtures/unary-expression/test.js

[Previously](https://github.com/marko-js/marko/commit/ff31597a56c6941b8e4da7cebdf61d36829db782#diff-f9b0c7cf6672c52d0c33f85ad8e78be2L50) an optimization was added for printing unary expressions however in some cases this can cause invalid javascript to be printed. This PR reverts that change.

Fix regression with unary expression printing

---

src/compiler/Normalizer.js
test/components-browser/fixtures/tag-params-nested-tags/index.marko
test/components-browser/fixtures/tag-params/index.marko
test/components-pages/fixtures/implicit-component-macro-params/components/hello-implicit-component/index.marko
test/components-pages/fixtures/implicit-component-macro-params/template.marko
test/components-pages/fixtures/implicit-component-macro-params/tests.js

Currently using tag parameters force templates to become components except for the built in modules (for, await, macro). Using a macro that accepts tag parameters is not in this whitelist and causes the whole template to be treated as a component.
In the future this heuristic should improve to actually check with the implementor of the tag params to see if it itself is a component, however for now this PR adds any `macro` usage to this whitelist.

Allow macros with tag params to be implicit components

---

src/core-tags/components/preserve-tag-browser.js
src/runtime/vdom/morphdom/index.js
test/components-browser/fixtures/preserve-dom-body-shared-key/components/child-preserved.marko
test/components-browser/fixtures/preserve-dom-body-shared-key/index.marko
test/components-browser/fixtures/preserve-dom-body-shared-key/test.js

Uses scoped keys for preserved elements.  Using a non-scoped key on the global components context meant there could be collisions where a node might be preserved when it shouldn't have been.

Fix preserve

---

src/compiler/CompileContext.js
src/compiler/Normalizer.js
src/compiler/config.js
test/__util__/runRenderTest.js
test/render/fixtures/escape-at-tag/components/child/index.marko
test/render/fixtures/escape-at-tag/expected.html
test/render/fixtures/escape-at-tag/template.marko
test/render/fixtures/escape-at-tag/test.js

This PR removes the `escapeAtTags` compiler option and partially merges it in with the existing `ignoreUnrecognizedTags` option. It only ever made sense to use these in conjunction and previously it would just hard error if you used `@tags` within a custom tag which you were allowing to pass through (likely for shallow rendering purposes).
With this change, if a tag is allowed through the compiler without finding a match and it has `@tags`, these `@tags` are now automatically allowed to pass through as html tags.
This fixes an issue seen in [marko-tester](https://github.com/oxala/marko-tester) where all `@tags` were ignored blindly which broke the new syntax for the core `await` tag.

Ignore unrecognized tags compiler option now includes @tags

---

src/runtime/components/Component.js
test/components-browser/fixtures-deprecated/get-el-component-key-nested-fragments/components/child/index.marko
test/components-browser/fixtures-deprecated/get-el-component-key-nested-fragments/components/nested-child/index.marko
test/components-browser/fixtures-deprecated/get-el-component-key-nested-fragments/template.marko
test/components-browser/fixtures-deprecated/get-el-component-key-nested-fragments/test.js
test/components-browser/fixtures-deprecated/get-el-nested-fragments/components/child/index.marko
test/components-browser/fixtures-deprecated/get-el-nested-fragments/components/nested-child/index.marko
test/components-browser/fixtures-deprecated/get-el-nested-fragments/template.marko
test/components-browser/fixtures-deprecated/get-el-nested-fragments/test.js

This fixes a regression where `getEl` (or `el`) can possible return a fragment marker when nested fragments are present. With this PR these methods now walk the fragments until finding a normal dom node or undefined.

Walk nested fragments for getEl

---

src/runtime/components/init-components-browser.js
test/components-browser/fixtures/emit-event-during-mount/components/custom-tag/index.marko
test/components-browser/fixtures/emit-event-during-mount/index.marko
test/components-browser/fixtures/emit-event-during-mount/test.js

Currently components are registered into the global component lookup leaf nodes first during mount.
This PR changes it so that all components are registered before mounting. This allows for children to emit events to their parents during the mount phase.

Register components before mounting

---

src/runtime/vdom/morphdom/fragment.js
test/components-browser/fixtures/nested-fragment-namespace/index.marko
test/components-browser/fixtures/nested-fragment-namespace/test.js

A regression was introduced in 4.17 that caused the parent namespaceURI to be missing when the node is inside of a fragment.
This PR adds a namespaceURI property to these fragments which forwards the namespace from the actual parent node.

Fix regression with namespace inside of a fragment

---

src/core-tags/components/helpers/markoKeyAttr.js
test/components-pages/fixtures/getEl-split/components/split-component/index.marko
test/components-pages/fixtures/getEl-split/tests.js

Currently split components with keys that are `repeated[]` do not get properly put into the keyed elements lookup. This PR ensures that the keys are handled the same way as repeated keys on the client.

Fix issue when using getEls with repeated id in a split component

---

src/runtime/components/ComponentDef.js
src/runtime/components/ServerComponent.js
test/components-browser/fixtures-deprecated/component-elId/index.marko
test/components-browser/fixtures-deprecated/component-elId/test.js

Fixes a regression from https://github.com/marko-js/marko/pull/1172 which broke passing non strings as keys. This PR now casts these keys to a string and logs a deprecation warning.
`.elId`'s server implementation was also missed here and so the implementation was copied there. In doing that it looks like previously `.elId(key, index)` was once supported but is not consistent with the client side implementation. This should probably be addressed in a separate PR.
Fixes #1342

Fix and deprecate passing a non string key

---

src/core-tags/components/TransformHelper/assignComponentId.js
src/core-tags/components/TransformHelper/index.js
test/compiler/fixtures-html-deprecated/at-tags-dynamic/expected.js
test/compiler/fixtures-html-deprecated/macros/expected.js
test/compiler/fixtures-html-deprecated/render-body-call/expected.js
test/compiler/fixtures-html-deprecated/simple/expected.js
test/compiler/fixtures-html/at-tags-dynamic/expected.js
test/compiler/fixtures-html/macros/expected.js
test/compiler/fixtures-html/simple/expected.js
test/compiler/fixtures-vdom-deprecated/control-flow/expected.js
test/compiler/fixtures-vdom/macro-in-loop/expected.js
test/compiler/fixtures-vdom/simple/expected.js
test/components-browser/fixtures/for-first-el-key-cache-value/index.marko
test/components-browser/fixtures/for-first-el-key-cache-value/test.js
test/components-compilation/fixtures-html-deprecated/auto-key-els/expected.js
test/components-compilation/fixtures-html-deprecated/macro-component/expected.js
test/components-compilation/fixtures-html/auto-key-els/expected.js
test/components-compilation/fixtures-html/macro-widget/expected.js
test/render/fixtures/for-tag-block-scoped-key/expected.html
test/render/fixtures/for-tag-block-scoped-key/template.marko
test/render/fixtures/for-tag-block-scoped-key/test.js

Fixes a couple of issues regarding for loop auto keying/scoping.
1. Use a unique index for each variable declared (previously was shared with node key indexes).
2. Move key scope var to be just before elements, allowing for key to be defined within the loop (fixes #1345).
3. Ensure that only keys on the first found element are used instead of the first element with keys (prevents issues similar to 2).
4. Cache key into a variable to ensure it is only evaluated once.

Improve for loop auto keying

---

src/runtime/vdom/VElement.js
test/components-browser/fixtures/textarea-value-attribute/index.marko
test/components-browser/fixtures/textarea-value-attribute/test.js

Currently, unlike other attributes, setting `<textarea value=false` will cause a the string `false` to be set as the textarea value (only in the client side).
This PR fixes that to ensure that `false` value is ignored just like other attributes.

Fix issue with setting textarea value to false

---

docs/state.md

docs: typo "to" -> "too"

---

docs/marko-vs-react.md

In the sections with bullet points comparing Marko to React, the closing `**` for the bold labels was in the incorrect place, meaning they weren't bold when rendered.

Fixed bold text in differences

---

src/core-tags/migrate/all-tags/index.js
test/migrate/fixtures/body-only-if/snapshot-expected.marko
test/migrate/fixtures/body-only-if/template.marko

Fixes a regression where a tag with `body-only-if` and a legacy control flow attribute, eg: `<div body-only-if(...) if(...)>` would not migrate properly.

Fix regression with body-only-if and control flow attribute

---

src/runtime/vdom/morphdom/index.js
test/components-browser/fixtures/diffpatch-mismatch-remove-fragment/index.marko
test/components-browser/fixtures/diffpatch-mismatch-remove-fragment/test.js

Currently when nodes are removed inside of a fragment (used by components, macros, and dynamic tag) it is possible for it to remove node's outside of the fragment if there is a next sibling fragment.
This PR checks that a fragment does not remove nodes outside of itself.

Fix issue with removing children inside of fragments

---

docs/installing.md

Add lasso configuration description for "Initializing server-rendered components", let it clearly to read and more easy in practice.
- add lasso configuration description for "Initializing server-rendered components", let it clearly to read and more easy in practice.
- add koa static binding to docs.
When I get started, I found:
- the page I created is rendering in browser without a correct style sheet.
- I have never hear about `lasso`, I didn't known it must config lasso first.
- I get a lot of error when using `app.use(require("lasso/middleware").serveStatic());`,
`app.use(require("lasso/middleware/koa/serveStatic"));` when I run on a Koa server.
This issues waste my half a day.
I finally find a solution, so I update the docs, to let others' time to be save.
This is just a document, so …

docs: add lasso configuration description to installing.md

---

src/compiler/index.js

fix non-existant method call

---

src/core-tags/migrate/layout-put-tag.js
test/migrate/fixtures/layout-put/template.marko

Currently empty layout-put tags get migrated to an empty `@tag` which intern becomes an empty object.
In Marko 3 empty `layout-put`'s are effectively ignored at runtime and so a more compatible migration is to simply remove them.
Currently this can cause issues when it is migrated to a dynamic tag where an empty object (without a renderBody) is passed in because of the empty `layout-put` (causing a runtime error).

Remove empty layout-put tags

---

src/core-tags/migrate/util/renderCallToDynamicTag.js
test/migrate/fixtures/invoke-tag/snapshot-expected.marko
test/migrate/fixtures/invoke-tag/template.marko
test/migrate/fixtures/render-call-in-scriptlet/snapshot-expected.marko
test/migrate/fixtures/render-call-in-scriptlet/template.marko

Currently in some cases the dynamic tag migrations call the renderer with the incorrect `this`.
This PR updates those edge cases to a safe transformation by passing a wrapping function.
Fixes https://github.com/marko-js/marko/issues/1361

Fix issue with render call binding for dynamic tag migration

---

src/core-tags/migrate/invoke-tag.js
test/migrate/fixtures/invoke-tag/snapshot-expected.marko
test/migrate/fixtures/invoke-tag/template.marko

Currently there is a bug with the `invoke` tag migration where it will incorrectly read the attributes before they are normalized by the common transformers.
This causes an issue where an invoke tag contains control flow:
```
<invoke if(x) y()/>
```
Which will error at compile time before this fix.

Fix issue with invoke tag that has control flow

---

src/core-tags/migrate/all-tags/w-id.js
test/migrate/fixtures/w-id/snapshot-expected.marko
test/migrate/fixtures/w-id/template.marko

In Marko 3, `w-id` was used as both a `key` and set a scoped `id`. The `id` was primarily an implementation detail, but it could also be used with `w-for` to associate DOM elements.
Marko 3:
```marko
<label w-for="foo"/>
<input w-id="foo"/>
```
Marko 4 equivalent:
```marko
<label for:scoped="foo"/>
<input key="foo" id:scoped="foo"/>
```
However Marko 4's `:scoped` modifier does not support repeated values.  This is because it's difficult to reason about association of repeated values (the primary use-case fore `:scoped`).  However, this causes the same ids to appear on the page because `:scoped` doesn't have special behavior for `repeated[]` values.
In Marko 3, this association doesn't actually work between repeated `w-id` and `w-for` attributes:
Input template:
```marko
<label …
```

no id:scoped for repeated w-id

---

src/runtime/vdom/morphdom/specialElHandlers.js
test/morphdom/fixtures/select-element-optgroup/expected.html
test/morphdom/fixtures/select-element-optgroup/from.html
test/morphdom/fixtures/select-element-optgroup/index.js
test/morphdom/fixtures/select-element-optgroup/to.html

This PR adds support for controlling `select` elements with nested [`optgroup`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/optgroup) tags.

Add optgroup support for controlled select elements

---

src/compiler/ast/Node.js
src/core-tags/components/init-components-tag.js
src/runtime/components/legacy/renderer-legacy.js
src/runtime/components/renderer.js
src/runtime/html/AsyncStream.js

Currently the `ComponentsContext` is not forwarded when using an `<await client-reorder>` tag.
This PR ensures that `await` tags with `client-reorder` are tracked accordingly which ensures more reliable keys, fixes some issues with hooking up events for split components and fixes some runtime errors that could occur if nesting `await` tags without components in between them.
This PR also contains a `bonus change`™️  which ensures that when creating new AST nodes while copying over body content from another node that the children properly track their new parent node. This fixes some issues with migrations which rely on this and also walk up the ast in some cases.

Fix issue with tracking components for client-reorder await tags

---

src/core-tags/migrate/all-tags/control-flow-directives.js
src/core-tags/migrate/for-tag.js
test/migrate/fixtures/control-flow-directives/snapshot-expected.marko
test/migrate/fixtures/control-flow-directives/template.marko
test/migrate/fixtures/legacy-for-syntax/snapshot-expected.marko
test/migrate/fixtures/legacy-for-syntax/template.marko

This PR fixes two migration issues.
1. Inline control flow directives on control flow tags was erroneously omitted from being migrated. Now only the `<else if(x)>` is not migrated while `<if(x) if(y)>` is migrated.
2. Legacy for loops without a `var` will not still properly migrate to a for tag instead of a `while` tag.

Control flow and looping migration fixes

---

src/compiler/ast/Node.js

Fixes a regression from https://github.com/marko-js/marko/pull/1375/files#diff-73897f1fa5eecec95203fcfbe9e5832eR112. It turns out that the existing behavior of using the same container node instance is relied on and that change causes some nodes to act as if they were removed.
This PR fixes the regression by reusing the array container instance and just changing the owner node.

Fix regression with container nodes

---

src/runtime/components/util-browser.js
test/components-browser/fixtures/get-component-for-el-nested-fragments/components/child/index.marko
test/components-browser/fixtures/get-component-for-el-nested-fragments/index.marko
test/components-browser/fixtures/get-component-for-el-nested-fragments/test.js

Currently `require('marko/components').getComponentForEl` will fail to return a component if there are nested fragments at play. This PR updates the logic to always return the owner component for an element which is simpler and typically what the user wants.

Fix getComponentForEl with nested fragments (returns owner component)

---

src/runtime/components/Component.js
src/runtime/components/legacy/defineRenderer-legacy.js
src/runtime/components/legacy/defineWidget-legacy-browser.js
src/runtime/components/legacy/renderer-legacy.js
src/runtime/vdom/morphdom/index.js

- temporary fix to ensure `getComponents` doesn't return `null` entries - these should really be removed from the `lookup` instead
- use a `for...in` loop to extend the `BaseComponent` (doesn't support getters properly) to maintain the same behavior as `marko-widgets`
- ensure that the original `input` for a widget is what gets serialized, not the result of `getTemplateData` (which is called again when hydrating)
- Bonus Change: rename `isRerenderInBrowser` to `isHydrate`

Legacy compat fixes

---

src/core-tags/migrate/all-tags/body-only-if.js
test/migrate/fixtures/body-only-if-renderer/components/NormalComponent.marko
test/migrate/fixtures/body-only-if-renderer/components/RendererComponent/renderer.js
test/migrate/fixtures/body-only-if-renderer/snapshot-expected.marko
test/migrate/fixtures/body-only-if-renderer/template.marko

Fixes the migration for `body-only-if` when the component is a `renderer.js`

fix body-only-if transform for renderer tags

---

package-lock.json
package.json
scripts/babel-plugin-marko-debug.js
src/compiler/Normalizer.js
src/compiler/ast/CustomTag.js
src/core-tags/migrate/all-tags/params.js
src/core-tags/migrate/all-templates/index.js
src/core-tags/migrate/all-templates/widget-data-is-state.js
src/runtime/components/legacy/dependencies/index.js
test/migrate/fixtures/include-tag/snapshot-expected.marko
test/migrate/fixtures/layout-use/snapshot-expected.marko
test/migrate/fixtures/widget-data-is-state/index.js
test/migrate/fixtures/widget-data-is-state/prompts.js
test/migrate/fixtures/widget-data-is-state/snapshot-expected.js
test/migrate/fixtures/widget-data-is-state/snapshot-expected.marko
test/migrate/fixtures/widget-data-is-state/template.marko

In Marko V3 when you have a widget with `getInitialState` and no `getTemplateData` the `data` variable in the template should equal the `state`. This PR adds an optional widget migration to similar to the one used for `getTemplateData`.

Add migration for legacy widget with `getInitialState` and no `getTemplateData`

---

src/runtime/components/legacy/defineWidget-legacy-browser.js

Previously before the deprecation warning this was configurable, and it was in Marko 3.
This PR improves the compatibility layer with Marko 3.

Make legacy widget property configurable

---

.npmrc
test/__util__/create-marko-jsdom-module.js
test/express/versions/express-4/package.json
test/express/versions/express-5/package.json
test/migrate/package.json
test/node-require/index.test.js
test/render/fixtures-deprecated/inline-script/expected.html
test/render/fixtures-deprecated/inline-script/template.marko
test/render/fixtures-deprecated/inline-script/vdom-expected.html
test/render/fixtures/bodyText/expected.html
test/render/fixtures/bodyText/tags/test-bodyText/code-generator.js
test/render/fixtures/bodyText/vdom-expected.html
test/render/fixtures/inline-script/expected.html
test/render/fixtures/inline-script/template.marko
test/render/fixtures/inline-script/vdom-expected.html
test/render/fixtures/script-string-literal-placeholder/expected.html
test/render/fixtures/script-string-literal-placeholder/template.marko
test/render/fixtures/script-string-literal-placeholder/vdom-expected.html
test/render/fixtures/script-tag-entities-static/expected.html
test/render/fixtures/script-tag-entities-static/tags/test-script/code-generator.js
test/render/fixtures/script-tag-entities-static/vdom-expected.html

Removes unnecessary console output when `npm run test`.
Unfortunately, there are some I was not able to fix:
* Any of the tests expected to fail
* Uncaught jsdom `TypeError`s in `components-browser/fixtures/{split-browser,split-browser-export-class,state-freeze}`
* The output from `[marko/hot-reload]` (didn’t see a way to mock functions in autotest)
* This thing:
```
AsyncStream
[…snip…]
✓ should catch error in promise catch if `error` listener only set inside mixin
(node:41213) UnhandledPromiseRejectionWarning: Error: Should not get here!
at out.catch.then (/Users/tigt/git/marko/test/async-stream/index.test.js:297:19)
at processTicksAndRejections (internal/process/next_tick.js:81:5)
(node:41213) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either …
```

Clean up test noise

---

src/core-tags/migrate/all-tags/index.js
src/core-tags/migrate/all-tags/partial-dynamic-tag.js
test/migrate/fixtures/partial-dynamic-tag/snapshot-expected.marko
test/migrate/fixtures/partial-dynamic-tag/template.marko
test/render/fixtures-deprecated/dynamic-tag-name-concise/expected.html
test/render/fixtures-deprecated/dynamic-tag-name-concise/template.marko
test/render/fixtures-deprecated/dynamic-tag-name-concise/test.js
test/render/fixtures-deprecated/dynamic-tag-name-concise/vdom-expected.html
test/render/fixtures-deprecated/dynamic-tag-name/expected.html
test/render/fixtures-deprecated/dynamic-tag-name/template.marko
test/render/fixtures-deprecated/dynamic-tag-name/test.js
test/render/fixtures-deprecated/dynamic-tag-name/vdom-expected.html
test/render/fixtures/dynamic-tag-name-concise/expected.html
test/render/fixtures/dynamic-tag-name-concise/template.marko
test/render/fixtures/dynamic-tag-name-concise/vdom-expected.html
test/render/fixtures/dynamic-tag-name/expected.html
test/render/fixtures/dynamic-tag-name/template.marko
test/render/fixtures/dynamic-tag-name/vdom-expected.html

This PR deprecates and adds an auto migration for the `<partial-${dynamic}>` tag.
It is not currently documented that this is possible, and an alternative syntax already exists `<${"partial-" + dynamic}>`

Deprecate the partial dynamic tag

---

src/runtime/components/beginComponent.js
src/runtime/components/legacy/renderer-legacy.js
test/components-browser/fixtures-deprecated/widget-conditional/test.js
test/components-browser/index.test.js
test/components-browser/template.component-browser.js
test/components-browser/template.marko

Adds support to the compatibility layer for conditional widgets rendered on the server.
```marko
<widget-types default="./"/>
<div w-bind=(data.includeWidget ? 'default' : null)>
...
</div>
```
Fixes the existing failing test.

fix server-rendered conditional widgets in the compatibility layer

---

src/loader/browser.json
src/loader/index-browser-dynamic.js
src/loader/index-browser.js
src/runtime/components/legacy/index-browser.js

Removes Webpack warnings about dynamic requires for legacy components by checking for `__webpack_require__`.

Improve webpack compatibility for legacy components.

---

docs/marko-json.md

I noticed the compiler put up red shouting when a `"required"` attribute wasn’t defined.

"required" does in fact do something

---

src/runtime/html/helper-attr.js
src/runtime/vdom/VElement.js
test/render/fixtures/pattern-attr-runtime/expected.html
test/render/fixtures/pattern-attr-runtime/template.marko
test/render/fixtures/pattern-attr-runtime/test.js
test/render/fixtures/pattern-attr-runtime/vdom-expected.html

If the attribute was a literal, it would work:
```marko
<input type="text" pattern=/\w{2,20}/ />
```
Prior to this PR, a non-literal regex did not work:
```marko
<input type="text" pattern=(true && /\w{2,20}/) />
<input type="text" pattern=regex />
```
Now it does.

fix regex attribute that's not static

---

src/loader/index-default.js
test/api/fixtures/load-prefer-precompiled/dummy.js

The `marko.load` api currently checks for a JS file with the same name as the marko file being loaded (`index.marko` -> `index.js`) and loads the JS file if found, assuming it is a precompiled version of the template.  
This PR adds an additional check for Marko's comment banner: 
```js
// Compiled using marko@x.x.x - DO NOT EDIT
```

improve precompiled heuristic to check for banner comment

---

src/compiler/Normalizer.js
test/render/fixtures/comments-preserve-ie-conditional/expected.html
test/render/fixtures/comments-preserve-ie-conditional/template.marko
test/render/fixtures/comments-preserve-ie-conditional/vdom-expected.html

Fixes #1425 - comment conditionals that span multiple comments were not being preserved.

Improve conditional comment support

---

src/runtime/vdom/morphdom/fragment.js
src/runtime/vdom/morphdom/index.js

Fixes #1290
This now works:
```marko
class {
onCreate() {
this.state = { count:0 }
}
increment() {
this.state.count++;
}
}
<!doctype html>
<html>
<head>
<title>${state.count}</title>
</head>
<body>
<h1>Hello ${state.count}</h1>
<button on-click("increment")>increment</button>
</body>
</html>
```

support components that contain <html>/<!doctype>

---

src/core-tags/html/marko.json
src/core-tags/html/normalize-script-text.js
test/compiler/fixtures-vdom/script-placeholders/expected.js
test/compiler/fixtures-vdom/script-placeholders/template.marko

Prior to this change, the following would have 3 text nodes, now it has 1.
```marko
<script>
var x = ${JSON.stringify(value)}
</script>
```
If the text nodes are inserted into the script sequentially while it's in the document, this would cause the execution of incomplete code, throwing a SyntaxError.

scripts now always generate a single text child - even if they have placeholders

---

src/runtime/components/dom-data.js

Rollup does not play well with `require.resolve` which we are using in the `dom-data` weak polyfill.
This PR updates the seed for these fake weak maps to use the client side runtime id instead which is guaranteed unique across multiple instances of Marko on the page.

Remove require.resolve from dom-data for improved rollup support

---

src/runtime/components/legacy/defineRenderer-legacy.js
src/runtime/components/legacy/renderer-legacy.js

`widgetProps` is added to `data` while rendering with `marko-widgets@6`. This PR updates the MarkoV3 compatibility layer to use the same name and exposes `widgetProps` on `input` for legacy components.

Rename private legacy widget props property for better legacy compat

---

src/runtime/components/util-browser.js

Slight improvements to the `getComponentForEl` helper which:
1. No longer throws if the node is not under a component.
2. Returns the owner component for all `Element` or `Fragment` nodes.

Improve getComponentByEl lookup to prefer owner components

---

src/compiler/ast/Macro.js
src/compiler/ast/TemplateRoot.js
test/compiler/fixtures-vdom/macro-in-loop/expected.js

Allows `<macro>` tags to be nested in the template by disabling the addition of `"use strict";` to the compiled output.

disable strict mode if a macro is not at the root

---

src/taglib/taglib-loader/Tag.js

Currently in Windows `core-tags` will log deprecation warnings which is unexpected due to a path issue. This PR updates the `isCoreTag` to check paths in a way that works on Windows.
Fixes: #1438

Fix invalid deprecation message for core-tags on windows

---

src/core-tags/core/await/renderer.js

Make sure that we have a correct stack trace during async rendering in dev

---

src/core-tags/core/await/renderer.js
test/render/fixtures/await-error-empty-catch/expected.html
test/render/fixtures/await-error-empty-catch/template.marko
test/render/fixtures/await-error-empty-catch/vdom-expected.html
test/render/fixtures/await-error-no-catch/template.marko
test/render/fixtures/await-error-no-catch/test.js
test/render/index.test.js

Allows an empty `<@catch/>` to swallow errors.
```marko
<await(Promise.reject(new Error("Something went wrong!")))>
<@then|testData|>Success!</@then>
<@catch/>
</await>
```

allow empty <@catch> to swallow errors

---

package-lock.json
package.json
src/compiler/Builder.js
src/compiler/ast/Expression.js
src/compiler/util/parseJavaScript.js
src/compiler/util/parseJavaScriptArgs.js
src/compiler/util/parseJavaScriptParams.js
src/runtime/components/Component.js
test/components-browser/fixtures/set-null-state/index.marko
test/components-browser/fixtures/set-null-state/test.js

In order to support the new state tag, I had to fix a couple of things in the old marko v4 version.
* Added expression statements to have ast
* Added a change on `setState` to initialize the state if it's null
* Upgraded estraverse to the latest version (for traversing esprima ast)

Added support for state tag

---

src/runtime/components/legacy/package.json

Fixes a regression from #1468 which removed a browser remap that is used via `marko-widgets` (compatibility layer).

Fix regression with browser remap for legacy widgets

---

src/runtime/components/legacy/defineRenderer-legacy.js
test/components-browser/fixtures-deprecated/widget-config-render-lifecycle/index.js
test/components-browser/fixtures-deprecated/widget-config-render-lifecycle/template.marko
test/components-browser/fixtures-deprecated/widget-config-render-lifecycle/test.js

Makes the legacy render lifecycle match that of Marko Widgets 6:
**Marko Widgets 6**:
getInitialProps
getInitialState
getTemplateData
getWidgetConfig
**Marko 4 (before this PR):**
getInitialProps
getWidgetConfig
getInitialState
getTemplateData

fix legacy render lifecycle order to match marko-widgets@6

---

src/runtime/components/legacy/defineRenderer-legacy.js
src/runtime/components/legacy/renderer-legacy.js

Currently passing in a null key will throw an error in the compatibility layer. This is transparently handled In the modern runtime and in the current v3 implementation.
Ideally this should log a warning in the future.

Support having nullish keys in the legacy compatibility layer

---

src/runtime/components/Component.js

Prior to this PR, `component.elId()`/`component.getElId()` (no args) returned something like `c0-undefined`, where it should have simply returned `c0`.

return the component id if no key is passed to getElId/elId

---

src/runtime/components/legacy/defineWidget-legacy-browser.js
test/components-browser/fixtures-deprecated/widget-state-assignment-merge/index.js
test/components-browser/fixtures-deprecated/widget-state-assignment-merge/template.marko
test/components-browser/fixtures-deprecated/widget-state-assignment-merge/test.js

In Marko 3 using `widget.state = newState` caused `newState` to be merged into the existing state. This behavior changed in Marko 4 to replace the existing state. This PR improves the v3 compatibility layer to merge assigned state in the legacy compatibility mode.

Merge new state on assignment for legacy widgets

---

src/core-tags/migrate/all-tags/w-bind.js

Currently the `w-bind` migration for legacy widgets looks for `index.js` and `widget.js` to determine if a component is split. However we were only looking for the`defineComponent` (`index.js`) when `w-bind` without a value was used.
This PR accounts for cases like `w-bind="index"` which we assume is a `defineComponent` and should not be split.

Fix resolving renderer path for legacy widgets

---

src/core-tags/components/TransformHelper/assignComponentId.js
src/core-tags/components/TransformHelper/handleComponentPreserve.js
src/core-tags/components/TransformHelper/index.js
src/core-tags/components/helpers/markoKeyAttr.js
src/core-tags/components/preserve-tag-browser.js
src/core-tags/components/preserve-tag.js
src/runtime/components/ComponentDef.js
src/runtime/components/GlobalComponentsContext.js
test/components-compilation/fixtures-html-deprecated/auto-key-els/expected.js
test/components-compilation/fixtures-html/auto-key-els/expected.js
test/components-pages/fixtures/preserve-server-rendered-content-on-mount/components/root/index.marko
test/components-pages/fixtures/preserve-server-rendered-content-on-mount/template.marko
test/components-pages/fixtures/preserve-server-rendered-content-on-mount/tests.js

Currently when using `no-update` on the server side, whatever you have will be thrown away when rerendering in the browser.
This PR updates `no-update` to preserve that content when hydrating.

Preserve SSR content with no-update

---

src/runtime/components/legacy/defineRenderer-legacy.js
src/runtime/components/legacy/defineWidget-legacy-browser.js

Improves v3 compatibility by supporting input with `getTemplateData(state, input, out)` on state based rerenders.

Preserve legacy widget input when rerendered

---

src/runtime/vdom/VNode.js
src/runtime/vdom/morphdom/specialElHandlers.js

Fixes a regression caused by #1480 which broke `<textarea no-update-body>`.

Fix regression with no-update-body on script tags

---

src/runtime/components/beginComponent.js
test/components-pages/fixtures/no-update-component/components/counter/index.marko
test/components-pages/fixtures/no-update-component/template.marko
test/components-pages/fixtures/no-update-component/tests.js

After #1480 top level components under a `no-update` root were not mounting properly.
This ensures that those components are initialized independently of their parent.

Fix issue with ssr'd components under 'no-update' not initializing

---

src/runtime/components/ready.js

Currently if a legacy widget overrides the `ready` method it will not work.
This PR improves consistency with Marko 3 components by allowing it to be overwritten.

Support overriding the 'ready' method in legacy widgets

---

src/core-tags/components/preserve-tag.js

Fixes an issue from #1480 where multiple nested `w-preserve`'s or `no-update`'s are present. There was an assumption made that everything was static under a no-update tag, however components can continue to update. When they do update, they could be incorrectly diffed since the fragment created on the browser was not done on the server.
This PR ensures the same structure is used in both the server and the browser.

Fix issue with no-update and nested components

---

src/runtime/components/legacy/defineWidget-legacy-browser.js

`this.el` was un-deprecated on modern components after https://github.com/marko-js/marko/pull/1341. This change did not carry over to the compatibility layer which still logs the warning.
In compatibility mode `this.el` returns the `w-bind` widget instead of the first element which differs from Marko 4. This PR updates the legacy compatibility warning to only display if the `w-bind` element is not also the first element when `this.el` is accessed.

Improve warning for 'this.el' in legacy components

---

src/compiler/ast/CustomTag.js
src/runtime/helpers/_change-case.js
src/runtime/helpers/dynamic-tag.js
src/runtime/helpers/style-value.js
src/runtime/html/helpers/attrs.js
src/runtime/vdom/helpers/attrs.js
test/render/fixtures/attrs-normalize-for-native-tag/components/custom-tag/index.marko
test/render/fixtures/attrs-normalize-for-native-tag/expected.html
test/render/fixtures/attrs-normalize-for-native-tag/template.marko
test/render/fixtures/attrs-normalize-for-native-tag/test.js
test/render/fixtures/attrs-normalize-for-native-tag/vdom-expected.html
test/render/fixtures/attrs-with-render-body/components/custom-tag/index.marko
test/render/fixtures/attrs-with-render-body/expected.html
test/render/fixtures/attrs-with-render-body/template.marko
test/render/fixtures/attrs-with-render-body/test.js
test/render/fixtures/attrs-with-render-body/vdom-expected.html

Currently the behavior when spreading attributes meant for a custom tag into a native tag can be surprising.
This PR improves the support by:
1. `renderBody` attributes passed to native tags is now ignored.
2. `camelCase` properties are now consistently converted to dash case.
This PR also fixes the following:
1. Prevent spread attributes from being mutated if a `renderBody` exists.
2. A direct renderBody to the dynamic tag now correctly takes precedence over one passed via regular input (spread).
resolves #1485 
resolves #824

Improve consistency with spread attributes

---

src/runtime/components/legacy/defineWidget-legacy-browser.js

Prior to this change, a widget def like this will go into an infinite look because the `defineWidget` helper set the constructor to the init property.  This PR makes it so Marko doesn't modify the widget prototype in this case.
```js
class Widget {
constructor() {
this.init()
}
init() {
// do stuff
}
}
```

don't modify the widget prototype for init

---

src/runtime/components/index.js
src/runtime/components/renderer.js

`___updatedInput` and `___updateQueued` are not needed in the hydration data.  We shouldn't serialize them.

remove unused properties from component hydration data

---

src/compiler/ast/HtmlElement/html/generateCode.js
test/components-pages/fixtures/no-update-with-an-event/components/counter/index.marko
test/components-pages/fixtures/no-update-with-an-event/template.marko
test/components-pages/fixtures/no-update-with-an-event/tests.js

Currently if you have a some content under a `no-update` section with an event handler which is initially rendered on the server it can fail to register the event.
This is related to the changes in https://github.com/marko-js/marko/pull/1480
Fixes #1492

Fix issue with registering events under a 'no-update' when server rendered

---

src/runtime/components/Component.js
src/runtime/components/legacy/defineWidget-legacy-browser.js
test/components-browser/fixtures-deprecated/widget-lifecycle-events-stateful-conditional-bind/index.js
test/components-browser/fixtures-deprecated/widget-lifecycle-events-stateful-conditional-bind/lifecycle-recorder.js
test/components-browser/fixtures-deprecated/widget-lifecycle-events-stateful-conditional-bind/template.marko
test/components-browser/fixtures-deprecated/widget-lifecycle-events-stateful-conditional-bind/test.js

Fixes case where a legacy widget is bound within an if statement, eg
```marko
<if(input.show)>
<div w-bind>
...
```

Improve support for conditional w-binds in legacy widgets

---

src/runtime/helpers/dynamic-tag.js

Currently the `body-only-if` migration outputs `{ renderer: dynamicTagValue }` when the tag being converted has a renderer to avoid the dynamic tag thinking it is a renderBody since https://github.com/marko-js/marko/pull/1384. This causes a regression if you specify a component/legacy widget as the renderer.
This PR adds a check in the dynamic tag runtime to see if the `renderer` was a another tag and renders it as a tag instead. It also logs a deprecation in this case.

Fix regression with body-only-if migration for legacy renderers

---

src/runtime/vdom/helpers/attrs.js
test/components-browser/fixtures/component-toggle-spread-attributes/component.js
test/components-browser/fixtures/component-toggle-spread-attributes/index.marko
test/components-browser/fixtures/component-toggle-spread-attributes/test.js

The changes in #1488 caused an issue where spread attributes passed to an element without a key would no longer be omitted if set to `null` or `false`. This is because the [assumption here](https://github.com/marko-js/marko/blob/master/src/runtime/vdom/VElement.js#L381) was broken.
- [ x I have added tests to cover my changes.

Fix regression for unkeyed elements with toggled spread attributes

---

src/runtime/components/legacy/renderer-legacy.js

In Marko 3 split components do not have access to their `input`, however modern split components do. This PR prevents serializing input for legacy split components to increase performance in that case.
This is a subset of https://github.com/marko-js/marko/commit/f4f89c93046b4958052832ec44d1afb9980d558f

Prevent serializing input for legacy split widgets

---

src/core-tags/components/preserve-tag.js

This fixes an issue where `no-update` can cause the structure to change in a browser vs a server render causing some SSR'd dom to be incorrectly removed. Now we always output fragment markers for SSR'd no-update content to maintain a consistent structure.

Always output no-update fragment on the server

---

src/core-tags/components/init-components-tag.js

The `<init-components>` tag previously on being rendered under the top level `out` however this was fixed in https://github.com/marko-js/marko/pull/1441. The fix however has a typo which caused it to only walk up one nested out. This PR fixes the typo and resolves the original issue.

Fix issue with init-components inside nested awaits

---

packages/marko/src/compiler/index.js
packages/translator-default/src/cdata/index[html].js
packages/translator-default/src/cdata/index[vdom].js
packages/translator-default/src/comment/index[html].js
packages/translator-default/src/declaration/index[html].js
packages/translator-default/src/document-type/index[html].js
packages/translator-default/src/placeholder/index[html].js
packages/translator-default/src/placeholder/index[vdom].js
packages/translator-default/src/tag/attribute-tag.js
packages/translator-default/src/tag/attribute/directives/class.js
packages/translator-default/src/tag/attribute/directives/style.js
packages/translator-default/src/tag/attribute/modifiers/scoped.js
packages/translator-default/src/tag/custom-tag.js
packages/translator-default/src/tag/dynamic-tag.js
packages/translator-default/src/tag/native-tag[html]/index.js
packages/translator-default/src/tag/native-tag[vdom]/index.js
packages/translator-default/src/taglib/core/conditional/util.js
packages/translator-default/src/taglib/core/macro/translate.js
packages/translator-default/src/taglib/core/translate-while.js
packages/translator-default/src/taglib/migrate/all-templates.js
packages/translator-default/src/text/index[html].js
packages/translator-default/src/text/index[vdom].js
packages/translator-default/src/util/with-previous-location.js

During the translate stage the new Marko compiler inserts a bunch of new art nodes. These nodes lose track of the source position intended for that operation which causes the debugger to jump in and out of a source mapped file. This PR updates most nodes inserted during this stage to map to an appropriate location in the source.
It also includes a fix where the sourcemaps were not being exposes properly with the legacy compiler api.

fix: improve node locations in sourcemaps

---

packages/marko/src/core-tags/components/preserve-tag.js
packages/marko/src/runtime/components/ComponentDef.js
packages/marko/src/runtime/components/ComponentsContext.js
packages/marko/src/runtime/components/beginComponent-browser.js
packages/marko/src/runtime/components/beginComponent.js
packages/marko/src/runtime/components/endComponent.js
packages/marko/src/runtime/html/helpers/data-marko.js
packages/marko/test/components-browser/fixtures-deprecated/preserve-with-nested-rerender-root/components/counter/index.js
packages/marko/test/components-browser/fixtures-deprecated/preserve-with-nested-rerender-root/components/counter/template.marko
packages/marko/test/components-browser/fixtures-deprecated/preserve-with-nested-rerender-root/index.marko
packages/marko/test/components-browser/fixtures-deprecated/preserve-with-nested-rerender-root/test.js

1. Uses the `componentsContext` rather than `globalComponentsContext` to track whether a section is preserved.  The `componentContext` is a more true context and maintains values for async parts of the render.
2. When entering a stateful component, it becomes a new render root and children of this component should not be preserved.  This fixes the following issues in preserved subtrees:
- Legacy widgets output `data-marko` attributes and root widgets claim the keyed elements, which causes errors during hydration.
- Split components under a stateful component output `data-marko` attributes, but since they do not claim the keyed elements due to not being roots, there is no observable impact other than increased HTML size.

Fix preserve context

---

packages/marko/src/runtime/components/index.js

Currently it is possible for a nested components context to be created without a parent component. The legacy `getInitWidgetsCode` and modern `writeInitComponentsCode` api's can fail to write out the initialization code for these nested contexts if the top level out is passed in.
This PR makes sure to visit nested contexts when serializing regardless of whether or not there are top level components.

fix: always include nested contexts when serializing

---

packages/marko/src/runtime/components/legacy/defineWidget-legacy-browser.js
packages/marko/test/components-browser/fixtures-deprecated/widget-lifecycle-events-stateful-conditional-bind-monkey-patched/index.js
packages/marko/test/components-browser/fixtures-deprecated/widget-lifecycle-events-stateful-conditional-bind-monkey-patched/lifecycle-recorder.js
packages/marko/test/components-browser/fixtures-deprecated/widget-lifecycle-events-stateful-conditional-bind-monkey-patched/template.marko
packages/marko/test/components-browser/fixtures-deprecated/widget-lifecycle-events-stateful-conditional-bind-monkey-patched/test.js

In v3 components it is possible to dynamically set lifecycle methods during runtime eg:
```
module.exports = require("marko-widgets").defineComponent({
template: require("./template.marko"),
init() {
this.onBeforeDestroy = function () { ... }
}
})
```
This PR updates these remapped lifecycle methods in the compatibility layer to have a setter in order to support this anti pattern.

fix: support monkey patching lifecycle methods for legacy widgets

---

packages/marko/src/compiler/CompileContext.js
packages/marko/src/core-tags/migrate/for-tag.js
packages/marko/test/migrate/fixtures/legacy-for-range-widget/snapshot-expected.marko
packages/marko/test/migrate/fixtures/legacy-for-range-widget/template.marko

In Marko 3 the `for from to` loop would iterate differently depending on if the `to` was able to be statically evaluated than if it was dynamic. This was obviously bad, but this PR brings back that behavior when we detect a template is using legacy widget features to improve compatibility.

fix: improve support for legacy widget for range

---

packages/marko/src/runtime/components/legacy/index-browser.js

In `marko-widgets@6` there was an alias for `getWidgetForEl` of `get`. This alias was not added in the compatibility layer (`marko-widgets@7`).

fix: add 'get' API for marko-widgets compat

---

packages/marko/src/runtime/html/helpers/attrs.js
packages/marko/src/runtime/vdom/helpers/attrs.js
packages/marko/test/render/fixtures/attrs-normalize-for-native-tag/expected.html
packages/marko/test/render/fixtures/attrs-normalize-for-native-tag/template.marko
packages/marko/test/render/fixtures/attrs-normalize-for-native-tag/vdom-expected.html

Fixes a regression from #1488 which incorrectly normalized native tag attributes when using `...spread`.
Resolves https://github.com/marko-js/marko/issues/1529

fix: spread attrs for native tag preserves case

---

packages/marko/src/core-tags/migrate/for-tag.js
packages/marko/src/runtime/helpers/for-range.js
packages/marko/test/compiler/fixtures-html-deprecated/render-body-call/expected.js
packages/marko/test/migrate/fixtures/legacy-for-syntax/snapshot-expected.marko
packages/marko/test/migrate/fixtures/render-call-in-scriptlet/snapshot-expected.marko

Currently some of the old for loop syntax is migrated to use a `<for|i| from=a to=b>` loop. This however has caused some issues around how the range loop works by automatically iterating in reverse if `from` is less than `to`. This PR updates the for range logic to prevent this reversing of direction when an explicit step is supplied, and updates the migrator to provide the step in the case that it is needed.

fix: prevent issue with range loop iterating in reverse

---

packages/marko/src/runtime/components/legacy/index-browser.js

Fixes an issue for the legacy `require("marko-widgets").getWidgetForEl` which was not correctly returning the `w-bind` widget for an element in some cases.

fix: improve legacy compatibility with getWidgetForEl api

---

packages/marko/src/compiler/ast/HtmlAttribute/html/generateCode.js
packages/marko/src/runtime/components/Component.js
packages/marko/src/runtime/components/ComponentDef.js
packages/marko/src/runtime/components/GlobalComponentsContext.js
packages/marko/src/runtime/components/KeySequence.js
packages/marko/src/runtime/components/ServerComponent.js
packages/marko/src/runtime/components/dom-data.js
packages/marko/src/runtime/components/index.js
packages/marko/src/runtime/components/legacy/renderer-legacy.js
packages/marko/src/runtime/components/registry.js
packages/marko/src/runtime/components/renderer.js
packages/marko/src/runtime/helpers/_weak-map.js
packages/marko/src/runtime/helpers/dynamic-tag.js
packages/marko/src/runtime/html/StringWriter.js
packages/marko/src/runtime/html/helpers/attr.js
packages/marko/src/runtime/html/helpers/attrs.js
packages/marko/src/runtime/html/helpers/escape-xml.js
packages/marko/src/runtime/html/helpers/props-script.js
packages/marko/src/runtime/vdom/morphdom/index.js
packages/marko/test/render/fixtures-deprecated/attrs/expected.html
packages/marko/test/render/fixtures/attr-escape-xml/expected.html
packages/marko/test/render/fixtures/attr-escape-xml/template.marko
packages/marko/test/render/fixtures/attr-escape-xml/vdom-expected.html
packages/marko/test/render/fixtures/attrs/expected.html

Many of these performance improvements are targeted toward legacy components, however some also improve modern components.
Legacy widget improvements include:
* Serializing legacy body content & widgetConfig now use less bytes.
* Legacy components no longer necessarily serialize an empty object for component props (this is now skipped for legacy components)
* Legacy components no longer serialize `null` for input, instead use `0`.
Modern component improvements include:
* Places where a `nonce` is added to scripts now uses the optimized double quote escape instead of `JSON.stringify`.
* Simplified key sequence code and use null prototype objects where possible.
* Server component simplified to use noops for missing lifecycle methods.
* Dynamic tag can now better tell apart user keys from …

Misc perf improvements

---

packages/marko/src/compiler/CodeWriter.js
packages/marko/src/compiler/CompileContext.js
packages/marko/src/compiler/ast/HtmlElement/html/generateCode.js
packages/marko/src/compiler/ast/HtmlElement/index.js
packages/marko/src/compiler/ast/HtmlElement/vdom/generateCode.js
packages/marko/src/compiler/ast/TemplateLiteral.js
packages/marko/src/compiler/util/discover-branch-types.js
packages/marko/test/codegen/fixtures/htmlElement-dynamic/expected.js
packages/marko/test/codegen/fixtures/templateLiteral/expected.js
packages/marko/test/compiler/fixtures-vdom/dynamic-tag-name/expected.js
packages/marko/test/compiler/fixtures-vdom/svg-dynamic-tag-name/expected.js

Perf improvement: Attempt to determine if a dynamic tag is can only be a native tag, and if so output using string concat on the server (and `out.e`/`be` in the browser) instead of using the dynamic tag helper.

perf: attempt to determine dynamic native tag, string concat if so

---

packages/marko/src/runtime/html/AsyncStream.js

The `voidWriter` is used on the server side to handle when there is an uncaught exception and we are now writing to dead stream. It allows us to gracefully handle that case (since the actual error should have surfaced somewhere else) and also does not buffer anything written after that point.
The `StringWriter` and `BufferedWriter` implementations recently got new methods to better handle concatenating component logic and handling batched flushes. These are missing from the `voidWriter`.
This PR adds those missing methods as `noop`'s to the `voidWriter`.

fix: implement missing methods for void-writer

---

packages/marko/src/runtime/components/util-browser.js
packages/marko/src/runtime/components/util.js
packages/marko/src/runtime/vdom/morphdom/fragment.js
packages/marko/src/runtime/vdom/morphdom/index.js

This adds additional checks in dev mode to give more context to the user as to why diffing failed when the DOM has been updated manually and fragment markers (empty text nodes) were removed.
Instead of throwing `TypeError: Cannot read property 'nextSibling' of null`, it now throws `Error: Cannot get fragment nodes. Boundary markers missing.`.  In addition to the new error text, a second error is passed to `console.warn` showing the location where the fragment marker was removed.

fix: add devmode warning for removing fragment markers

---

packages/marko/src/runtime/components/legacy/defineWidget-legacy-browser.js
packages/marko/test/components-browser/fixtures-deprecated/widget-class-init-loop/template.marko
packages/marko/test/components-browser/fixtures-deprecated/widget-class-init-loop/test.js
packages/marko/test/components-browser/fixtures-deprecated/widget-class-init-loop/widget.js
packages/marko/test/components-browser/fixtures-deprecated/widget-lifecycle-events-stateful-conditional-bind-monkey-patched/index.js
packages/marko/test/components-browser/fixtures-deprecated/widget-lifecycle-events-stateful-conditional-bind-monkey-patched/test.js
packages/marko/test/components-browser/index.test.js

Re-fixes the issue fixed in https://github.com/marko-js/marko/pull/1490 that was regressed in https://github.com/marko-js/marko/pull/1521.
Fixes the test runner to handle widgets that don't call `defineWidget`.
Adds a test so this doesn't happen again.

fix: don't modify proto.init when creating a widget

---

packages/marko/src/core-tags/migrate/all-tags/w-bind.js
packages/marko/src/runtime/components/ComponentDef.js
packages/marko/src/runtime/renderable.js

Fixes three small issues:
1. The `w-bind` migrator would normalize `w-bind="./index"` to `w-bind="./"` which was not safe if you had a `package.json` in the same folder with a `main` field.
2. `widgetConfig` was being incorrectly merged into the component instance (as well as being available on `this.widgetConfig`. This is a regression from https://github.com/marko-js/marko/pull/1539
3. Previously in Marko 3 `template.render` with a callback would provide `out` as the third  argument. This has been added back for compatibility.

fix: improve a few small things legacy compatibility

---

packages/marko/src/runtime/renderable.js

Updates the `safeRender` helper to use our `nextTick` helper instead of `setTimeout` since that is more inline with what we want and is more predictable.

fix: switch safe renderer to use nextTick for errors

---

packages/marko/src/runtime/components/legacy/dependencies/index.js

Currently if you are using `lasso@2` it can cause Marko to inline a full file system path as a comment. This is bad if you are relying on the file content as a hash.... which is happening.

fix: prevent lasso 2 from inlining full system paths

---

packages/marko/src/runtime/components/legacy/dependencies/index.js

Fixes an issue introduced in #1555: relative paths that are in the current directory or a child directory did not have the `./` prefix.
Lasso resolves relative paths that don't start with a `./` or `../` as node modules, which is not what we want and results in component files being undiscoverable.

fix(legacy dependencies): relative path should begin with ./

---

packages/marko/src/compiler/ast/HtmlElement/html/StartTag.js
packages/marko/src/runtime/html/AsyncStream.js
packages/marko/src/runtime/html/helpers/data-marko.js
packages/marko/test/compiler/fixtures-html/no-update-multiple/expected.js
packages/marko/test/compiler/fixtures-html/no-update/expected.js
packages/marko/test/components-compilation/fixtures-html-deprecated/bind-component/expected.js
packages/marko/test/components-compilation/fixtures-html-deprecated/bind-widget/expected.js
packages/marko/test/components-compilation/fixtures-html-deprecated/component-include-attr/expected.js
packages/marko/test/components-compilation/fixtures-html-deprecated/component-template-entry/expected.js
packages/marko/test/components-compilation/fixtures-html-deprecated/widget-types/expected.js
packages/marko/test/render/fixtures/await-no-update-content/component-browser.js
packages/marko/test/render/fixtures/await-no-update-content/expected.html
packages/marko/test/render/fixtures/await-no-update-content/template.marko
packages/marko/test/render/fixtures/await-no-update-content/test.js

There was a regression from https://github.com/marko-js/marko/pull/1480 which would cause `no-update` body to loose track of if it was preserved when it was wrapped in an async writer (`<await>`).

fix: issue with data-marko attributes under 'no-update' with <await>

---

packages/marko/src/core-tags/core/await/reorderer-renderer.js
packages/marko/test/components-pages/fixtures/split-async-keys/components/app-hello/index.marko
packages/marko/test/components-pages/fixtures/split-async-keys/tests.js

Fixes a regression from #1502 which causes components under a `client-reorder` not to initialize.

fix: components under client-reorder not initializing

---

packages/marko/src/core-tags/migrate/all-tags/w-config.js
packages/marko/test/migrate/fixtures/w-config/snapshot-expected.marko
packages/marko/test/migrate/fixtures/w-config/template.marko

In Marko 3 having an empty `w-config` (eg `<div w-bind w-config>`) would act as a noop.
In the Marko 4 compatibility layer this now outputs invalid javascript.
This PR updates the `w-config` migration to not output any code if the `w-config` has no value.

fix: support empty w-config

---

packages/marko/src/core-tags/migrate/macro-tag.js
packages/marko/test/migrate/fixtures/legacy-macro-syntax/snapshot-expected.marko
packages/marko/test/migrate/fixtures/legacy-macro-syntax/template.marko

Currently, the legacy macro syntax migrator has a bug where if the argument syntax is used and an argument is skipped, that argument will be set to `true` instead of `undefined`.
eg:
```marko
<macro some-tag(a, b)>
<div/>
</macro>
<some-tag("hi")/>
```
In the above `b` would be `true`.

fix: issue with optional arguments for legacy macro migration

---

.lintstagedrc
lint-staged.config.js
package-lock.json
package.json

`lint-staged` is breaking down with special characters in the paths, eg `index[html].js`. This PR escapes those via the lintstaged config.

chore: fix lint staged escapes

---

packages/marko/src/compiler/ast/HtmlElement/html/generateCode.js
packages/marko/src/compiler/ast/HtmlElement/vdom/generateCode.js
packages/marko/src/core-tags/components/preserve-tag-browser.js
packages/marko/src/core-tags/components/preserve-tag.js
packages/marko/src/runtime/helpers/dynamic-tag.js
packages/marko/src/runtime/html/AsyncStream.js
packages/marko/src/runtime/vdom/AsyncVDOMBuilder.js
packages/marko/test/render/fixtures-deprecated/body-only-if/expected.html

Currently, there is a regression that causes `body-only-if` and `<${null}>` content to not match correctly if set to `false` and hydrated in the client.
In this PR it is fixed so that the fragments created on the server are the same as on the browser.

fix: issue with hydrating body-only-if content

---

packages/compiler/src/taglib/index.js

Exposes the `taglib.register` API from the new `@marko/compiler` api. This allows for registering global, cross translator, taglibs.

feat(compiler): expose register taglib api

---

packages/compiler/src/taglib/index.js
packages/translator-default/src/taglib/index.js

Currently Marko 5 always loads the taglib utils from `marko/src`. This can cause issues if other tools are using the taglib utils from `dist` to register tags.
This PR updates Marko 5 to always use the correct taglib utils import.

fix: load correct taglib utils based on env

---

packages/marko/src/compiler/CompileContext.js
packages/marko/src/compiler/ast/HtmlElement/vdom/HtmlElementVDOM.js
packages/marko/src/runtime/vdom/VElement.js
packages/marko/src/runtime/vdom/morphdom/index.js
packages/marko/test/components-browser/fixtures/diffpatch-dynamic-attributes/index.marko
packages/marko/test/components-browser/fixtures/diffpatch-dynamic-attributes/test.js
packages/marko/test/vdom-compiler/fixtures-deprecated/attrs-dynamic-object-literal/expected.js
packages/marko/test/vdom-compiler/fixtures-deprecated/attrs-dynamic/expected.js
packages/marko/test/vdom-compiler/fixtures/attrs-dynamic-object-literal/expected.js
packages/marko/test/vdom-compiler/fixtures/attrs-dynamic/expected.js

```marko
$ {
const attrs = {};
if(someCondition) {
attrs.href = "https://someCoolUrl"
} else {
attrs["aria-disabled"] = true
}
}
<a ...attrs>some text</a>
```
When `someCondition` changes, the old attribute doesn't currently get removed.  This PR fixes this issue.

fix: diffing dynamic attributes with mismatched keys

---

packages/babel-utils/src/tags.js
packages/compiler/src/babel-plugin/file.js
packages/compiler/src/babel-plugin/index.js
packages/compiler/src/babel-plugin/parser.js
packages/compiler/src/babel-plugin/plugins/migrate.js
packages/compiler/src/babel-plugin/plugins/transform.js
packages/marko/src/taglib/taglib-loader/Taglib.js
packages/marko/src/taglib/taglib-lookup/TaglibLookup.js
packages/translator-default/src/optimize.js
packages/translator-default/src/tag/index.js
packages/translator-default/src/util/with-previous-location.js

Exposes a new `metadata` property that lists some files which tools such as the `WebpackDevServer` should include as a dependency for the compiled Marko file. This is not an exhaustive list, but hopefully good enough for practical purposes.

Marko 5: Expose watch file meta data

---

packages/marko/src/runtime/vdom/VElement.js
packages/marko/src/runtime/vdom/morphdom/index.js
packages/marko/test/components-browser/fixtures/form-controls-default-value/index.marko
packages/marko/test/components-browser/fixtures/form-controls-default-value/test.js

Currently, when actualizing a viritual `textarea` element (IE not server-rendered) we do not properly assign the `defaultValue` property. 
This PR sets both `defaultValue` and `value` in this case.

fix: set default value for textarea when created

---

packages/marko/package-lock.json
packages/marko/package.json
packages/marko/src/compiler/util/isCompoundExpression.js
packages/marko/src/compiler/util/parseRawJavaScriptAst.js
packages/marko/src/core-tags/components/TransformHelper/handleRootNodes.js
packages/marko/test/parseFor/fixtures/forEach-invalid-option2/expected.json
packages/marko/test/render/fixtures-deprecated/error-invalid-for-attr-separator/test.js
packages/marko/test/render/fixtures-deprecated/error-invalid-for-attr/test.js
packages/marko/test/render/fixtures-deprecated/error-invalid-for-props/test.js
packages/marko/test/render/fixtures-deprecated/error-invalid-for-range-step/test.js
packages/marko/test/render/fixtures-deprecated/error-invalid-for-range-to-expr/test.js
packages/marko/test/render/fixtures-deprecated/error-invalid-for-range/test.js
packages/marko/test/render/fixtures-deprecated/error-invalid-if-attr/test.js
packages/marko/test/render/fixtures-deprecated/error-invalid-if-else-attr/test.js
packages/marko/test/render/fixtures-deprecated/error-invalid-if-else-if-attr/test.js
packages/marko/test/render/fixtures-deprecated/error-invalid-if-else-if-else-attr/test.js
packages/marko/test/render/fixtures-deprecated/error-invalid-unless-tag/test.js
packages/marko/test/render/fixtures/error-bad-expression/test.js
packages/marko/test/render/fixtures/error-invalid-else-if-tag/test.js
packages/marko/test/render/fixtures/error-invalid-if-attr/test.js
packages/marko/test/render/fixtures/error-invalid-if-else-attr/test.js
packages/marko/test/render/fixtures/error-invalid-if-else-if-attr/test.js
packages/marko/test/render/fixtures/error-invalid-if-else-if-else-attr/test.js
packages/marko/test/render/fixtures/error-invalid-if-else-if-else-tag/test.js
packages/marko/test/render/fixtures/error-invalid-if-else-if-tag/test.js
packages/marko/test/render/fixtures/error-invalid-if-tag/test.js

esprima seems to no longer be maintained. This PR switches Marko 4 to use the fork that is maintained by the eslint team called espree.
For the most part, these are compatible, and this means Marko 4 can now parse more modern JavaScript.
Fixes https://github.com/marko-js/marko/issues/1450
https://github.com/marko-js/marko/issues/1450 is also already fixed in Marko 5 with babel now being used as the parser.

feat: switch to espree from esprima

---

packages/marko/src/compiler/util/vdom/index.js

Deleted duplicate string for export 'registerOptimizer'
The problem occurs when using the 'rollup'. The duplicate caused a compilation error:
```
[!] Error: Duplicate export 'registerOptimizer'
node_modules/marko/dist/compiler/util/vdom/index.js (36:32)
34: export { registerOptimizer_1 as registerOptimizer };
35: export { isStaticValue_1 as isStaticValue };
36: export { registerOptimizer_2 as registerOptimizer };
```
After the fix everything works

fix: duplicate export 'registerOptimizer'

---

packages/marko/helpers/empty-browser.marko
packages/marko/helpers/empty.js
packages/marko/helpers/notEmpty-browser.marko
packages/marko/helpers/notEmpty.js
packages/marko/package.json
packages/marko/src/legacy-helpers/empty.js
packages/marko/src/legacy-helpers/notEmpty.js
packages/marko/src/loader/index-browser.js

Prevents loading the complain module when legacy helpers (`marko/helpers`) are loaded.
This PR also contains a minor optimization for the `.load` api when used in the browser.

Legacy helpers perf

---

packages/marko/src/runtime/components/ComponentDef.js
packages/marko/src/runtime/components/index.js
packages/marko/src/runtime/components/legacy/defineRenderer-legacy.js
packages/marko/src/runtime/setImmediate.js

* Avoids serializing empty objects for w-config (legacy widgets)
* Prevent bundlers from including a `setImmediate` shim
* Avoid changing component instance shape

Minor perf fixes

---

packages/marko/src/compiler/ast/HtmlElement/vdom/HtmlElementVDOM.js
packages/marko/src/core-tags/components/TransformHelper/handleComponentPreserve.js
packages/marko/src/core-tags/components/TransformHelper/handleComponentPreserveAttrs.js
packages/marko/src/core-tags/components/marko.json
packages/marko/src/core-tags/components/preserve-tag-browser.js
packages/marko/src/core-tags/components/preserve-tag.js
packages/marko/src/runtime/components/init-components-browser.js
packages/marko/src/runtime/vdom/VElement.js
packages/marko/src/runtime/vdom/VNode.js
packages/marko/src/runtime/vdom/morphdom/index.js
packages/marko/src/runtime/vdom/preserve-attrs.js
packages/marko/test/compiler/fixtures-html/no-update-multiple/expected.js
packages/marko/test/compiler/fixtures-html/no-update/expected.js
packages/marko/test/components-compilation/fixtures-html-deprecated/auto-key-els/expected.js
packages/marko/test/components-compilation/fixtures-html/auto-key-els/expected.js
packages/marko/test/render/fixtures/await-no-update-content/expected.html

https://github.com/marko-js/marko/pull/1480 made it so that `no-update` would preserve server rendered content. To achieve this it used preserved fragment markers.
This caused a regression specifically when people are relying on those markers not being there in order to just set `innerHTML` or similar for child nodes like `<div no-update-body>`.
This PR treats native elements with `no-update` specially and doesn't introduce any new nodes to do so.

fix: no longer use fragments for preserved native els

---

packages/marko/README.md

Fixed wrong "docs" url in the README.md 
This change is required because if you click on "docs" url, you will end up with 404 page.

Fixed "docs" url in the README.md

---

packages/babel-utils/src/tags.js
packages/translator-default/src/tag/custom-tag.js
packages/translator-default/src/tag/dynamic-tag.js
packages/translator-default/src/tag/index.js
packages/translator-default/src/tag/native-tag.js
packages/translator-default/src/tag/native-tag[html]/index.js
packages/translator-default/src/tag/native-tag[vdom]/index.js
packages/translator-default/test/fixtures/dynamic-tag-name/snapshots/cjs-expected.js
packages/translator-default/test/fixtures/dynamic-tag-name/snapshots/generated-expected.marko
packages/translator-default/test/fixtures/dynamic-tag-name/snapshots/html-expected.js
packages/translator-default/test/fixtures/dynamic-tag-name/snapshots/htmlProduction-expected.js
packages/translator-default/test/fixtures/dynamic-tag-name/snapshots/vdom-expected.js
packages/translator-default/test/fixtures/dynamic-tag-name/snapshots/vdomProduction-expected.js
packages/translator-default/test/fixtures/dynamic-tag-name/template.marko

Fixes an issue where type optimize dynamic attributes were not running the running the correct attribute translators.
IE
```marko
<${a && "div"} class=["a"]/>
```
would not properly normalize the class. (Optimized to know that the dynamic tag was always a string).

Marko5 fix: dynamic tag html attr normalize

---

.gitignore
package-lock.json
package.json
packages/babel-types/index.d.ts
packages/babel-types/package.json
scripts/types-babel-traverse.js
scripts/types-babel-types.js

Adds TypeScript definitions for Babel Types that include Marko's custom types.
Also creates a modified types definitions for Babel Traverse.
These definitions are generated at build time via scripts.

feat: add typescript types for babel-types

---

packages/babel-types/index.d.ts
packages/babel-utils/index.d.ts
packages/babel-utils/package.json

Adds basic typescript types to `@marko/babel-utils`.

feat(babel-utils): add basic types

---

packages/babel-types/src/generator/patch.js
packages/babel-types/src/types/definitions.js
packages/compiler/package.json
packages/compiler/src/babel-plugin/util/parse-attributes.js
packages/translator-default/test/fixtures/tag-with-default-attr/snapshots/cjs-error-expected.txt
packages/translator-default/test/fixtures/tag-with-default-attr/snapshots/cjs-expected.js
packages/translator-default/test/fixtures/tag-with-default-attr/snapshots/generated-expected.marko
packages/translator-default/test/fixtures/tag-with-default-attr/snapshots/html-error-expected.txt
packages/translator-default/test/fixtures/tag-with-default-attr/snapshots/html-expected.js
packages/translator-default/test/fixtures/tag-with-default-attr/snapshots/htmlProduction-error-expected.txt
packages/translator-default/test/fixtures/tag-with-default-attr/snapshots/htmlProduction-expected.js
packages/translator-default/test/fixtures/tag-with-default-attr/snapshots/vdom-error-expected.txt
packages/translator-default/test/fixtures/tag-with-default-attr/snapshots/vdom-expected.js
packages/translator-default/test/fixtures/tag-with-default-attr/snapshots/vdomProduction-error-expected.txt
packages/translator-default/test/fixtures/tag-with-default-attr/snapshots/vdomProduction-expected.js
packages/translator-default/test/fixtures/tag-with-default-attr/template.marko

Adds parse and codegen support for the new default attribute syntax, eg:
```marko
<my-tag="x"/>
```
equivalent to:
```marko
<my-tag default="x"/>
```

feat: add default attribute support

---

package-lock.json
package.json
packages/compiler/package.json
packages/compiler/src/taglib/index.js

Lerna was not properly updating out package lock. This PR removes the `--no-ci` option which was preventing this.
Also upgrades htmljs-parser.

chore: update htmljs parser, fix lerna issue

---

babel.config.js
package-lock.json
package.json
packages/marko/test/render/fixtures/nested-tags-repeated-with-default-render-body/components/test-nested-tags-tabs/index.marko
packages/marko/test/render/fixtures/nested-tags-repeated-with-default-render-body/components/test-nested-tags-tabs/marko-tag.json
packages/marko/test/render/fixtures/nested-tags-repeated-with-default-render-body/expected.html
packages/marko/test/render/fixtures/nested-tags-repeated-with-default-render-body/template.marko
packages/marko/test/render/fixtures/nested-tags-repeated-with-default-render-body/test.js
packages/marko/test/render/fixtures/nested-tags-repeated-with-default-render-body/vdom-expected.html
packages/translator-default/src/tag/attribute-tag.js
packages/translator-default/src/tag/util.js

Fixes issue where dynamic attribute tags are used with default body content.

Marko 5: Fix repeated render body

---

packages/babel-utils/index.d.ts
packages/babel-utils/src/index.js
packages/babel-utils/src/tags.js
packages/compiler/src/babel-plugin/index.js
packages/translator-default/src/index.js

Exposes a utility to get the template id.
Exposes a utility to resolve `<tag>` style imports.

feat(babel-utils): expose import and id utils

---

packages/marko/docs/koa.md

Without configuring the `flush` option in `createGzip()`, the example code will buffer a lot of HTML and more or less defeat the point.

Preserve gzip streaming in Koa integration example

---

packages/marko/docs/core-tags.md

-Correcting a variable (typo)
-Added client-reorder so the placeholder tag actually gets used in the example
Makes the example work aswell as displaying the placeholder property in action

Changed <await> doc

---

packages/marko/src/runtime/components/ComponentDef.js

Fixes an exception that was being thrown when trying to deserialize a components input where the input only contained the warp 10 renderBody and was assumed to be empty.

fix: issue with only renderBody being serialized

---

packages/compiler/package.json
packages/compiler/src/babel-plugin/index.js
packages/compiler/src/config.js

Updates the Marko 5 compiler to no longer bring in `@marko/translator-default` as a dep. The default translator is now inferred from your installed node_modules instead.
This PR also makes it possible to pass in a string matching `@marko/translator-`, `marko-translator-` or a module name to use as the translator instead of only allowing passing the translator itself.
Eg the following are now all possible
```
compile(src, { translator: require("@marko/translator-default") });
compile(src, { translator: "@marko/translator-default" });
compile(src, { translator: "marko-translator-default" });
compile(src, { translator: "default" }); // either `@marko/translator-default`, `marko-translator-default` or a module called `default`
```

feat: allow string translator config

---

packages/babel-utils/src/imports.js

Fixes a regression in Marko 5 that was causing import paths to templates in node_modules to be incorrect.

fix(babel-utils): resolve node_module templates to relative paths

---

packages/marko/test/components-browser/fixtures/tag-params-nested-tags/index.marko
packages/marko/test/components-browser/fixtures/tag-params/index.marko
packages/marko/test/render/fixtures/dynamic-tag-arguments/expected.html
packages/translator-default/src/index.js
packages/translator-default/src/tag/native-tag[html]/index.js
packages/translator-default/src/tag/util.js
packages/translator-default/src/taglib/core/parse-class.js
packages/translator-default/src/util/get-component-files.js
packages/translator-default/test/fixtures/at-tags-dynamic-with-params/snapshots/cjs-expected.js
packages/translator-default/test/fixtures/at-tags-dynamic-with-params/snapshots/html-expected.js
packages/translator-default/test/fixtures/at-tags-dynamic-with-params/snapshots/htmlProduction-expected.js
packages/translator-default/test/fixtures/at-tags-dynamic-with-params/snapshots/vdom-expected.js
packages/translator-default/test/fixtures/at-tags-dynamic-with-params/snapshots/vdomProduction-expected.js
packages/translator-default/test/fixtures/custom-tag-parameters/snapshots/cjs-expected.js
packages/translator-default/test/fixtures/custom-tag-parameters/snapshots/html-expected.js
packages/translator-default/test/fixtures/custom-tag-parameters/snapshots/htmlProduction-expected.js
packages/translator-default/test/fixtures/custom-tag-parameters/snapshots/vdom-expected.js
packages/translator-default/test/fixtures/custom-tag-parameters/snapshots/vdomProduction-expected.js
packages/translator-default/test/fixtures/data-migration/snapshots/cjs-expected.js
packages/translator-default/test/fixtures/data-migration/snapshots/html-expected.js
packages/translator-default/test/fixtures/data-migration/snapshots/htmlProduction-expected.js
packages/translator-default/test/fixtures/data-migration/snapshots/vdom-expected.js
packages/translator-default/test/fixtures/data-migration/snapshots/vdomProduction-expected.js

Currently whenever tag params are used on an implicit component it forces it to become a stateful component with the exception being the built-in tags (eg `for|param|`).
This PR updates that logic to use child template analysis and our new analysis stage in order to first check to see if the tag param provider component is stateful. This means that stateless components that provide tag parameters no longer cause their parent component to become treated stateful.

feat: improve analysis for stateful tag parameters

---

packages/babel-utils/src/tags.js
packages/translator-default/src/taglib/core/translate-include-content.js

After working with @DylanPiercey to debug an issue related to Webpack/Marko, he found that `fs.readFileSync` is not the native node version, but rather Webpack's custom version. What was happening was that it would read the file as a buffer rather than a string, erroring out when Webpack would do its bundling

Added fix for webpack's file system not converting buffer properly

---

packages/marko/docs/10-awesome-marko-features.md

Tiniest possible contribution: fixed a small typo in a documentation page.

Fix typo in documentation: replace special character by "--"

---

packages/babel-utils/src/tags.js
packages/translator-default/test/fixtures/at-tags-dynamic/snapshots/cjs-expected.js
packages/translator-default/test/fixtures/at-tags-dynamic/snapshots/generated-expected.marko
packages/translator-default/test/fixtures/at-tags-dynamic/snapshots/html-expected.js
packages/translator-default/test/fixtures/at-tags-dynamic/snapshots/htmlProduction-expected.js
packages/translator-default/test/fixtures/at-tags-dynamic/snapshots/vdom-expected.js
packages/translator-default/test/fixtures/at-tags-dynamic/snapshots/vdomProduction-expected.js
packages/translator-default/test/fixtures/at-tags-dynamic/template.marko
packages/translator-default/test/fixtures/sanity-check/snapshots/vdom-expected.js
packages/translator-default/test/fixtures/sanity-check/snapshots/vdomProduction-expected.js

Fixes a bug where you aren't able to use attribute tags inside of an `<else-if>` tag.
Adds else-if to TRANSPARENT_TAGS Set in @marko/babel-utils

Fix: Allow attribute tags inside of else-if tags

---

packages/marko/src/core-tags/core/await/client-reorder-runtime.min.js
packages/marko/src/core-tags/core/await/client-reorder.js

This PR simplifies the loading of the `client-reorder-runtime` code.
Instead of having the minified code in a separate file it is now just inlined.

fix(marko): simplify client-reorder runtime loading login to inline code

---

packages/marko/src/runtime/components/event-delegation.js

In some browsers the event target can be a text node, for example, `dragenter` in firefox can do this.
When that happens, currently our event delegation breaks down since it expects a regular element node.
This PR adds a check for text nodes during event delegation and uses the parent element to check for event handlers.

fix(marko): issue with delegating events from text nodes

---

packages/marko/src/runtime/components/init-components-browser.js
packages/marko/src/runtime/components/registry-browser.js

improvement: add support for split component lazy hydration

---

packages/marko/src/runtime/components/init-components-browser.js
packages/marko/src/runtime/components/registry-browser.js

Fixes an issue where if a component is hydrated async after the final flush from the server the metadata needed to initialize the component could be gone.
This PR also adds a more helpful warning when it is detected multiple copies of Marko are initializing without unique runtimeId's.

fix(marko): issue with async hydrate after final flush

---

packages/compiler/package.json
packages/compiler/src/babel-plugin/index.js
packages/compiler/src/config.js
packages/compiler/src/taglib/finder/index.js
packages/compiler/src/taglib/fs.js
packages/compiler/src/taglib/loader/json-file-reader.js
packages/compiler/src/taglib/loader/loadTagFromProps.js
packages/compiler/src/taglib/loader/loadTaglibFromProps.js
packages/compiler/src/taglib/loader/scanTagsDir.js
packages/marko/src/node-require/index.js

Changes all taglib apis to move away from `lasso-caching-fs` to instead use the `options.fileSystem`passed to the compiler.

fix(compiler): use provided FS for taglib building

---

packages/compiler/src/taglib/loader/json-file-reader.js
packages/compiler/src/taglib/loader/scanTagsDir.js

We call `.readFileSync` and pass `{ encoding:"utf-8" }` but a custom filesystem may not honor that (webpack, looking at you).  So this adds an additional cast to string.

fix: cast result of readFile to string

---

packages/compiler/src/taglib/index.js

Makes it easier to use `compiler.taglib.buildLookup` by making the `translator` argument use the default translator when not provided.

feat(compiler): use default translator for buildLookup api

---

packages/compiler/src/config.js
packages/marko/docs/compiler.md
packages/translator-default/src/index.js
packages/translator-default/src/util/add-dependencies.js
packages/translator-default/test/fixtures/import-hydrate-include/bar.js
packages/translator-default/test/fixtures/import-hydrate-include/snapshots/cjs-expected.js
packages/translator-default/test/fixtures/import-hydrate-include/snapshots/generated-expected.marko
packages/translator-default/test/fixtures/import-hydrate-include/snapshots/html-expected.js
packages/translator-default/test/fixtures/import-hydrate-include/snapshots/htmlProduction-expected.js
packages/translator-default/test/fixtures/import-hydrate-include/snapshots/hydrate-expected.js
packages/translator-default/test/fixtures/import-hydrate-include/snapshots/vdom-expected.js
packages/translator-default/test/fixtures/import-hydrate-include/snapshots/vdomProduction-expected.js
packages/translator-default/test/fixtures/import-hydrate-include/template.marko

Currently when using `import` for a server side only template, bundlers don't have a great way (even in hydrate mode) to be able to know include known asset types in the browser.
For example, if you `import "./foo.css"` from a server only module, it will currently not be included in the browser in our supported bundler plugins. One work around is to use `@import` in the component `style.x` or inline `style` blocks, however being able to import something like `style.module.css` would not currently match.
This PR adds the `hydrateIncludeImports` option with a new default regexp that matches imports in the template and includes many known asset types in the `hydrate` mode output by default.

feat: add new hydrateIncludeImports option

---

packages/compiler/index.d.ts
packages/compiler/src/index.js
packages/translator-default/src/index.js

This exposes an api from the compiler (`getRuntimeEntryFiles(output, translator)`) which returns a list of runtime entry files that can be loaded from that translator. This is useful for bundlers like `Vite` which perform optimizations on these assets during dev server startup.

feat: expose api to get runtime entry files for translator

---

packages/marko/docs/custom-tags.md

At the moment, `<match-media>` custom tag could be installed as follows:
`npm install --save @marko-tags/match-media`
Update installation directions for `<match-media>` custom tag package

docs: update match-media install path on npm

---

packages/marko/src/runtime/helpers/style-value.js
packages/marko/test/render/fixtures/style-attr-object/template.marko

```marko
<div style={ display: "block", color: false, marginRight: 16 }>
```
Old output
```html
<div style="display:block;color:false;margin-right:16px;">
```
New output
```html
<div style="display:block;margin-right:16px;">
```

fix: false values are removed from style string. closes #1692

---

packages/marko/src/runtime/html/AsyncStream.js
packages/marko/test/render/fixtures/dynamic-tag-name/expected.html
packages/marko/test/render/fixtures/dynamic-tag-name/template.marko
packages/marko/test/render/fixtures/dynamic-tag-name/vdom-expected.html

This PR fixes a regression from https://github.com/marko-js/marko/commit/47a98341a2bdb4ae136495c5e3976dfe7c24a77c which impacts Marko >= `v5.0.0-next.39` (`v4` not impacted). 
Specifically when a non statically analyzable dynamic tag receives a string, and no renderBody content, it was not outputting the open tag correctly.
```marko
<${dynamic}/>
<${input.foo ? "a" : "div"}/>
<${dynamic}>
Nested content
</>
```
If the dynamic element was a void tag then it was also no effected.

fix(marko): issue with dynamic tag name string and no renderbody

---

packages/compiler/src/babel-plugin/index.js
packages/compiler/src/babel-plugin/plugins/migrate.js
packages/compiler/src/babel-plugin/plugins/transform.js
packages/compiler/src/babel-types/traverse/patch.js
packages/compiler/src/taglib/loader/loadTaglibFromProps.js

This PR contains two commits that are prerequisites for the upcoming [tags api preview](https://github.com/marko-js/marko/issues/1704).
1. It adds support for a taglib level `translate` hook. It also now supports exporting arrays from taglib compiler hooks which will automatically merge the visitors.
2. Supports hoisting tag variable bindings.

Improve taglib hooks, support tag var hoisting.

---

packages/compiler/src/babel-types/traverse/patch.js
packages/translator-default/src/index.js

Currently the tag var scope hoisting logic doesn't account for the current scope of the reference and just checks parent scopes. This logic is fixed in this PR.
This PR also contains a fix where (by moving content into the default render function) the scope information was off during the rest of the translate phase.

fix: issue with tag var scope hoisting

---

packages/compiler/src/babel-plugin/util/parse-attributes.js
packages/compiler/src/babel-types/generator/patch.js
packages/compiler/src/babel-types/types/definitions.js
packages/translator-default/src/tag/attribute/index.js

Adds support for a `bound` property on the attribute ast node and code generator.
This maps to a yet to be released version of `htmljs-parser` that handles the a new attribute binding shorthand syntax and will be used by the ["Tags API preview"](https://github.com/marko-js/marko/issues/1704).

feat: add support for new binding shorthand syntax

---

packages/compiler/src/babel-plugin/file.js
packages/compiler/src/taglib/lookup/index.js

When taglibs are merged together the previous merge logic would simply iterate over all properties on the taglib and copy them into a new object.
This PR updates the logic to account for when the properties are getter/setters and instead copies over the property definition.

fix(compiler): issue with getters on taglibs not properly merging

---

packages/translator-default/src/index.js

Fixes an issue with the default translator where if a compile hook added a `MarkoClass` node it would not properly track that the child was a stateful component.

fix(translator-default): issue when MarkoClass added via compiler hook

---

packages/compiler/package.json
packages/compiler/register.d.ts
packages/compiler/register.js
packages/compiler/src/register.js
packages/marko/docs/10-awesome-marko-features.md
packages/marko/docs/express.md
packages/marko/docs/http.md
packages/marko/docs/koa.md
packages/marko/src/node-require/index.js

Currently the `marko/node-require` api is exposed from the `marko` package which is intended for runtime code only that will eventually be replaced with the new `fluurt` runtime.
The `node-require` api is still useful however and is not coupled to the runtime, just the compiler. This API has now been moved into the compiler and exposed via `@marko/compiler/register` and a deprecation is logged when using the old path.

feat: expose @marko/compiler/register api

---

packages/marko/src/node-require/index.js

Back ports a change from Marko 5 which removes an unnecessary file rename.
Ultimately this was discovered to in some cases be more likely to cause issues with windows.

fix: remove file rename hack when writing files to disk

---

scripts/babel-plugin-marko-debug.js

Fixes #1742
The tool that strips out `MARKO_DEBUG` could leave behind invalid code:
**Example:**
`const complain = "MARKO_DEBUG" && require("complain");` => `const complain;`
**Fix:**
This PR removes the entire `VariableDeclarator` if the value is being removed.

fix: remove empty const/let/var declarations caused by removal of MARKO_DEBUG expressions

---

packages/marko/src/runtime/vdom/morphdom/index.js

Currently during hydration if there are adjacent text nodes (for example caused by placeholders after static text) the first node is set to it's original value, then subsequent nodes are rebuilt.
This PR normalizes this text during hydration to avoid rebuilding nodes in the case of the mismatch.

fix: issue with hydrating adjacent text nodes

---

packages/marko/src/runtime/components/beginComponent/index.js

This exposes the `willRerenderInTheBrowser` flag in a way that doesn't get garbled by our production build process. Still for internal usage only but will help with some patterns around synchronizing hydration for conditionally async things.

Expose will rerender in browser (internal use)

---

packages/marko/docs/custom-tags.md
packages/marko/docs/syntax.md
packages/marko/test/components-browser/fixtures/dynamic-tag-shorthand/components/test/index.marko
packages/marko/test/components-browser/fixtures/dynamic-tag-shorthand/index.marko
packages/marko/test/components-browser/fixtures/dynamic-tag-shorthand/test.js
packages/translator-default/src/tag/custom-tag.js

Adds a shorthand for dynamic tags based on a single identifier. With this change if you have a tag that would not be discovered from the file system and an in scope identifier exists it will act as a dynamic tag.
eg:
```marko
import SomeTag from "./somewhere.marko"
$ const { renderBody } = input;
$ const MyTag = input.href ? "a" : "button";
<SomeTag/>
<MyTag/>
<renderBody/>
```
For backward compatibility in scope variables have been implemented to have the lowest priority in the tag discovery process. In Marko 6 this will be bumped to the highest priority. Currently this PR will log a deprecation warning if there is a conflict that will have a different behavior in Marko 6.

feat: add shorthand for dynamic tag names from identifier

---

packages/marko/docs/cloudflare-workers.md
packages/marko/docs/express.md
packages/marko/docs/fastify.md
packages/marko/docs/http.md
packages/marko/docs/koa.md
packages/marko/docs/rollup.md
packages/marko/docs/structure.json
packages/marko/docs/troubleshooting-streaming.md
packages/marko/docs/vite.md
packages/marko/docs/webpack.md

Cleans up and updates a bunch of the server and bundler docs.
Also adds vite + cloudflare docs.

docs: refresh multiple server / bundler docs

---

packages/babel-utils/index.d.ts
packages/babel-utils/src/index.js
packages/compiler/src/taglib/loader/loadTagFromProps.js
packages/marko/docs/compiler.md
packages/marko/docs/marko-json.md

This PR adds support for a new field in `marko.json` files to define a function to handle the `analyze` stage of the compiler.
It also exposes types from `@marko/babel-utils` that better match a partial tag definition to aid in type completion for tag definitions defined in javascript/typescript.

feat: support analyze field in marko.json

---

packages/marko/docs/syntax.md

The location was wrapped in double quotes causing the link to not work.
P.S. the JS Foundation CLA link in the [CONTRIBUTING.md file](https://github.com/marko-js/marko/blob/7e3f7d66ef94f1aa76a00eabefdd20a7bf48c0a3/.github/CONTRIBUTING.md#pull-requests-are-always-welcome) is showing the following error:
```
Error
There is no CLA to sign for marko-js/marko
({"message":"Must specify access token via Authorization header. https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param","documentation_url":"https://docs.github.com/v3/#oauth2-token-sent-in-a-header"})
```

Fix broken link on line 586

---

packages/marko/docs/syntax.md

For some reason, on the online [syntax doc](https://markojs.com/docs/syntax) the [dynamic tag jump-link](https://markojs.com/docs/syntax#dynamic-tag) second-to-last paragraph is breaking, trying to load a different page, and loading a 404. For some unknown reason, quotation marks are placed around the jumplink in the markdown. Propose making the relative link to the same page and adding the jump #.
This change could make the jump tag work in the doc. 
Fixes issue# [1773](https://github.com/marko-js/marko/issues/1773)

update to dynamic tag jump link

---

packages/marko/docs/marko-vs-react.md

Apologies for the two tiny updates. The docs look really good. It's just an incorrect apostrophe.
Solves a typo. 
- [x ] I have read the **CONTRIBUTING** document and have signed (or will sign) the CLA.

Small syntax update

---

packages/marko/src/runtime/html/AsyncStream.js

In dev mode the Marko call the `prepareStackTrace` each time a component is rendered. `prepareStackTrace` is called when an errorstack trace is stringfied (by accessing the `.stack`  in the `Error`). That trigger a the sourcemap logic that can be very CPU intensive. 
We have a table with a lot of nested component that takes 40 seconds to render with full 100% CPU. After profiling the CPU with a flamegraph it is clear that during marko rendering `node` spends a considerable amount of time in `prepareStackTrace`.
This PR just save a new Error()  and do the `getNonMarkoStack(error.stack)`  only when an error occur.

fix: performance hit in development mode because continually parsing stacktrace

---

package-lock.json
packages/babel-utils/package.json
packages/babel-utils/src/imports.js

There are a few cases where Marko's compilation doesn't do the best job of normalizing import paths for resolved custom tags within node_modules. Specifically adjacent node_modules and/or if things were scoped.
Technically this is not an issue, the paths we output are valid. However some of our setups rely on excluding node_modules for SSR builds and that typically works by doing a rough check on the request id to see if it looks like a node_module. In some cases Marko will currently output a relative require path to another node_module which causes these externalizers to fail.
This PR brings in a new module built to do a better job of this normalization (https://github.com/marko-js/relative-import-path) and uses it instead of our previous algorithm.

feat: relative import normalization now works better with node_modules

---

packages/marko/src/runtime/components/event-delegation.js
packages/marko/test/components-browser/fixtures/event-handler-non-bubbling-multiple-listeners/index.marko
packages/marko/test/components-browser/fixtures/event-handler-non-bubbling-multiple-listeners/test.js

Fixes a regression from https://github.com/marko-js/marko/pull/1104 which caused non bubbling events to propagate up to any parent tag handler if the same event was registered there.
Resolves #1780

fix: prevent bubbling non bubbling events

---

.changeset/wet-jeans-double.md
.github/workflows/ci.yml
package-lock.json
package.json
packages/compiler/package.json

Pin a newer version of htmljs-parser that fixes some parser bugs. See: https://github.com/marko-js/htmljs-parser/pull/103
This PR also contains some small cleanup to the GitHub Actions CI config.
Resolves #1796

fix: upgrade htmljs-parser

---

.changeset/pink-poems-swim.md
package-lock.json
packages/compiler/src/babel-types/types/patch.js

Updates projects deps and inlines the `builder` helper that existed in babel before https://github.com/babel/babel/pull/14519

fix: update deps, inline babel helper removed from latest version

---

.changeset/spicy-actors-suffer.md
packages/marko/src/core-tags/core/__flush_here_and_after__.js
packages/marko/test/render/fixtures/flush-here-and-after-sync/test.js
packages/marko/test/render/index.test.js

Fixes a bug where sync render methods eg `renderToString` would not work with our default bundler integrations because of an internal tag `<__flush_here_and_after__>` not working with sync rendering. This PR updates the tag to work correctly when in sync rendering mode.

fix: issue with using __flush_here_and_after__ when in sync mode

---

.changeset/green-moons-smoke.md
packages/compiler/src/babel-plugin/parser.js

Turns out that babels parser really doesn't like it when you try to tell it that the start position while parsing is a negative integer and that we we're passing a negative integer when we were parsing the attr method shorthand (eg `<div onClick() {}>`).
This PR updates the parsing here to avoid using a prefix which could cause a negative start position by instead parsing the params and body separately. 
Indirectly this resolves https://github.com/marko-js/prettier/issues/7

fix: attr method shorthand source map position

---

packages/marko/docs/core-tags.md

Prompted by [this Discord conversation](https://discord.com/channels/725013179465203793/725013179926708226/990598962962640946):
> [8:46 AM] vwong: What is the intended use case for `<await show-after>`? I'm reading the docs, and am just wondering what use-case drove this feature?
> [8:49 AM] mpeg: If you do out of order client rendering with client-reorder I guess you could still want to have certain `<await>` blocks to wait for others to finish before showing
> [8:51 AM] vwong: Yeah, I get that it's only for client rendering, since server rendering is basically HTML order (or CSS if you flip it around). But example scenario?
> [8:52 AM] mpeg: Seems pretty niche for UX reasons, maybe say you want your `<await>` for product recommendations to show only after showing the product info
> …

Use-cases for `<await>` attributes

---

.changeset/happy-sheep-drum.md
packages/compiler/src/babel-plugin/parser.js
packages/translator-default/test/fixtures/attr-method-with-return/components/test.marko
packages/translator-default/test/fixtures/attr-method-with-return/snapshots/cjs-expected.js
packages/translator-default/test/fixtures/attr-method-with-return/snapshots/generated-expected.marko
packages/translator-default/test/fixtures/attr-method-with-return/snapshots/html-expected.js
packages/translator-default/test/fixtures/attr-method-with-return/snapshots/htmlProduction-expected.js
packages/translator-default/test/fixtures/attr-method-with-return/snapshots/vdom-expected.js
packages/translator-default/test/fixtures/attr-method-with-return/snapshots/vdomProduction-expected.js
packages/translator-default/test/fixtures/attr-method-with-return/template.marko

Fix issue where shorthand attribute methods could not have a "return" statement.

fix: issue with return statement inside attr method shorthand

---

.changeset/four-dogs-shout.md
packages/translator-default/src/taglib/core/conditional/util.js
packages/translator-default/test/fixtures/else-tag-with-whitespace-and-comments/snapshots/cjs-expected.js
packages/translator-default/test/fixtures/else-tag-with-whitespace-and-comments/snapshots/generated-expected.marko
packages/translator-default/test/fixtures/else-tag-with-whitespace-and-comments/snapshots/html-expected.js
packages/translator-default/test/fixtures/else-tag-with-whitespace-and-comments/snapshots/htmlProduction-expected.js
packages/translator-default/test/fixtures/else-tag-with-whitespace-and-comments/snapshots/vdom-expected.js
packages/translator-default/test/fixtures/else-tag-with-whitespace-and-comments/snapshots/vdomProduction-expected.js
packages/translator-default/test/fixtures/else-tag-with-whitespace-and-comments/template.marko

Fix issue where there was whitespace or a comment between else/else-if tags.

fix: comments or whitespace between else/else-if tags

---

.changeset/eighty-pandas-relate.md

The `markoc` cli was given the ability to strip typescript types, however it (accidentally) was not released with the previous changes. This adds release notes for the `marko` package so that it can now be published.

chore: add release notes for markoc

---

.changeset/twenty-games-perform.md
packages/compiler/src/babel-plugin/parser.js

There was a regression recently where the source map positions for shorthand attribute methods were off.

fix: source map for shorthand attr methods

---

.changeset/six-coats-visit.md
package-lock.json
packages/compiler/package.json

Upgrades the `htmljs-parser` to bring in https://github.com/marko-js/htmljs-parser/pull/127

chore: upgrade htmljs-parser

---

.changeset/red-spoons-flash.md
packages/babel-utils/src/imports.js

Our existing regex for swapping dev/prod runtimes was too eager and would match stuff like `./anything/marko/src/`. Now it will only match `marko` in `node_modules`.

fix: regexp for swapping dev/prod runtimes

---

.changeset/brave-rice-wink.md
packages/compiler/src/register.js

Currently to use `@lasso/marko-taglib` with the new `@marko/compiler/register` api the `meta` option must be enabled.
In order to improve support for that case we change this option to be enabled by default.

fix: improve support for @lasso/marko-taglib and @marko/compiler/register

---

packages/marko/package-lock.json
packages/marko/src/taglib/taglib-finder/index.js
packages/marko/src/taglib/taglib-loader/index.js
packages/marko/src/taglib/taglib-loader/loadTaglibFromDir.js
packages/marko/src/taglib/taglib-loader/loaders.js

This PR improves the performance of the taglib scanning for the `components` directories. This was not correctly being cached previously.

V4 improve tagdir folder scan cache

---

.changeset/soft-cups-punch.md
packages/marko/src/runtime/vdom/hot-reload.js

Currently the HMR implementation for the DOM mutates the template constructor keep track of all instances.
This mutation causes an issue when a template is passed around in the tags api preview where things are frozen.
This PR updates that logic to avoid mutating the instance.

fix: avoid template instance mutation in HMR mode

---

.changeset/purple-cameras-sit.md
packages/marko/src/runtime/html/StringWriter.js
packages/marko/test/components-server/fixtures/scriptConcat/template.marko
packages/marko/test/components-server/fixtures/scriptConcat/test.js

Fix an issue where merging scripts (via the out.script api) was not properly inserting delimiters when scripts are added in different async writers.
Specifically these scripts should be joined by `;`.

fix: ensure delimiter added when scripts merged across async writers

---

.changeset/gentle-foxes-knock.md
packages/babel-utils/index.d.ts
packages/compiler/src/taglib/loader/Tag.js
packages/compiler/src/taglib/loader/Taglib.js
packages/compiler/src/taglib/loader/loadTagFromProps.js
packages/compiler/src/taglib/loader/loadTaglibFromProps.js
packages/marko/index.d.ts
packages/marko/package.json
packages/marko/src/core-tags/core/await/index.marko
packages/translator-default/src/taglib/core/index.js

This PR adds apis needed by https://github.com/marko-js/language-server as well as some basic type definitions for a global `Marko` type. Docs coming in a future PR.

feat: add taglib extensions and type definitions for typescript support

---

packages/marko/docs/troubleshooting-streaming.md

Smaller record sizes can have massive TTFB improvements for clients, and `X-CTO: nosniff` is something sites should really be doing anyway for security reasons.
- ~~[n/a] I have added tests to cover my changes.~~

Mention TLS record sizes & MIME sniffing

---

packages/marko/docs/rollup.md

- Better sell why you might want to use this integration in the first place
- More examples
- Copyediting
I’m not entirely sure about removing the section on passing a `.marko` template to the `.browser()` plugin for 100% CSR apps, but I erred on the side of “don’t encourage behavior you don’t want to see”. I can put it back if you think I should.
- n/a ~~I have added tests to cover my changes.~~

Overhaul Rollup docs

---

.changeset/healthy-pans-remain.md
packages/compiler/src/taglib/loader/loadTagFromProps.js
packages/marko/index.d.ts
packages/marko/src/core-tags/core/await/index.marko
packages/marko/src/runtime/components/entry/index-browser.js
packages/marko/src/runtime/components/entry/index.js

* Tightens up the `.d.ts` for the Marko runtime
* Exposes a `Marko.Component` global which can be used to create a typed Marko component in a `component.{js,ts}`
* Fixes the `<await>` tag types.

chore: improve typescript support

---

.changeset/eleven-lobsters-pretend.md
packages/marko/src/runtime/components/entry/index-browser.js
packages/marko/src/runtime/components/entry/index.js
packages/marko/src/runtime/html/index.js
packages/marko/src/runtime/vdom/index.js

Depending on execution order it was possible that the `Marko.Component` global (used for typescript classes) was not defined before a `component.*` file was loaded.
This PR ensures that the global is set right away.

fix: issue with Marko.Component registered too late

---

.changeset/clever-kids-smile.md
packages/translator-default/src/class.js

An error was surfaced when a class component had empty members:
```
class {
state;
}
```
This is especially important for TypeScript:
```
class {
state: { count: number };
}
```

fix: allow empty class member

---

.changeset/sixty-bottles-call.md
packages/marko/src/runtime/components/registry/index-browser.js

Avoid using eval (in dev mode) for providing a better class name on component constructors.

fix: avoid using eval in dev mode

---

.changeset/small-donuts-sip.md
packages/compiler/src/babel-plugin/index.js
packages/translator-default/test/fixtures/exports/snapshots/cjs-expected.js
packages/translator-default/test/fixtures/exports/snapshots/generated-expected.marko
packages/translator-default/test/fixtures/exports/snapshots/html-expected.js
packages/translator-default/test/fixtures/exports/snapshots/htmlProduction-expected.js
packages/translator-default/test/fixtures/exports/snapshots/vdom-expected.js
packages/translator-default/test/fixtures/exports/snapshots/vdomProduction-expected.js
packages/translator-default/test/fixtures/exports/template.marko

Reduce script parsing restrictions added by Babel.
This was causing Babel to error when parsing partion scripts.
```marko
static const x = 1;
export { x };
```
Before this change in the above code Babel would error when parsing `export { x }` saying `x` was not previously defined. This is because Marko parses these statements in isolation.

fix: loosen babel parse errors

---

.changeset/hungry-games-flash.md
packages/marko/index.d.ts

Remove class lifecycle types to avoid the need to `override` them.
This provides slightly worse intenseness, but typing class methods based on super class is tricky in typescript. This may be revisited in the future.

fix: remove class lifecycle types

---

packages/marko/docs/marko-json.md
packages/marko/docs/state.md
packages/marko/docs/vite.md

There are small typos in:
- packages/marko/docs/marko-json.md
- packages/marko/docs/state.md
- packages/marko/docs/vite.md
Fixes:
- Should read `properties` rather than `properites`.
- Should read `individual` rather than `individial`.
- Should read `automatically` rather than `automaticall`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: Fix a few typos

---

.changeset/six-doors-jump.md
package-lock.json
packages/marko/docs/typescript.md
packages/marko/index.d.ts
packages/marko/package.json
packages/marko/tags-html.d.ts

Adds strict typescript types for the native HTML tags.

feat: add strict types for native html tags

---

.changeset/ninety-pumpkins-cross.md
packages/marko/docs/typescript.md
packages/marko/index.d.ts

Adds `NativeTagInput` and `NativeTagReturn` back as deprecated types. They were removed in favor of `Marko.Input` and `Marko.Return`, but bringing them back makes migrating to the new api a bit easier.
This PR also includes some docs improvements for typescript.

Add back NativeTag{Input,Return} as deprecated types.

---

packages/marko/docs/syntax.md

I've noticed that dynamic tag doesn't work also for macros, so it is good to mention in the docs
Example what is not working
```
<macro|{ renderBody, color }| name="greeting">
<div
class="greeting"
style={
backgroundColor: color
}>
Hello <${renderBody}/>}!
</div>
</macro>
<${true ? "greeting": "h1" } color="green">
World
</>
```

Add note that dynamic tag doesn't work for macro

---

.changeset/thin-goats-happen.md
packages/marko/tags-html.d.ts

`Marko.Input<"input">` had a required `type` attribute, which meant that `<input>` tags without `type` were receiving errors.

fix(input): make type optional

---

.changeset/stupid-jeans-lick.md
packages/translator-default/src/util/get-component-files.js

Marko@4 supported adaptive `.marko` files importing their supporting files (`component.js`, `style.css`, etc) when using [arc](https://github.com/eBay/arc).
In Marko 5 this handling was removed (seemingly accidentally).
This PR brings back support for that.

fix: arc support

---

.changeset/lazy-apricots-joke.md
packages/translator-default/src/util/add-dependencies.js

When telling the compiler to output the `hydrate` entry point with `modules` as `cjs` there is currently a compiler error since part of the hydrate compilation expects the imports to be actual esm import nodes.
This PR fixes the issue by avoiding adding `require` statements in the hydrate compilation and instead relying on the babel commonjs transform which happens later.

fix: hydrate commonjs output bug

---

.changeset/fluffy-paws-cross.md
.changeset/soft-points-work.md
lint-staged.config.js
packages/babel-utils/index.d.ts
packages/babel-utils/src/index.js
packages/babel-utils/src/loc.js
packages/babel-utils/src/parse.js
packages/compiler/src/babel-plugin/index.js
packages/compiler/src/babel-plugin/parser.js
packages/compiler/src/babel-types/generator/patch.js
packages/compiler/src/babel-types/types/definitions.js
packages/compiler/src/index.js
packages/compiler/src/util/merge-errors.js
packages/marko/src/node_modules/@internal/components-registry/index-browser.js
packages/translator-default/src/index.js
packages/translator-default/src/taglib/core/parse-class.js
packages/translator-default/src/taglib/core/parse-export.js
packages/translator-default/src/taglib/core/parse-import.js
packages/translator-default/src/taglib/core/parse-static.js
packages/translator-default/test/fixtures/module-code/snapshots/cjs-expected.js

Allow parse errors to be recovered from by migrations. This adds a new ast node type of MarkoParseError.
MarkoParseError nodes can be removed during the migration stage to handle legacy syntaxes. Any MarkoParseError
left in the AST at the end of the migration phase will throw an error similar to what it would have previously
thrown synchronously.
This also means that all parse errors can be surfaced as an aggregate error instead of bailing on the first
parse error. When the compiler is ran with `errorRecovery: true` these errors become diagnostics instead of
being thrown.

Fixable parse errors

---

.changeset/twenty-beers-repeat.md
packages/compiler/src/util/build-code-frame.js

Resolves https://github.com/marko-js/vite/issues/74

fix: deleting error properties regression

---

.changeset/gold-timers-sleep.md
packages/marko/src/core-tags/core/await/renderer.js
packages/marko/test/render/fixtures/await-error-rethrow-catch/template.marko
packages/marko/test/render/fixtures/await-error-rethrow-catch/test.js

Handles errors thrown within an `await` catch attribute using `out.error` to propagate the error to the response in the same way an await tag without a catch would.
Throwing an error in catch would be an unhandled error which could cause the server to crash.

fix: handle errors thrown in await catch attrs

---

.changeset/friendly-mangos-sleep.md
packages/marko/src/runtime/components/update-manager.js
packages/marko/test/components-browser/fixtures/component-update-batch-not-empty/components/counter.marko
packages/marko/test/components-browser/fixtures/component-update-batch-not-empty/index.marko
packages/marko/test/components-browser/fixtures/component-update-batch-not-empty/test.js

Refactors batching code to simplify the logic and prevent an issue when bundling with Rollup. Rollup's default treeshaking causes [part of the batching code](https://github.com/marko-js/marko/blob/1122f64b3a857ba4ebe8589469ffee4718bbd1a9/packages/marko/src/runtime/components/update-manager.js#L69) to be incorrectly omitted.
```js
function batchUpdate(func) {
const batch = {
___queue: null
};
batchStack.push(batch);
try {
func();
} finally {
try {
if (batch.___queue) {
updateComponents(batch.___queue);
}
} finally {
batchStack.length--;
}
}
}
````
becomes
```js
function batchUpdate(func) {
const batch = {
___queue: null
};
batchStack.push(batch);
try {
func();
} finally {
try {
if (batch.___queue) {
;
}
} finally {
batchStack.length--;
}
}
}
````
which prevents component changes batched …

fix: batching to prevent treeshaking issues

---

.changeset/pretty-shirts-wait.md
packages/marko/src/runtime/components/legacy/defineRenderer-legacy.js

Improves compat for legacy v3 widgets using the `markoWidgets.defineRenderer` api when passing in a template.
This api will now accept template modules with a default export.

fix: improve compat for legacy defineRenderer template references

---

.changeset/gold-rats-protect.md
packages/marko/tags-html.d.ts

fix(typescript): camel case event handlers were incorrect

---

.changeset/eleven-trees-grow.md
packages/babel-utils/src/parse.js
packages/compiler/src/babel-plugin/parser.js
packages/compiler/src/babel-types/generator/patch.js
packages/compiler/src/babel-types/types/definitions.js
packages/translator-default/test/fixtures/typescript-generic-tag/components/type-arg-and-param.marko
packages/translator-default/test/fixtures/typescript-generic-tag/components/type-arg.marko
packages/translator-default/test/fixtures/typescript-generic-tag/components/type-param.marko
packages/translator-default/test/fixtures/typescript-generic-tag/snapshots/cjs-expected.js
packages/translator-default/test/fixtures/typescript-generic-tag/snapshots/generated-expected.marko
packages/translator-default/test/fixtures/typescript-generic-tag/snapshots/html-expected.js
packages/translator-default/test/fixtures/typescript-generic-tag/snapshots/htmlProduction-expected.js
packages/translator-default/test/fixtures/typescript-generic-tag/snapshots/vdom-expected.js
packages/translator-default/test/fixtures/typescript-generic-tag/snapshots/vdomProduction-expected.js
packages/translator-default/test/fixtures/typescript-generic-tag/template.marko

Add type args and type params to the AST, primarily for use in tools like Prettier but also adds consistency with the rest of Babel parsing.

feat(ast): add type args and params

---

.changeset/spicy-turtles-travel.md
packages/marko/src/node_modules/@internal/components-define-widget-legacy/index-browser.js

Fixes an issue where if the `require('marko-component').defineComponent` is passed a template which is compiled in esm mode.

fix: legacy compatibility issue with esm templates and defineWidget

---

.changeset/witty-apricots-travel.md
packages/compiler/src/babel-plugin/parser.js
packages/compiler/src/babel-types/generator/patch.js
packages/compiler/src/babel-types/types/definitions.js

fix(babel): use correct types for params and args

---

.changeset/grumpy-kids-check.md
packages/compiler/src/taglib/finder/index.js
packages/compiler/src/taglib/loader/Taglib.js
packages/compiler/src/taglib/loader/index.js
packages/compiler/src/taglib/loader/loadTaglibFromFile.js
packages/compiler/src/taglib/loader/loadTaglibFromProps.js
packages/marko/docs/marko-json.md
packages/marko/test/taglib-finder/fixtures/exports/marko.json
packages/marko/test/taglib-finder/fixtures/exports/node_modules/included-dependency/marko.json
packages/marko/test/taglib-finder/fixtures/exports/node_modules/included-dependency/package.json
packages/marko/test/taglib-finder/fixtures/exports/package.json
packages/marko/test/taglib-finder/fixtures/exports/test.js

Add support for an `"exports"` member in `marko.json` which can point to the dist folder.

feat(compiler): add "exports" to marko.json

---

.changeset/flat-camels-hide.md
packages/compiler/src/babel-plugin/parser.js

Source maps were broken for TagTypeArgs and TagTypeParams, now they are not.

fix(sourcemaps): TagTypeArgs and TagTypeParams

---

.changeset/eighty-beers-speak.md
packages/compiler/src/babel-plugin/index.js

Fixes a bug where if you ask the Marko compiler to strip types from a template (not when outputting actual js) that additional template exports were removed.

fix: issue removing exports in stripTypes mode

---

.sizes.json
packages/translator-tags/src/__tests__/fixtures/tag-var-destructure/__snapshots__/csr-sanitized.expected.md
packages/translator-tags/src/__tests__/fixtures/tag-var-destructure/__snapshots__/csr.expected.md
packages/translator-tags/src/__tests__/fixtures/tag-var-destructure/__snapshots__/dom.expected/template.js
packages/translator-tags/src/__tests__/fixtures/tag-var-destructure/__snapshots__/html.expected/template.js
packages/translator-tags/src/__tests__/fixtures/tag-var-destructure/__snapshots__/resume-sanitized.expected.md
packages/translator-tags/src/__tests__/fixtures/tag-var-destructure/__snapshots__/resume.expected.md
packages/translator-tags/src/__tests__/fixtures/tag-var-destructure/__snapshots__/ssr-sanitized.expected.md
packages/translator-tags/src/__tests__/fixtures/tag-var-destructure/__snapshots__/ssr.expected.md
packages/translator-tags/src/__tests__/fixtures/tag-var-destructure/template.marko
packages/translator-tags/src/__tests__/fixtures/tag-var-destructure/test.ts
packages/translator-tags/src/core/let.ts
packages/translator-tags/src/util/replace-assignments.ts
packages/translator-tags/src/visitors/assignment-expression.ts
packages/translator-tags/src/visitors/update-expression.ts

- Allow destructure into tag variables, by replacing with a temporary local identifier before performing replacement.

feat: allow destructure assignment to tag variable

---

.sizes.json
packages/translator-interop/src/__tests__/fixtures/interop-basic-tags-to-class/__snapshots__/dom.expected/template.js
packages/translator-interop/src/__tests__/fixtures/interop-nested-tags-to-class/__snapshots__/dom.expected/template.js
packages/translator-interop/src/__tests__/fixtures/interop-tag-params-class-to-tags/__snapshots__/dom.expected/components/tags-layout.js
packages/translator-interop/src/__tests__/fixtures/interop-tag-params-tags-to-class/__snapshots__/dom.expected/template.js
packages/translator-tags/src/__tests__/fixtures/attr-class/__snapshots__/dom.expected/template.js
packages/translator-tags/src/__tests__/fixtures/basic-shared-node-ref/__snapshots__/dom.expected/template.js
packages/translator-tags/src/__tests__/fixtures/custom-tag-parameters-from-args/__snapshots__/dom.expected/components/custom-tag.js
packages/translator-tags/src/__tests__/fixtures/custom-tag-parameters-from-attributes/__snapshots__/dom.expected/components/custom-tag.js
packages/translator-tags/src/__tests__/fixtures/custom-tag-parameters-from-single-arg/__snapshots__/dom.expected/components/custom-tag.js
packages/translator-tags/src/__tests__/fixtures/dynamic-native-dynamic-tag/__snapshots__/dom.expected/template.js
packages/translator-tags/src/__tests__/fixtures/dynamic-tag-args-tag-var/__snapshots__/dom.expected/template.js
packages/translator-tags/src/__tests__/fixtures/dynamic-tag-args/__snapshots__/dom.expected/template.js
packages/translator-tags/src/__tests__/fixtures/dynamic-tag-custom-tags/__snapshots__/dom.expected/template.js
packages/translator-tags/src/__tests__/fixtures/dynamic-tag-single-arg/__snapshots__/dom.expected/template.js
packages/translator-tags/src/__tests__/fixtures/for-tag/__snapshots__/dom.expected/template.js
packages/translator-tags/src/__tests__/fixtures/lifecycle-tag-assignment/__snapshots__/dom.expected/template.js
packages/translator-tags/src/__tests__/fixtures/lifecycle-tag-conditional/__snapshots__/dom.expected/template.js
packages/translator-tags/src/__tests__/fixtures/lifecycle-tag-this/__snapshots__/dom.expected/template.js
packages/translator-tags/src/__tests__/fixtures/lifecycle-tag/__snapshots__/dom.expected/template.js
packages/translator-tags/src/__tests__/fixtures/user-effect-cleanup/__snapshots__/dom.expected/template.js
packages/translator-tags/src/core/condition/if.ts
packages/translator-tags/src/core/effect.ts
packages/translator-tags/src/core/for.ts
packages/translator-tags/src/core/lifecycle.ts
packages/translator-tags/src/util/reserve.ts
packages/translator-tags/src/visitors/placeholder.ts
packages/translator-tags/src/visitors/tag/dynamic-tag.ts

- Resolve collisions by using `generateUid` when passing a name into `reserveScope`
- Didn't update `"#child-scope"` from `custom-tag`, because it was breaking things
- Didn't add any tests

fix: use unique identifers for scope name reserves

---

packages/runtime-tags/src/common/types.ts
packages/runtime-tags/src/dom/control-flow.ts
packages/runtime-tags/src/dom/dom.ts
packages/runtime-tags/src/dom/fragment.ts
packages/runtime-tags/src/dom/queue.ts
packages/runtime-tags/src/dom/renderer.ts
packages/runtime-tags/src/dom/resume.ts
packages/runtime-tags/src/dom/signals.ts
packages/runtime-tags/src/dom/walker.ts
packages/runtime-tags/src/html/writer.ts
packages/translator-interop/src/feature-detection.ts
packages/translator-tags/src/core/condition/if.ts
packages/translator-tags/src/core/for.ts
packages/translator-tags/src/util/sections.ts
packages/translator-tags/src/util/signals.ts
packages/translator-tags/src/util/tag-name-type.ts
packages/translator-tags/src/util/walks.ts
packages/translator-tags/src/visitors/placeholder.ts
packages/translator-tags/src/visitors/tag/attribute-tag.ts
packages/translator-tags/src/visitors/tag/dynamic-tag.ts
packages/translator-tags/src/visitors/tag/index.ts
packages/translator-tags/src/visitors/tag/native-tag.ts

This all might be bad but...
- Normalize enum naming/casing/pluralization
- Deduplicate enums shared between tags translator and runtime by moving them into the runtime. This also required moving the shared enums into the `/runtime-tags/common/types.ts` file (otherwise the tests would end up trying to run module scope code that relies on `document`).

Dedupe enums

---

.changeset/modern-toes-exist.md
packages/marko/src/runtime/vdom/morphdom/index.js

In hydrate mode we use the [splitText](https://developer.mozilla.org/en-US/docs/Web/API/Text/splitText) api to break up text nodes which would have been merged after being rendered on the server.
The existing check had a bug though and did not verify that the previous content was long enough, which means if there was a hydration mismatch you could get errors like `Uncaught DOMException: Failed to execute 'splitText' on 'Text': The offset 1 is larger than the Text`.
This PR updates the logic to only call splitText if the current node actually starts with the expected content while hydrating.

fix: split text node hydrate issue

---

.changeset/mighty-pugs-burn.md
packages/marko/src/runtime/helpers/attr-tag.js

Fixes a regression where if you specify attribute tags and no renderBody content that it'd override existing renderBody in the input.

fix: renderBody regression with attribute tags

---

.changeset/selfish-bananas-exercise.md
packages/marko/src/runtime/vdom/VElement.js
packages/marko/src/runtime/vdom/VNode.js
packages/marko/src/runtime/vdom/morphdom/index.js

Fix regression where a textarea created with no value in the browser was setting `null` as the value.

fix: text area null regression

---

.sizes.json
scripts/sizes.ts

Removes gzip from the runtime size calculator (just brotli and minified now).
For some unknown reason the gzip size output was not deterministic. (this is a cry for help, fyi it does not appear to be related to the gzip headers)

chore: remove gzip from size check

---

packages/marko/docs/typescript.md

Minor fix for docs at: https://markojs.com/docs/typescript/#registering-a-new-native-tag-eg-for-custom-elements
Noticed it just repeated `namespace` instead of defining `NativeTags` as an `interface`; this fixes that. I assume it should align with structure of the `NativeTags` already defined in [`packages/marko/tags-html.d.t` ](https://github.com/marko-js/marko/blob/main/packages/marko/tags-html.d.ts#L13).

docs: Fixing NativeTags demo (interface, not namespace)

---

.changeset/serious-phones-burn.md
packages/marko/src/runtime/html/helpers/escape-script-placeholder.js
packages/marko/src/runtime/html/helpers/escape-style-placeholder.js
packages/marko/src/runtime/html/helpers/escape-xml.js
packages/marko/test/render/fixtures/escape-script/expected.html
packages/marko/test/render/fixtures/escape-style/expected.html
packages/marko/test/render/fixtures/script-tag-entities/expected.html
packages/translator-default/test/fixtures/placeholders/snapshots/cjs-expected.js
packages/translator-default/test/fixtures/placeholders/snapshots/html-expected.js
packages/translator-default/test/fixtures/placeholders/snapshots/htmlProduction-expected.js

After some recent benchmarking it turns out the current escape utilities for html body content are no longer faster than their regexp counter parts.
This PR updates the implementations to use regexps for escaping instead of manual iteration.
Note: In most cases doing a `.test` call before doing a `.replace` is faster, even though it's technically a bit slower for the cases where we actually escape something.

perf: improve html body content escaping

---

.changeset/rotten-months-cheat.md
packages/marko/src/runtime/html/helpers/escape-script-placeholder.js
packages/marko/src/runtime/html/helpers/escape-style-placeholder.js

Fix regression where interpolating null/undefined in a script/style tag was being replaced with an empty string instead of toString'd and added.
Eg `<script>${undefined}</>` was changed to render nothing, when previously it output `undefined` as a string inside the script.
Note this behavior should not be relied on and will change in the next major of Marko to normalize the interpolated value to an empty string for nullish values.

fix: avoid normalizing nullish values for script/style interpolation

---

.changeset/grumpy-shirts-cross.md

Fixes an issue where native tags would fail to hydrate in some cases if there was a diffing mismatch because they did not have their server key serialized.

fix: hydration native tag no-update issue

---

packages/marko/docs/fastify.md

Docs: Update fastify.md with Global outputs

---

.changeset/six-terms-smile.md
packages/marko/src/node_modules/@internal/components-registry/index-browser.js
packages/marko/src/node_modules/@internal/preserve-tag/index-browser.js
packages/marko/src/runtime/vdom/morphdom/index.js

Fixes #2198.
Note that there is quite a lot going on there and there are 3 main fixes in this PR on top of #2210 which was a partial fix.
In #2210 it ensured that native tags with `no-update` got their key serialized via the `data-marko-key` attribute to help with diffing.
However there are two places keys need to be stored and `data-marko-key` only set one of them. (The first place is essentially for `getEl` and the second is used in morphdom for diffing).
https://github.com/marko-js/marko/compare/no-update-directives-hydrate-fixes-04-16-24?expand=1#diff-172d13e48a87ce821ebe7c0b2d56ab3aad1fc85092dc196a360200a400236825R238 ensures the key is there when we go to diff.
Next issue is that after #2192 had an incorrect check to see if we should split the text node. With the check that was …

fix: issues related to hydrating no-update native tags

---

.changeset/shaggy-teachers-pay.md
packages/marko/src/runtime/helpers/empty-component.js
packages/marko/test/components-pages/fixtures/component-implicit-event-handlers/components/app-button-component/index.marko
packages/marko/test/components-pages/fixtures/component-implicit-event-handlers/components/app-button-split/index.marko
packages/marko/test/components-pages/fixtures/component-implicit-event-handlers/template.component-browser.js
packages/marko/test/components-pages/fixtures/component-implicit-event-handlers/template.marko
packages/marko/test/components-pages/fixtures/component-implicit-event-handlers/tests.js
packages/translator-default/src/index.js
packages/translator-default/src/tag/native-tag[html]/index.js
packages/translator-default/src/util/get-component-files.js
packages/translator-default/test/fixtures/error-duplicate-event-handlers/snapshots/hydrate-expected.js
packages/translator-default/test/fixtures/error-event-handler-missing-args/snapshots/hydrate-expected.js
packages/translator-default/test/fixtures/error-event-handler-value/snapshots/hydrate-expected.js
packages/translator-default/test/fixtures/event-handlers/snapshots/cjs-expected.js
packages/translator-default/test/fixtures/event-handlers/snapshots/html-expected.js
packages/translator-default/test/fixtures/event-handlers/snapshots/htmlProduction-expected.js
packages/translator-default/test/fixtures/event-handlers/snapshots/hydrate-expected.js
packages/translator-default/test/fixtures/event-handlers/snapshots/vdom-expected.js
packages/translator-default/test/fixtures/event-handlers/snapshots/vdomProduction-expected.js

This PR makes it so that if you have a template with event handlers and no `class`, `component.js` or `component-browser.js` that it will implicitly create one for you.
If the event handlers are all string literals it will inline a noop split component (`component-browser.js`) which means that having a top level template that just forwards events will work out of the box without manually creating an empty `component-browser.js` file. Eg the following will just work even as a top level template.
```marko
<button onClick("emit", "click")/>
```
If the event handler is not a string, then the template will implicitly become a client side component. Which means examples like this work out of the box without wrapping it in a component.
```marko
static function handleClick() {
// ...
}
<button …
```

feat: event handler implicit components

---

.changeset/warm-plums-look.md
packages/translator-default/src/util/optimize-vdom-create.js
packages/translator-default/test/fixtures/doctype/snapshots/vdomProduction-expected.js
packages/translator-default/test/fixtures/white-space-test/snapshots/vdomProduction-expected.js

Fix issue where element keys could be different because of hoisted const elements not always being keyed. This could cause a hydration issue since the server and client compilations would not agree on the keys.
Resolves #2216 
> Note:
> Ideally we refactor this so that this keying is all figured out in the analyze stage so that it's actually impossible for there to be a server/client compilation disagreement.

fix: optimize vdom key issue

---

packages/compiler/src/babel-types/generator/patch.js
packages/compiler/src/babel-types/types/definitions.js
packages/translator-tags/src/__tests__/fixtures/server-client/__snapshots__/csr-sanitized.expected.md
packages/translator-tags/src/__tests__/fixtures/server-client/__snapshots__/csr.expected.md
packages/translator-tags/src/__tests__/fixtures/server-client/__snapshots__/dom.expected/template.js
packages/translator-tags/src/__tests__/fixtures/server-client/__snapshots__/html.expected/template.js
packages/translator-tags/src/__tests__/fixtures/server-client/__snapshots__/ssr-sanitized.expected.md
packages/translator-tags/src/__tests__/fixtures/server-client/__snapshots__/ssr.expected.md
packages/translator-tags/src/__tests__/fixtures/server-client/template.marko
packages/translator-tags/src/__tests__/fixtures/server-client/test.ts
packages/translator-tags/src/core/client.ts
packages/translator-tags/src/core/index.ts
packages/translator-tags/src/core/server.ts
packages/translator-tags/src/visitors/program/html.ts
packages/translator-tags/src/visitors/scriptlet.ts

- Add `server` and `client` top-level statements, which act the same as `static` but are restricted to their target.

feat: add `server` and `client` statements

---

.changeset/slow-insects-sparkle.md
packages/marko/src/runtime/helpers/of-fallback.js
packages/translator-default/src/index.js
packages/translator-default/src/taglib/core/translate-for.js
packages/translator-default/test/fixtures/at-tags-dynamic/snapshots/cjs-expected.js
packages/translator-default/test/fixtures/at-tags-dynamic/snapshots/html-expected.js
packages/translator-default/test/fixtures/at-tags-dynamic/snapshots/htmlProduction-expected.js
packages/translator-default/test/fixtures/at-tags-dynamic/snapshots/vdom-expected.js
packages/translator-default/test/fixtures/at-tags-dynamic/snapshots/vdomProduction-expected.js
packages/translator-default/test/fixtures/at-tags-repeated-longhand/snapshots/cjs-expected.js
packages/translator-default/test/fixtures/at-tags-repeated-longhand/snapshots/html-expected.js
packages/translator-default/test/fixtures/at-tags-repeated-longhand/snapshots/htmlProduction-expected.js
packages/translator-default/test/fixtures/at-tags-repeated-longhand/snapshots/vdom-expected.js
packages/translator-default/test/fixtures/at-tags-repeated-longhand/snapshots/vdomProduction-expected.js
packages/translator-default/test/fixtures/for-tag/snapshots/cjs-expected.js
packages/translator-default/test/fixtures/for-tag/snapshots/html-expected.js
packages/translator-default/test/fixtures/for-tag/snapshots/htmlProduction-expected.js
packages/translator-default/test/fixtures/for-tag/snapshots/vdom-expected.js
packages/translator-default/test/fixtures/for-tag/snapshots/vdomProduction-expected.js
packages/translator-default/test/fixtures/macros/snapshots/cjs-expected.js
packages/translator-default/test/fixtures/macros/snapshots/html-expected.js
packages/translator-default/test/fixtures/macros/snapshots/htmlProduction-expected.js
packages/translator-default/test/fixtures/macros/snapshots/vdom-expected.js
packages/translator-default/test/fixtures/macros/snapshots/vdomProduction-expected.js
packages/translator-default/test/fixtures/simple/snapshots/cjs-expected.js
packages/translator-default/test/fixtures/simple/snapshots/html-expected.js
packages/translator-default/test/fixtures/simple/snapshots/htmlProduction-expected.js
packages/translator-default/test/fixtures/simple/snapshots/vdom-expected.js
packages/translator-default/test/fixtures/simple/snapshots/vdomProduction-expected.js

- Istanbul treats logical expressions in a way that results in uncovered lines in for-of loops as they were implemented.

fix: code coverage in for-of loops

---

.changeset/curly-cameras-move.md
packages/marko/tags-html.d.ts

Add open graph attributes to type defs
- Adds `prefix` to `<html>` and `<head>`
- Adds `property` to `<meta>`

Add open graph attributes to type defs

---

package.json
packages/translator-tags/src/__tests__/fixtures/let-tag-controllable-compile-error/__snapshots__/dom.expected/template.error.txt
packages/translator-tags/src/__tests__/fixtures/let-tag-controllable-compile-error/__snapshots__/html.expected/template.error.txt
packages/translator-tags/src/__tests__/fixtures/shadow-same-scope/__snapshots__/csr-sanitized.expected.md
packages/translator-tags/src/__tests__/fixtures/shadow-same-scope/__snapshots__/csr.expected.md
packages/translator-tags/src/__tests__/fixtures/shadow-same-scope/__snapshots__/dom.expected/template.hydrate.js
packages/translator-tags/src/__tests__/fixtures/shadow-same-scope/__snapshots__/dom.expected/template.js
packages/translator-tags/src/__tests__/fixtures/shadow-same-scope/__snapshots__/html.expected/template.js
packages/translator-tags/src/__tests__/fixtures/shadow-same-scope/__snapshots__/resume-sanitized.expected.md
packages/translator-tags/src/__tests__/fixtures/shadow-same-scope/__snapshots__/resume.expected.md
packages/translator-tags/src/__tests__/fixtures/shadow-same-scope/__snapshots__/ssr-sanitized.expected.md
packages/translator-tags/src/__tests__/fixtures/shadow-same-scope/__snapshots__/ssr.expected.md
packages/translator-tags/src/__tests__/fixtures/shadow-same-scope/template.marko
packages/translator-tags/src/__tests__/fixtures/shadow-same-scope/test.ts
packages/translator-tags/src/core/let.ts
packages/translator-tags/src/util/references.ts
packages/translator-tags/src/util/signals.ts
packages/translator-tags/src/util/translate-var.ts
packages/translator-tags/src/visitors/program/dom.ts
packages/translator-tags/src/visitors/program/html.ts
scripts/inspect-compiled-output.ts

[This](https://hackmd.io/SQGg1eGgTFyQmLASYaabIg?view#Shadowing) is now allowed:
```marko
<let/x = 0/>
<div>
<div>
<let/x = 1/>
${x} // 1
</div>
${x} // 0
</div>
```

feat: tag var shadowing, same scope

---

.changeset/long-adults-knock.md
packages/translator-default/src/tag/attribute/directives/class.js
packages/translator-default/src/tag/attribute/directives/style.js
packages/translator-default/src/tag/native-tag[html]/attributes.js
packages/translator-default/test/fixtures/attr-escape/snapshots/cjs-expected.js
packages/translator-default/test/fixtures/attr-escape/snapshots/html-expected.js
packages/translator-default/test/fixtures/attr-escape/snapshots/htmlProduction-expected.js
packages/translator-default/test/fixtures/attr-template-literal-escape/snapshots/cjs-expected.js
packages/translator-default/test/fixtures/attr-template-literal-escape/snapshots/html-expected.js
packages/translator-default/test/fixtures/attr-template-literal-escape/snapshots/htmlProduction-expected.js
packages/translator-default/test/fixtures/shorthand-id/snapshots/cjs-expected.js
packages/translator-default/test/fixtures/shorthand-id/snapshots/html-expected.js
packages/translator-default/test/fixtures/shorthand-id/snapshots/htmlProduction-expected.js

* Optimize the printing of template literals in the compiled html output. This now merges the static content from template literals with the rest of native tag html and reduces the amount of escaping needed.
* Avoid passing template literals through to the merge style/class helpers since we already know their strings.

perf: optimize template literal printing in html mode

---

.changeset/wise-dogs-jam.md
packages/marko/src/runtime/vdom/AsyncVDOMBuilder.js
packages/marko/src/runtime/vdom/VComment.js
packages/marko/src/runtime/vdom/vdom.js
packages/marko/test/components-browser/fixtures/component-unescaped-html/test.js
packages/translator-default/src/taglib/core/translate-html-comment.js
packages/translator-default/test/fixtures/comments/snapshots/vdom-expected.js
packages/translator-default/test/fixtures/comments/snapshots/vdomProduction-expected.js
packages/translator-default/test/fixtures/html-comment/snapshots/vdom-expected.js
packages/translator-default/test/fixtures/html-comment/snapshots/vdomProduction-expected.js
packages/translator-default/test/fixtures/sanity-check/snapshots/vdom-expected.js
packages/translator-default/test/fixtures/sanity-check/snapshots/vdomProduction-expected.js

Fixes a regression where unescaped html that contained a comment node was throwing an exception while diffing.
This was caused by https://github.com/marko-js/marko/pull/1519 which assumed the comment nodes were no longer used (bad assumption).
Besides support for diffing unescaped html with comments, now any nodes which cannot be virtualized are skipped.
This PR also fixes the `<html-comment>` tag syntax to properly output vdom nodes.

fix: issue diffing unescaped html that contains comments

---

.changeset/shaggy-plants-smell.md
.changeset/wise-sloths-prove.md
packages/marko/src/node_modules/@internal/components-util/index-browser.js
packages/marko/src/runtime/vdom/morphdom/index.js
packages/translator-default/src/tag/index.js

* Fix issue with the "ignoreUnrecognizedTags" compiler option being used with dynamic tags that have attribute tags.
* Removes the debug mode dom manipulation warning since chrome dropped the api's that allowed us to get useful stack traces.

Fix dynamic tag with attribute tags and the `ignoreUnrecognizedTags` compiler option.

---

.changeset/nine-kids-divide.md
packages/compiler/src/util/build-code-frame.js

Adds a `frame` property to CompileError errors

fix: add frame property to compile errors

---

.changeset/hip-roses-prove.md
package-lock.json
packages/marko/package.json

Downgrade minimatch module since latest version requires node 20 while we support 18+.

fix: downgrade minimatch

---

packages/translator-tags/src/__tests__/fixtures/cdata/__snapshots__/dom.expected/template.error.txt
packages/translator-tags/src/__tests__/fixtures/cdata/__snapshots__/dom.expected/template.js
packages/translator-tags/src/__tests__/fixtures/cdata/__snapshots__/html.expected/template.error.txt
packages/translator-tags/src/__tests__/fixtures/cdata/__snapshots__/html.expected/template.js
packages/translator-tags/src/__tests__/fixtures/cdata/test.ts
packages/translator-tags/src/visitors/cdata.ts

- People shouldn't be using CDATA in `.marko` files, let's throw an error instead.

fix: throw error instead of printing CDATA

---

.changeset/forty-eagles-end.md
packages/compiler/src/config.js
packages/compiler/src/index.js
packages/translator-tags/src/__tests__/fixtures/let-tag-controllable-runtime-error/__snapshots__/csr.expected.md
packages/translator-tags/src/__tests__/main.test.ts
packages/translator-tags/src/__tests__/utils/bundle.ts

Remove the default cache auto clearing behavior.
Previously the default compiler "cache" was cleared every setImmediate. This was to support server hot reloading in apps using `Lasso` (and `browser-refresh`). Since we brought back support for `browser-refresh` in the Marko package we now clear this cache when browser-refresh triggers a change making the default cache clearing redundant.

fix: remove default compiler cache clearing

---

.changeset/sharp-monkeys-deny.md
packages/translator-default/src/tag/custom-tag.js
packages/translator-default/src/tag/index.js
packages/translator-interop/src/__tests__/fixtures/interop-class-to-tags-import/__snapshots__/csr.expected.md
packages/translator-interop/src/__tests__/fixtures/interop-class-to-tags-import/__snapshots__/dom.expected/components/tags-counter.js
packages/translator-interop/src/__tests__/fixtures/interop-class-to-tags-import/__snapshots__/dom.expected/template.hydrate.js
packages/translator-interop/src/__tests__/fixtures/interop-class-to-tags-import/__snapshots__/dom.expected/template.js
packages/translator-interop/src/__tests__/fixtures/interop-class-to-tags-import/__snapshots__/html.expected/components/tags-counter.js
packages/translator-interop/src/__tests__/fixtures/interop-class-to-tags-import/__snapshots__/html.expected/template.js
packages/translator-interop/src/__tests__/fixtures/interop-class-to-tags-import/__snapshots__/resume.expected.md
packages/translator-interop/src/__tests__/fixtures/interop-class-to-tags-import/__snapshots__/ssr.expected.md
packages/translator-interop/src/__tests__/fixtures/interop-class-to-tags-import/components/tags-counter.marko
packages/translator-interop/src/__tests__/fixtures/interop-class-to-tags-import/template.marko
packages/translator-interop/src/__tests__/fixtures/interop-class-to-tags-import/test.ts

Manually imported tags in Marko 5 can now be analyzed and are optimized to use the import instead of being a dynamic tag.

fix: direct import of tags in translator-default

---

.changeset/calm-boxes-give.md
packages/compiler/src/taglib/index.js

```ts
import type { Input } from "./index.marko";
//                         ^^^^^^^^^^^^^^^  File './index.marko' is not a module.
```
- Thanks @DylanPiercey for finding this fix

fix: ts was not finding `.marko` files

---

packages/runtime-tags/src/html/template.ts

- Handle edge case where `stream.emit` doesn't exist or it doesn't emit an error properly.
- Improve safety of `socket`

fix: emit errors properly

---

.changeset/mean-ants-perform.md
packages/babel-utils/src/tags.js
packages/compiler/src/babel-plugin/parser.js
packages/compiler/src/babel-types/types/definitions.js
packages/translator-default/src/tag/attribute-tag.js
packages/translator-default/src/tag/index.js
packages/translator-default/src/taglib/core/conditional/translate-else.js
packages/translator-default/src/taglib/core/conditional/util.js
packages/translator-default/src/taglib/core/translate-for.js
packages/translator-default/src/taglib/core/translate-while.js
packages/translator-default/src/util/optimize-vdom-create.js
packages/translator-tags/src/core/for.ts
packages/translator-tags/src/core/if.ts
packages/translator-tags/src/util/get-parent-tag.ts
packages/translator-tags/src/util/nested-attribute-tags.ts
packages/translator-tags/src/util/references.ts
packages/translator-tags/src/util/sections.ts
packages/translator-tags/src/util/translate-attrs.ts
packages/translator-tags/src/visitors/tag/attribute-tag.ts
packages/translator-tags/src/visitors/tag/custom-tag.ts

Partially revert https://github.com/marko-js/marko/commit/8e07673ca07cc83d9910c68ff8359264015c28d1.
Specifically the control flow tags now have their body content as a `MarkoTagBody` instead of the `attributeTags` list.
This was done for two reasons:
1. The `for` tag needs to have a scope for it's tag parameters which could not properly be reflected on the refactored ast.
2. Getting rid of the body for the control flow indirectly broke the `@marko/tags-api-preview`.

fix: use MarkoTagBody for control flow

---

.changeset/silent-rats-report.md
packages/compiler/config.js
packages/compiler/index.d.ts
packages/compiler/src/index.js

Expose `globalConfig` on compiler
Fix compiler config default export

Compiler global config

---

.changeset/long-lemons-turn.md
packages/translator-default/src/util/add-dependencies.js

`lasso-marko` uses regular `path.resolve` instead of a `require.resolve` when processing the dependencies provided from the Marko compiler (https://github.com/lasso-js/lasso-marko/blob/9d4a2f7c190167e5bc3ab1015de54b14163e21b6/lasso-marko-plugin.js#L273).
In the hydrate compilation Marko tries to shorten all import paths to trim off `node_modules`, eg `./node_modules/@ebay/ebayui-core/thing` gets shortened to `@ebay/ebayui-core/thing` with the assumption it will be resolved later. However `lasso-marko` was not resolving this, so this PR changes it such that the dependencies provided to lasso are the full (relative) posix path.

fix: properly resolve lasso manifest in hydrate output

---

.changeset/fresh-rockets-sin.md
packages/compiler/babel-utils.d.ts
packages/compiler/src/babel-utils/imports.js
packages/compiler/src/babel-utils/index.js
packages/runtime-tags/src/translator/util/runtime.ts
packages/runtime-tags/src/translator/visitors/program/index.ts
packages/runtime-tags/src/translator/visitors/tag/dynamic-tag.ts
packages/translator-interop/src/__tests__/fixtures/interop-basic-tags-to-class/__snapshots__/dom.expected/template.js
packages/translator-interop/src/__tests__/fixtures/interop-basic-tags-to-class/__snapshots__/html.expected/template.js
packages/translator-interop/src/__tests__/fixtures/interop-class-in-components-in-tags-dir/__snapshots__/dom.expected/tags/hello.js
packages/translator-interop/src/__tests__/fixtures/interop-class-in-components-in-tags-dir/__snapshots__/html.expected/tags/hello.js
packages/translator-interop/src/__tests__/fixtures/interop-events-tags-to-class/__snapshots__/dom.expected/template.js
packages/translator-interop/src/__tests__/fixtures/interop-events-tags-to-class/__snapshots__/html.expected/template.js
packages/translator-interop/src/__tests__/fixtures/interop-nested-tags-to-class/__snapshots__/dom.expected/template.js
packages/translator-interop/src/__tests__/fixtures/interop-nested-tags-to-class/__snapshots__/html.expected/template.js
packages/translator-interop/src/__tests__/fixtures/interop-tag-params-tags-to-class/__snapshots__/dom.expected/template.js
packages/translator-interop/src/__tests__/fixtures/interop-tag-params-tags-to-class/__snapshots__/html.expected/template.js

fix: remove duplicate imports of compat runtime

---

packages/runtime-class/test/translator/fixtures/data-structure/snapshots/cjs-expected.js
packages/runtime-class/test/translator/fixtures/data-structure/snapshots/generated-expected.diagnostics.txt
packages/runtime-class/test/translator/fixtures/data-structure/snapshots/generated-expected.marko
packages/runtime-class/test/translator/fixtures/data-structure/snapshots/html-expected.js
packages/runtime-class/test/translator/fixtures/data-structure/snapshots/htmlProduction-expected.js
packages/runtime-class/test/translator/fixtures/data-structure/snapshots/vdom-expected.js
packages/runtime-class/test/translator/fixtures/data-structure/snapshots/vdomProduction-expected.js
packages/runtime-class/test/translator/fixtures/data-structure/template.marko

- Maybe resolves #2254 
- Added test for shadowing with a destructure
- The shadowing issue mentioned in the issue is not replicated by Marko's test suite
- With minimal testing, it seems this is not replicable. I will look further to attempt replication.

test(translator): check for shadowing `data` with a tag destructure

---

.changeset/large-colts-fold.md
.github/workflows/ci.yml
package-lock.json
packages/compiler/package.json
packages/runtime-class/package.json
packages/runtime-tags/package.json
packages/translator-interop/package.json

Updated version of https://github.com/marko-js/marko/pull/2097
Resolves #2096
* Adds `engines` field to all packages with node `18`, `20` and `>=22`.
* Add node `22` to CI test matrix.

chore: add engines field and add node 22 ci

---

.changeset/wet-lizards-repair.md
packages/runtime-class/src/translator/tag/attribute/modifiers/scoped.js
packages/runtime-class/test/translator/fixtures/attr-no-update-scoped/snapshots/cjs-expected.js
packages/runtime-class/test/translator/fixtures/attr-no-update-scoped/snapshots/generated-expected.marko
packages/runtime-class/test/translator/fixtures/attr-no-update-scoped/snapshots/html-expected.js
packages/runtime-class/test/translator/fixtures/attr-no-update-scoped/snapshots/htmlProduction-expected.js
packages/runtime-class/test/translator/fixtures/attr-no-update-scoped/snapshots/vdom-expected.js
packages/runtime-class/test/translator/fixtures/attr-no-update-scoped/snapshots/vdomProduction-expected.js
packages/runtime-class/test/translator/fixtures/attr-no-update-scoped/template.marko

resolves https://github.com/marko-js/marko/issues/1664

fix: issue mixing scoped and no-update directives

---

.changeset/strong-steaks-jam.md
.changeset/tall-stingrays-fry.md
packages/compiler/src/babel-plugin/parser.js
packages/runtime-class/src/translator/taglib/core/parse-class.js
packages/runtime-class/test/translator/fixtures/error-class-syntax/snapshots/cjs-error-expected.txt
packages/runtime-class/test/translator/fixtures/error-class-syntax/snapshots/generated-error-expected.txt
packages/runtime-class/test/translator/fixtures/error-class-syntax/snapshots/html-error-expected.txt
packages/runtime-class/test/translator/fixtures/error-class-syntax/snapshots/htmlProduction-error-expected.txt
packages/runtime-class/test/translator/fixtures/error-class-syntax/snapshots/hydrate-error-expected.txt
packages/runtime-class/test/translator/fixtures/error-class-syntax/snapshots/vdom-error-expected.txt
packages/runtime-class/test/translator/fixtures/error-class-syntax/snapshots/vdomProduction-error-expected.txt
packages/runtime-class/test/translator/fixtures/error-class-syntax/template.marko

Resolves https://github.com/marko-js/marko/issues/1328 and https://github.com/marko-js/marko/issues/1329
* Errors from the htmljs-parser will now _also_ display any compile errors as an aggregate error.
* The `class` block errors were being bounded to the incorrect end position for the `class` block.

fix: improve parse error locations and aggregate errors

---

.changeset/rude-oranges-fly.md
packages/compiler/src/taglib/loader/loadTagFromProps.js
packages/compiler/src/taglib/loader/loadTaglibFromProps.js

Resolves https://github.com/marko-js/marko/issues/997

fix: improve errors from unresolved taglib paths

---

.changeset/young-books-sleep.md
packages/runtime-class/src/runtime/components/ServerComponent.js

Resolves https://github.com/marko-js/marko/issues/998
* Adds stubs with better errors for component methods which cannot be used on the server.
* Adds `isDestroyed` and state setting apis to server side component instances.

fix: add stubs for some client side component apis

---

.changeset/famous-dingos-run.md
packages/runtime-tags/src/__tests__/fixtures/multiple-bound-values/__snapshots__/.name-cache.json
packages/runtime-tags/src/__tests__/fixtures/multiple-bound-values/__snapshots__/csr-sanitized.expected.md
packages/runtime-tags/src/__tests__/fixtures/multiple-bound-values/__snapshots__/csr.expected.md
packages/runtime-tags/src/__tests__/fixtures/multiple-bound-values/__snapshots__/dom.expected/tags/2counters.js
packages/runtime-tags/src/__tests__/fixtures/multiple-bound-values/__snapshots__/dom.expected/template.hydrate.js
packages/runtime-tags/src/__tests__/fixtures/multiple-bound-values/__snapshots__/dom.expected/template.js
packages/runtime-tags/src/__tests__/fixtures/multiple-bound-values/__snapshots__/html.expected/tags/2counters.js
packages/runtime-tags/src/__tests__/fixtures/multiple-bound-values/__snapshots__/html.expected/template.js
packages/runtime-tags/src/__tests__/fixtures/multiple-bound-values/__snapshots__/resume-sanitized.expected.md
packages/runtime-tags/src/__tests__/fixtures/multiple-bound-values/__snapshots__/resume.expected.md
packages/runtime-tags/src/__tests__/fixtures/multiple-bound-values/__snapshots__/ssr-sanitized.expected.md
packages/runtime-tags/src/__tests__/fixtures/multiple-bound-values/__snapshots__/ssr.expected.md
packages/runtime-tags/src/__tests__/fixtures/multiple-bound-values/tags/2counters.marko
packages/runtime-tags/src/__tests__/fixtures/multiple-bound-values/template.marko
packages/runtime-tags/src/__tests__/fixtures/multiple-bound-values/test.ts
packages/runtime-tags/src/translator/visitors/tag/index.ts

Currently, [this](https://markojs.com/v6/playground/#NobwRAdghgtgpmAXGAlhAJnAHgOhlAJwGsB7MAGjAAcoAXACyTAHpaoBzAZ2bU132JlKAYxIRaccUwA2cWs1EBXcQEYAvAAYAOhFnyl4gEyadOwwYkFOAAgsrEau7ZLLahhxcOmMKAG7WAWgDrABIQOwBfUPCXIwiwCPJwaHgmc1jLTjxCUgpqOkZkVg5udNc4K2zBPNFxSVoZOQUM+zU0KkVaHDsdPWbXdzaIDq7PbwAjTtoxazEAYWkUYSIACgBKaxBnVxUAal3rKKDoyJ1J2mmIWYgFpdWNrc99w8DgsM94iIBdIA) is broken (adjacent bound values don't transform properly)

fix: adjacent bound attrs transform properly

---

.changeset/tough-readers-compare.md
packages/runtime-tags/tags-html.d.ts

- Since event handlers of the `on[A-Z]` form are case-insensitive, this casing is preferred.

feat(ts): capitalize words in event handlers

---

.changeset/popular-experts-applaud.md
.sizes.json
.sizes/dom.js
packages/runtime-tags/src/dom/event.ts

- There is a [Google Chrome Bug](https://issues.chromium.org/issues/41484175) where blur events are fired when elements are removed from the DOM (this behavior does not match that of other browsers). This causes issues when Marko removes elements during the render phase.
- This PR changes Marko's behavior so that if an event happens during the render phase, handlers do not fire. Incidentally, this means behavior matches React for the `blur` case but not any of the other frameworks.

fix: ignore events during the render phase

---

.changeset/three-monkeys-boil.md
packages/runtime-tags/src/__tests__/serializer.test.ts
packages/runtime-tags/src/html/serializer.ts

Apparently this breaks in v8...
```js
var x = {};
x[0]=x[1]=x[2]=x[3]=x[4]=x[5]=x[6]=x[7]=x[8]=x[9]=x[10]=x[11]=x[12]=x[13]=x[14]=x[15]=x[16]=x[17]=x[18]=x[19]=x[20]=x[21]=x[22]=x[23]=x[24]=x[25]=x[26]=x[27]=x[28]=x[29]=x[30]=x[31]=x[32]=x[33]=x[34]=x[35]=x[36]=x[37]=x[38]=x[39]=x[40]=x[41]=x[42]=x[43]=x[44]=x[45]=x[46]=x[47]=x[48]=x[49]=x[50]=x[51]=x[52]=x[53]=x[54]=x[55]=x[56]=x[57]=x[58]=x[59]=x[60]=x[61]=x[62]=x[63]=x[64]=x[65]=x[66]=x[67]=x[68]=x[69]=x[70]=x[71]=x[72]=x[73]=x[74]=x[75]=x[76]=x[77]=x[78]=x[79]=x[80]=x[81]=x[82]=x[83]=x[84]=x[85]=x[86]=x[87]=x[88]=x[89]=x[90]=x[91]=x[92]=x[93]=x[94]=x[95]=x[96]=x[97]=x[98]=x[99]=x[100]=x[101]=x[102]=x[103]=x[104]=x[105]=x[106]=x[107]=x[108]=x[109]=x[110]=x[111]=x[112]=x[113]=x[114]=x[115]=x[116]=x[117]=x[118]=x[119]=x[120]=x[121]=x[122] …
```

[Tags API] fix: avoid long assignment chains in serializer

---

.changeset/old-cameras-cheat.md
packages/runtime-class/test/package.json
packages/runtime-tags/src/__tests__/fixtures/trailing-tag-dynamic-attr/__snapshots__/.name-cache.json
packages/runtime-tags/src/__tests__/fixtures/trailing-tag-dynamic-attr/__snapshots__/dom.expected/template.hydrate.js
packages/runtime-tags/src/__tests__/fixtures/trailing-tag-dynamic-attr/__snapshots__/dom.expected/template.js
packages/runtime-tags/src/__tests__/fixtures/trailing-tag-dynamic-attr/__snapshots__/html.expected/template.js
packages/runtime-tags/src/__tests__/fixtures/trailing-tag-dynamic-attr/__snapshots__/resume-sanitized.expected.md
packages/runtime-tags/src/__tests__/fixtures/trailing-tag-dynamic-attr/__snapshots__/resume.expected.md
packages/runtime-tags/src/__tests__/fixtures/trailing-tag-dynamic-attr/__snapshots__/ssr-sanitized.expected.md
packages/runtime-tags/src/__tests__/fixtures/trailing-tag-dynamic-attr/__snapshots__/ssr.expected.md
packages/runtime-tags/src/__tests__/fixtures/trailing-tag-dynamic-attr/template.marko
packages/runtime-tags/src/__tests__/fixtures/trailing-tag-dynamic-attr/test.ts
packages/runtime-tags/src/translator/visitors/tag/native-tag.ts

- Allow dynamic attrs on `<body>` and `<html>` tags, which are special cased as trailing tags

fix: dynamic attrs on html and body tags

---

.changeset/flat-teeth-return.md
package-lock.json
packages/runtime-tags/package.json
packages/translator-interop/package.json
scripts/publish-alias.ts

Releases `marko@6.0.0` which will be tagged as `next` until [stable milestone tasks](https://github.com/orgs/marko-js/projects/2/views/12?filterQuery=-status%3ADone+milestones%3A%22TagsAPI+Stable%22) are completed.

chore: release tags api as 6.0.0

---

.changeset/deep-hands-sort.md
packages/runtime-tags/src/__tests__/fixtures/serialize-promise/__snapshots__/resume.expected.md
packages/runtime-tags/src/__tests__/fixtures/serialize-promise/__snapshots__/ssr.expected.md
packages/runtime-tags/src/__tests__/serializer.test.ts
packages/runtime-tags/src/html/serializer.ts

Partial fix for #2791.
Promises serialized no longer contribute to unhandled rejections when unreferenced.

fix: avoid unhandled promise rejections when serializing promises

---

SECURITY.md

👋 Hi everyone! We’re @UlisesGascon and @RafaelGSS, working with the OpenJS Foundation as part of [the Alpha-Omega initiative](https://openjsf.org/blog/openjs-security-checkpoint-2025-so-far). Our focus is supporting OpenJS projects in strengthening their security posture. We can help with things like:
- Reviewing or creating security documentation (e.g., SECURITY.md, incident response plans...)
- Supporting vulnerability handling and escalation (reporting, triage, CVEs, disputes)
- Reviewing repo configurations and GitHub security settings
- Sharing best practices (e.g., OSSF Scorecard)
- Answering general questions on licenses, compliance, or incident response
:sparkles: We’re here as a resource for the Marko team and happy to collaborate on whatever is most useful for you. Looking …

 docs: add a security policy
