marko-js/marko

- README.md
- runtime/marko-runtime.js
- test/api-tests.js
- test/test-project/hello-global.marko
* https://github.com/raptorjs/marko/issues/28
> Support $global in template.renderSync

- taglibs/core/AssignNode.js
Removing the else if block in order to allow complex var names on the left hand of the assignment.
> Allowing complex var names;

- test/fixtures/async-templates/async-fragment-promise-error/expected.html
- test/fixtures/async-templates/async-fragment-promise-error/template.marko
- test/fixtures/async-templates/async-fragment-promise-error/test.js
Adding test case for [markp-async promise data provider fix](https://github.com/raptorjs/marko-async/pull/12)
> adding async-promise resolve callback uncaught exception test case

- README.md
Fixes https://github.com/marko-js/marko-widgets/issues/64
> Added empty() and notEmpty() helpers to the readme

- README.md
Raise awareness for number one of https://github.com/marko-js/marko/issues/59
> Improved docs for async taglib

- README.md
fixes https://github.com/marko-js/marko/issues/125
> improved docs for input.renderBody()

- compiler/Builder.js
> change value of literalFalse to false

- compiler/Builder.js
> change value of literalUndefined to undefined

- test/autotests/codegen/literal/expected.js
> Fix tests for #332 and #333

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- README.md
This branch is a starting point for encouraging contributions to Marko with the following:
> Encourage Contributions

- defineRenderer.js
- docs/javascript-api.md
- package.json
- test/autotests/api/defineRenderer/template.marko
- test/autotests/api/defineRenderer/test.js
> Fixes #344 - defineRenderer for marko

- docs/overview.md
Minor update to documentation. Adding VSCode's syntax highlighter.
> Add syntax highlighting extension

- runtime/helpers.js
- test/autotests/render/for-props-map/expected.html
- test/autotests/render/for-props-map/template.marko
- test/autotests/render/for-props-map/test.js
> For each property should work with Map instances.

- docs/components.md
The developer can `require` marko files then use component auto init.
I found out about it in the [marko-webpack/src/pages/home/client.js](https://github.com/marko-js-samples/marko-webpack/blob/master/src/pages/home/client.js) file.
It may be helpful to include it in the documentation.
> component auto-init documentation

- docs/core-tags.md
The `await` tag basic implementation and advanced use signature.
I wanted to fill in the basic implementation because it's so handy. If you think this will help users I will also volunteer to document the advanced usage but doing so could take a whole page. Your thoughts?
> await tag basic documentation

- docs/getting-started.md
Related to: https://github.com/marko-js/marko/issues/619
Replaced constructor with onCreate
> Replace constructor with onCreate

- docs/components.md
+ clarify on-* wildcard usage
+ event handler basic and advanced notes
+ events comparison with dom, jquery, marko
+ link to example https://github.com/marko-js/markojs-website/pull/10
In the chat earlier we found an opportunity to improve the docs around event handlers.
> event handlers docs clarification, on-*, usage, comparisons, example

- express.js
enable res.marko can catch a error safe
use like 
```javascript
res.marko(..).catch((err) => {
next(err);
})
```
enable res.marko can catch a error safe
see issue #692
> enable res.marko can catch a error safe

- docs/installing.md
> Corrected file name for generated js file.

- docs/components.md
- docs/webpack.md
> Fix typo in webpack.md

- docs/marko-vs-react.md
Fix up dangling backtick.
Include missing code snippet.
> Clean up marko-vs-react.md

- docs/why-is-marko-fast.md
Clean up a dangling quotation mark 💅
> Clean up why-is-marko-fast.md

- src/components/taglib/TransformHelper/handleRootNodes.js
- test/autotests/render/error-variable-id-root-node/template.marko
- test/autotests/render/error-variable-id-root-node/test.js
- test/autotests/render/shorthand-div-id-dynamic/expected.html
- test/autotests/render/shorthand-div-id-dynamic/template.marko
> Revert "Fixes #705 - Throw error when the root HTML element has a dynamic id …"

- docs/components.md
🐛 Fix broken link to `lifecycle` section.
> Fix broken link to lifecycle section

- docs/redux.md
> Fix typo in redux.md

- docs/webpack.md
Changed component name from my-component to referencing hello (which is the name of the file above)
Just correcting the filename
> Update webpack.md on the name of the file in example

- src/compiler/index.js
A very simple enhancement: Update the test description. from `shouldbe` to `should be`.
> Update compile/index.js test description

- src/components/jquery.js
In the client side, we are very cared about the size of core runtime library size. So there is necessary to simplify the code as long as we can, of course it should be in the premise of not impacting the existing logic and performance. So i made this PR.
> Simplify a condition judgement in components-jquery

- src/components/Component.js
before access newInput.$global， we should judge if it is undefined or not
> fix undefined reference error in Component.js

- docs/components.md
> Fixes #841

- docs/components.md
Just a one char fix to correct a broken link in the docs.
> fix docs link to lifecycle methods

- docs/fastify.md
Fixed the incorrect marko-fastify project link.
> Updated the marko-fastify project link

- src/components/legacy/defineWidget-legacy-browser.js
- src/components/legacy/renderer-legacy.js
- fix updating transcluded content in legacy components (w-body).
- don't preserve input for legacy components. 
> Legacy compatibility layer fixes

- src/components/legacy/dependencies/vdom.js
- src/runtime/compiler.browser.json
Without this change, Try Online is broken.
The paths were incorrect
It works:
> update incorrect paths

- docs/http.md
Instead of requiring the http module again use the http variable.
> Use http variable

- test/components-browser/fixtures/transclusion-rerender-stateful/components/container/index.marko
- test/components-browser/fixtures/transclusion-rerender-stateful/components/counter/index.marko
- test/components-browser/fixtures/transclusion-rerender-stateful/index.marko
- test/components-browser/fixtures/transclusion-rerender-stateful/test.js
Adds a failing test case for #1022
> Failing test case for #1022 

- src/compiler/Parser.js
- test/render/fixtures/spread-attribute-function-object/test.js
The following now works:
```marko
<tag ...getAttrs()/>
```
> Fix spread fns #1008

- bin/markoc.js
Adds a quiet mode to the `markoc` cli tool
```
markoc . --quiet
```
> add a quiet option to markoc

- src/compiler/taglib-loader/loadTagFromProps.js
- src/compiler/taglib-loader/loadTaglibFromProps.js
- test/render/fixtures/template-tag-transformer-array/expected.html
- test/render/fixtures/template-tag-transformer-array/marko.json
- test/render/fixtures/template-tag-transformer-array/template.marko
- test/render/fixtures/template-tag-transformer-array/transformer-1.js
- test/render/fixtures/template-tag-transformer-array/transformer-2.js
- test/render/fixtures/template-transformer-array/expected.html
- test/render/fixtures/template-transformer-array/marko.json
- test/render/fixtures/template-transformer-array/template-a.marko
- test/render/fixtures/template-transformer-array/template-b.marko
- test/render/fixtures/template-transformer-array/template.marko
- test/render/fixtures/template-transformer-array/transformer-1.js
- test/render/fixtures/template-transformer-array/transformer-2.js
> Fixes #877 - Allow array of transformers in marko.json.

- test/components-browser/fixtures-deprecated/widget-stateful-update-on-init/index.js
- test/components-browser/fixtures-deprecated/widget-stateful-update-on-init/template.marko
- test/components-browser/fixtures-deprecated/widget-stateful-update-on-init/test.js
- test/components-browser/fixtures/widget-stateful-update-on-mount/component.js
- test/components-browser/fixtures/widget-stateful-update-on-mount/index.marko
- test/components-browser/fixtures/widget-stateful-update-on-mount/test.js
A sanity check test that ensures you can update a component during the onMount part of the lifecycle.
> Add test for updating in onMount

- docs/components.md
Documentations on split components has beed edited and updated.
> DOCS Updated.

- docs/lasso.md
Updating docs to reflect the new package types for Marko with Lasso
- Only changes to docs regarding `marko-dependencies`, `marko-hydrate`, `package`.
> Adding docs for new package types for Marko with Lasso

- .gitignore
- package.json
- src/components/taglib/TransformHelper/assignComponentId.js
- test/compiler/fixtures-html/at-tags-dynamic/expected.js
- test/compiler/fixtures-html/simple/expected.js
- test/compiler/fixtures-vdom/simple/expected.js
- test/components-browser/fixtures/widget-preserve-all-state-when-rendered-in-loop/index.marko
- test/components-browser/fixtures/widget-preserve-all-state-when-rendered-in-loop/test.js
- test/components-compilation/fixtures-html/auto-key-els/expected.js
- test/components-compilation/fixtures-html/macro-widget/expected.js
- test/components-pages/fixtures/preserve-no-update-for-loop/tests.js
Fixes #952 
Fixes autokey keys in `for` loops
> fix for loop autokeys

- package-lock.json
- package.json
- src/compiler/CompileContext.js
- Update to latest complain (does a single complain per dependent module to reduce noise)
- Fallback to the template filepath as the location so `marko` is not shown as using deprecated features when it is actually the application
> Deprecation warnings

- src/components/taglib/components-transformer.js
- test/components-browser/fixtures/dynamic-tag-user-key/components/hello.marko
- test/components-browser/fixtures/dynamic-tag-user-key/index.marko
- test/components-browser/fixtures/dynamic-tag-user-key/test.js
> fixes #1075 - cannot compile dynamic tag at root with user key

- docs/syntax.md
- src/runtime/html/helpers.js
- src/runtime/vdom/helper-styleAttr.js
- test/render/fixtures/style-attr-array-mixed/expected.html
- test/render/fixtures/style-attr-array-mixed/template.marko
- test/render/fixtures/style-attr-array-mixed/test.js
```marko
<div style=['color:red', { background:'blue' }]/>
```
<p align="center">↓ ↓ ↓ ↓ ↓</p>
```html
<div style="color:red;background:blue;"></div>
```
Implements #1074 
> enable style arrays

- docs/components.md
First time looking at marko, but I think that `users` should be `user`
Code example doesn't make sense
> typo in code example

- docs/components.md
- src/components/Component.js
- src/components/event-delegation.js
- test/components-browser/fixtures/custom-events-declarative-function/component.js
- test/components-browser/fixtures/custom-events-declarative-function/components/app-bar/index.marko
- test/components-browser/fixtures/custom-events-declarative-function/components/app-bar/renderer.js
- test/components-browser/fixtures/custom-events-declarative-function/components/app-custom-events/component.js
- test/components-browser/fixtures/custom-events-declarative-function/components/app-custom-events/index.marko
- test/components-browser/fixtures/custom-events-declarative-function/index.marko
- test/components-browser/fixtures/custom-events-declarative-function/marko.json
- test/components-browser/fixtures/custom-events-declarative-function/test.js
- test/components-browser/fixtures/event-attach-el-function/index.marko
- test/components-browser/fixtures/event-attach-el-function/test.js
- test/components-browser/fixtures/event-handler-dom-args-bubbling-function/component.js
- test/components-browser/fixtures/event-handler-dom-args-bubbling-function/index.marko
- test/components-browser/fixtures/event-handler-dom-args-bubbling-function/test.js
This PR adds support for the following:
```marko
static function sayHello() {
alert('hello');
}
<button on-click(sayHello)>Say Hello</button>
```
Closes #624
> Event function handlers

- test/components-browser/fixtures/top-level-transcluded-content/components/inner.marko
- test/components-browser/fixtures/top-level-transcluded-content/index.marko
- test/components-browser/fixtures/top-level-transcluded-content/test.js
Adds a failing test case for #1033  (resolved by #1094)
> Add test for top level transcluded content.

- test/components-browser/fixtures/nested-fragments/components/container.marko
- test/components-browser/fixtures/nested-fragments/components/fragment.marko
- test/components-browser/fixtures/nested-fragments/index.marko
- test/components-browser/fixtures/nested-fragments/test.js
Adds a failing test case for #1051 (resolved by #1094)
> Add test for nested fragments.

- docs/installing.md
lasso module is missing on first documentation page (https://markojs.com/docs/installing/)
lasso module is missing
CLI installation globally is not enough, otherwise I get this error:
Error while applying option of "plugin". 
Cause: Error: Cannot find module 'lasso/package'
I run exactly the steps on this page, but got this error
```
$ lasso --main client.js --plugins lasso-marko --inject-into index.html
Config:
{
"outputDir": "/Users/timaschew/dev/my-mirror/frontend/static",
"urlPrefix": "%STATIC_PATH%",
"fingerprintsEnabled": false,
"plugins": [
"lasso-marko"
]
}
/Users/timaschew/n/lib/node_modules/lasso-cli/node_modules/property-handlers/lib/index.js:23
throw cause;
^
Error: Error while applying option of "plugin". Cause: Error: Cannot find module 'lasso/package'
at …
```
> DOCS: fix missing module to install

- src/morphdom/fragment.js
Removes use of es2015 features for browser support and uglification with uglify-js.
Fixes #1114
> Remove es2015 features from runtime.

- src/taglibs/core/util/parseImport.js
- test/parseImport/fixtures/parseImport-member-newlines/expected.json
- test/parseImport/fixtures/parseImport-member-newlines/input.txt
Updates the import tag parsing to support newlines.
Fixes: #1097
> Fix multi line import parsing.

- src/express.js
Currently we emit error events on the response object however this doesn't go through expresses normal error handling.
This PR calls Expresses `next` function with the error to allow regular error handling.
Fixes #973
> Express Errors with res.marko API

- docs/components.md
Fixed several typos in [components.md](https://github.com/marko-js/marko/blob/master/docs/components.md).
I've fixed three typos in [components.md](https://github.com/marko-js/marko/blob/master/docs/components.md).
- [ x ] I have read the **CONTRIBUTING** document and have signed (or will sign) the CLA.
- [ x ] I have updated/added documentation affected by my changes.
- [ x ] I have added tests to cover my changes.
> Fix several typos in components documentation

- src/morphdom/index.js
> Let to var in runtime code

- test/components-compilation/fixtures-html/arrow-functions/expected.js
- test/components-compilation/fixtures-html/arrow-functions/index.marko
- test/components-compilation/fixtures-html/arrow-functions/test.js
added failing test case for https://github.com/marko-js/marko/issues/1181
> added failing test case for #1181

- src/compiler/HtmlJsParser.js
- src/compiler/ast/HtmlElement/vdom/generateCode.js
- src/compiler/ast/TemplateLiteral.js
- src/taglibs/migrate/assign-tag.js
- src/taglibs/migrate/util/printJS.js
- test/codegen/fixtures/templateLiteral/expected.js
- test/codegen/fixtures/templateLiteral/index.js
- test/codegen/index.test.js
Fixes for printing template literals.
> Template literal print fixes

- test/migrate/fixtures/assign-tag/snapshot-expected.marko
- test/migrate/fixtures/assign-tag/template.marko
- test/migrate/fixtures/async-fragment-tag/snapshot-expected.marko
- test/migrate/fixtures/async-fragment-tag/template.marko
- test/migrate/fixtures/control-flow-directives/snapshot-expected.marko
- test/migrate/fixtures/control-flow-directives/template.marko
- test/migrate/fixtures/invoke-tag/snapshot-expected.marko
- test/migrate/fixtures/invoke-tag/template.marko
- test/migrate/fixtures/render-call-in-scriptlet/snapshot-expected.marko
- test/migrate/fixtures/render-call-in-scriptlet/template.marko
- test/migrate/fixtures/var-tag/snapshot-expected.marko
- test/migrate/fixtures/var-tag/template.marko
- test/migrate/fixtures/w-on/snapshot-expected.marko
- test/migrate/fixtures/w-on/template.marko
This PR adds tests for running `marko migrate` on all existing migrations.
> Additional migration tests

- package.json
Currently we publish all files (including tests) to npm. This PR adds a white list of files to be uploaded to npm.
> Whitelist files published to npm

- src/components/taglib/TransformHelper/handleComponentPreserve.js
- src/components/taglib/TransformHelper/handleScopedAttrs.js
- src/components/taglib/components-transformer.js
- src/taglibs/migrate/all-tags/w-for.js
Removes some duplicated deprecation handling for migrations added in #1190.
> Remove deprecations already moved to the migrate stage.

- src/compiler/ast/HtmlElement/vdom/HtmlElementVDOM.js
- src/taglibs/core/core-transformer.js
This PR removes some code missed in #1202 which is now handled in the migration layer.
> Remove unreachable dynamic attribute code

- scripts/build.js
- src/components/legacy/defineRenderer-legacy.js
- src/components/legacy/defineWidget-legacy-browser.js
- src/components/legacy/renderer-legacy.js
- src/components/taglib/TransformHelper/handleLegacyBind.js
- src/components/taglib/marko.json
- src/taglibs/migrate/all-tags/w-config.js
- src/taglibs/migrate/marko.json
- test/migrate/fixtures/w-config/snapshot-expected.marko
- test/migrate/fixtures/w-config/template.marko
- test/taglib-lookup/fixtures/forEachAttribute/expected.json
Adds migration for `w-config` attribute.
> Add migrator for w-config

- test/components-browser/fixtures-deprecated/widget-transitive-event/components/transitive/template.marko
- test/components-browser/fixtures-deprecated/widget-transitive-event/index.js
- test/components-browser/fixtures-deprecated/widget-transitive-event/marko.json
- test/components-browser/fixtures-deprecated/widget-transitive-event/template.marko
- test/components-browser/fixtures-deprecated/widget-transitive-event/test.js
- test/components-browser/fixtures-deprecated/widget-transitive-get-el/components/transitive/template.marko
- test/components-browser/fixtures-deprecated/widget-transitive-get-el/index.js
- test/components-browser/fixtures-deprecated/widget-transitive-get-el/marko.json
- test/components-browser/fixtures-deprecated/widget-transitive-get-el/template.marko
- test/components-browser/fixtures-deprecated/widget-transitive-get-el/test.js
> Failing tests for transitive widget ids/events

- package-lock.json
- package.json
- test/migrate/index.test.js
This PR updates the migration tests to use the new @marko/migrate programatic API.
> Update @marko/migrate and migration tests

- src/morphdom/index.js
- test/components-browser/fixtures/preserve-dom-conditional-before/component.js
- test/components-browser/fixtures/preserve-dom-conditional-before/index.marko
- test/components-browser/fixtures/preserve-dom-conditional-before/test.js
- test/components-browser/fixtures/preserve-dom-loop/component.js
- test/components-browser/fixtures/preserve-dom-loop/index.marko
- test/components-browser/fixtures/preserve-dom-loop/test.js
> fix no-update when nodes don't match up during diff

- package-lock.json
- package.json
- test/compiler/fixtures-html/class-tag-withspaces/expected.js
- test/compiler/fixtures-html/class-tag-withspaces/template.marko
Tests for [this issue](https://github.com/marko-js/htmljs-parser/issues/63).
- [ x ] I have read the **CONTRIBUTING** document and have signed (or will sign) the CLA.
- [ x ] I have updated/added documentation affected by my changes.
- [ x ] I have added tests to cover my changes.
> add test for whitespace between class {} and <html>

- package-lock.json
- src/runtime/html/AsyncStream.js
- src/taglibs/html/html-comment-tag.js
- src/taglibs/html/marko.json
- test/render/fixtures/html-comment-tag-dynamic/expected.html
- test/render/fixtures/html-comment-tag-dynamic/template.marko
- test/render/fixtures/html-comment-tag-dynamic/test.js
- test/render/fixtures/html-comment-tag/test.js
`<html-comment>` now works in vdom output and supports placeholders
> fix <html-comment> tag

- docs/marko-json.md
Fixes broken links in the documentation.
> docs: fix links

- docs/class-components.md
> Fixed misspelled "gelEl" to "getEl"

- docs/class-components.md
> docs: fix link text

- CHANGELOG.md
**Changes:**
1. statments ==> statements
2. parenthesis ==> parentheses
3. uneeded ==> unneeded
- [x ] I have read the **CONTRIBUTING** document and have signed (or will sign) the CLA.
> Fixed a few typos

- docs/state.md
Corrected two types, from its to it's and cumbersum to cumbersome
> Corrected typos

- docs/events.md
> Fixed typo in events.md

- src/core-tags/components/TransformHelper/convertToComponent.js
- test/components-compilation/fixtures-html-deprecated/bind-widget/expected.js
- test/components-compilation/fixtures-html-deprecated/component-template-entry/expected.js
- test/components-compilation/fixtures-html/component-template-entry-split/expected.js
- test/components-compilation/fixtures-html/index-widget-only/expected.js
Update the dependency path that gets added for split components.
Fixes #1320
> fix components runtime path after refactor

- docs/body-content.md
> Fix typo in body-content.md

- docs/events.md
> Fix typo in events.md

- docs/syntax.md
Fix a broken link in the docs.
> docs: fix broken link

- test/migrate/fixtures/control-flow-directives/snapshot-expected.marko
- test/migrate/fixtures/control-flow-directives/template.marko
Added a test which was removed by this PR: 
https://github.com/marko-js/marko/commit/8fc2ec4c85e837f8f368a4e12c34fb24695a4650#diff-d1930ac1b546d0101084664daec14c2e
> Readded tests

- docs/installing.md
highlight the code sample
The code snipts that I added before missing code highlighting, so I add it now.
This is a documentation update, so no tests supplied.
> highlight the code sample

- docs/10-awesome-marko-features.md
- docs/core-tags.md
- src/core-tags/migrate/all-tags/body-only-if.js
- src/core-tags/migrate/all-tags/control-flow-directives.js
- src/core-tags/migrate/all-tags/dynamic-attributes.js
- src/core-tags/migrate/all-tags/legacy-nested-tag.js
- src/core-tags/migrate/all-tags/modifier-key.js
- src/core-tags/migrate/all-tags/w-body.js
- src/core-tags/migrate/all-tags/w-config.js
- src/core-tags/migrate/all-tags/w-for.js
- src/core-tags/migrate/all-tags/w-id.js
- src/core-tags/migrate/all-tags/w-on.js
- src/core-tags/migrate/all-tags/w-preserve-attrs.js
- src/core-tags/migrate/all-tags/w-preserve.js
- src/core-tags/migrate/all-tags/widget-in-attrs.js
- src/core-tags/migrate/all-templates/non-standard-template-literals.js
- src/core-tags/migrate/assign-tag.js
- src/core-tags/migrate/invoke-tag.js
- src/core-tags/migrate/layout-placeholder-tag.js
- src/core-tags/migrate/layout-use-tag.js
- src/core-tags/migrate/var-tag.js
[I made some edits to wiki titles](https://gitter.im/marko-js/marko?at=5d43a91ea96def4751a0a5fd) before realizing their URLs were referenced here, so this fixes that.
> Update wiki URLs

- docs/redux.md
Whenever I read the Marko docs and see anything that I feel could be improved, I open a PR for that file.
Let me know if that’s a bad thing.
> Copyediting, make syntax consistent

- docs/class-components.md
Documentation fix. Helps readability.
- [ x ] I have read the **CONTRIBUTING** document and have signed (or will sign) the CLA.
- [ x ] I have updated/added documentation affected by my changes.
> Fix getComponent table;

- src/runtime/components/init-components-browser.js
Continuation of https://github.com/marko-js/marko/pull/1317
This PR fixes the same issue as the above but for when there are async out of order components being rendered before the document has finished loading.
> Fix init order for out of order components

- src/runtime/RenderResult.js
- src/runtime/components/legacy/index.js
> add legacy properties to RenderResult and add legacy getInitWidgetsCode

- src/runtime/components/util.js
> deprecate widget-id-prefix

- src/runtime/components/dom-data.js
> remove circular dep for dom weakmaps

- src/core-tags/components/preserve-tag-browser.js
- src/runtime/vdom/morphdom/index.js
- test/components-browser/fixtures/preserve-component-transcluded-autokey/component.js
- test/components-browser/fixtures/preserve-component-transcluded-autokey/components/container.marko
- test/components-browser/fixtures/preserve-component-transcluded-autokey/components/counter.marko
- test/components-browser/fixtures/preserve-component-transcluded-autokey/index.marko
- test/components-browser/fixtures/preserve-component-transcluded-autokey/test.js
- test/components-browser/fixtures/preserve-component-transcluded-userkey/component.js
- test/components-browser/fixtures/preserve-component-transcluded-userkey/components/container.marko
- test/components-browser/fixtures/preserve-component-transcluded-userkey/components/counter.marko
- test/components-browser/fixtures/preserve-component-transcluded-userkey/index.marko
- test/components-browser/fixtures/preserve-component-transcluded-userkey/test.js
- test/components-browser/fixtures/preserve-dom-transcluded-autokey/component.js
- test/components-browser/fixtures/preserve-dom-transcluded-autokey/components/container.marko
- test/components-browser/fixtures/preserve-dom-transcluded-autokey/index.marko
- test/components-browser/fixtures/preserve-dom-transcluded-autokey/test.js
- test/components-browser/fixtures/preserve-dom-transcluded-userkey/component.js
- test/components-browser/fixtures/preserve-dom-transcluded-userkey/components/container.marko
- test/components-browser/fixtures/preserve-dom-transcluded-userkey/index.marko
- test/components-browser/fixtures/preserve-dom-transcluded-userkey/test.js
> fix preservation of transcluded dom nodes, add transcluded preservation tests

- docs/core-tags.md
> Typo in example output

- packages/marko/src/runtime/components/legacy/renderer-legacy.js
> fix: don't serialize input for stateful widgets

- packages/marko/docs/custom-tags.md
Fixed a typo in "Custom tags" doc page.
> docs: fix a typo in custom tags page

- babel.config.js
- package-lock.json
- package.json
- packages/compiler/src/babel-plugin/index.js
- packages/compiler/src/taglib/index.js
- packages/compiler/test/index.test.js
- packages/marko/package.json
- packages/marko/src/compiler/modules.js
- packages/marko/src/taglib/taglib-finder/index.js
- packages/marko/src/taglib/taglib-loader/loadTagFromProps.js
- packages/marko/src/taglib/taglib-loader/loadTaglibFromProps.js
- packages/translator-default/src/tag/attribute/directives/index.js
- packages/translator-default/src/tag/attribute/index.js
- packages/translator-default/src/tag/attribute/modifiers/index.js
- packages/translator-default/src/tag/native-tag[html]/index.js
- packages/translator-default/src/taglib/index.js
- packages/translator-default/test/fixtures/class-inline-class-props-without-on-create/html-expected.js
- packages/translator-default/test/fixtures/class-inline-class-props-without-on-create/vdom-expected.js
- packages/translator-default/test/fixtures/class-inline/html-expected.js
- packages/translator-default/test/fixtures/class-inline/vdom-expected.js
- packages/translator-default/test/fixtures/error-class-private-properties/generated-error-expected.txt
- packages/translator-default/test/fixtures/error-class-private-properties/html-error-expected.txt
- packages/translator-default/test/fixtures/error-class-private-properties/vdom-error-expected.txt
- packages/translator-default/test/fixtures/error-class-static-properties/html-error-expected.txt
- packages/translator-default/test/fixtures/error-class-static-properties/vdom-error-expected.txt
Various updates to Marko@5 compiler to be more friendly to bundling with webpack for the browser target which is needed for the "try online" section of the website.
> fix: improve browser support for website

- packages/marko/src/runtime/html/AsyncStream.js
PR to fix https://github.com/marko-js/marko/issues/1599
> updated error emitted to keep the init error obj

- packages/marko/docs/conditionals-and-lists.md
- packages/marko/docs/events.md
- Fixes misspelled word in the [Styles](https://markojs.com/docs/conditionals-and-lists/#always-set-a-key) guide
- Fixes a syntax error in a code block in the [Events](https://markojs.com/docs/events/#listening-to-events) guide
> docs: fix a couple of typos in the guides

- packages/marko/src/runtime/components/Component.js
- packages/marko/src/runtime/components/init-components-browser.js
- packages/marko/src/runtime/components/legacy/defineRenderer-legacy.js
- packages/marko/src/runtime/components/legacy/defineWidget-legacy-browser.js
- packages/marko/src/runtime/components/legacy/renderer-legacy.js
- packages/marko/src/runtime/components/renderer.js
- packages/marko/src/runtime/components/util-browser.js
- packages/marko/src/runtime/helpers/class-value.js
- packages/marko/src/runtime/helpers/load-tag.js
- packages/marko/src/runtime/html/AsyncStream.js
- packages/marko/src/runtime/vdom/helpers/attrs.js
- packages/marko/src/runtime/vdom/parse-html.js
- packages/marko/src/runtime/vdom/vdom.js
Misc perf improvements discovered while optimizing an app.
Some are legacy component-specific.
> perf: misc optimizations

- packages/marko/docs/rollup.md
Changed the installation command to reflect usage of `@rollup/plugin-node-resolve` and `@rollup/plugin-commonjs`
Fixed the installation command.
> Changed Installation Command

- package-lock.json
- package.json
- packages/marko/package-lock.json
- packages/marko/package.json
- packages/marko/src/compiler/Parser.js
- packages/marko/src/compiler/ast/CustomTag.js
- packages/marko/src/runtime/helpers/merge-nested-tags.js
- packages/marko/test/migrate/fixtures/widget-data-is-state/snapshot-expected.js
- packages/marko/test/render/fixtures-deprecated/assign-computed-prop/template.marko
- packages/marko/test/render/fixtures-deprecated/assignment-concise/template.marko
- packages/marko/test/render/fixtures-deprecated/assignment/template.marko
- packages/marko/test/render/fixtures/error-nested-tags-repeated-with-invalid-render-body/components/test-nested-tags-tabs/index.marko
- packages/marko/test/render/fixtures/error-nested-tags-repeated-with-invalid-render-body/components/test-nested-tags-tabs/marko-tag.json
- packages/marko/test/render/fixtures/error-nested-tags-repeated-with-invalid-render-body/expected.html
- packages/marko/test/render/fixtures/error-nested-tags-repeated-with-invalid-render-body/template.marko
- packages/marko/test/render/fixtures/error-nested-tags-repeated-with-invalid-render-body/test.js
- packages/marko/test/render/fixtures/error-nested-tags-repeated-with-invalid-render-body/vdom-expected.html
- packages/marko/test/render/fixtures/nested-tags-repeated-with-default-render-body/components/test-nested-tags-tabs/index.marko
- packages/marko/test/render/fixtures/nested-tags-repeated-with-default-render-body/components/test-nested-tags-tabs/marko-tag.json
- packages/marko/test/render/fixtures/nested-tags-repeated-with-default-render-body/expected.html
- packages/marko/test/render/fixtures/nested-tags-repeated-with-default-render-body/template.marko
- packages/marko/test/render/fixtures/nested-tags-repeated-with-default-render-body/test.js
- packages/marko/test/render/fixtures/nested-tags-repeated-with-default-render-body/vdom-expected.html
* Update dependencies.
* Fixes issue where dynamic attribute tags are used with default body content.
> Fix repeated renderbody

- packages/compiler/index.d.ts
- packages/compiler/package.json
- packages/compiler/src/index.js
Adds basic type definitions for the compiler apis.
> chore: add types for compiler api

- packages/marko/docs/10-awesome-marko-features.md
- packages/marko/docs/marko-vs-react.md
- packages/marko/docs/why-is-marko-fast.md
Add dates and disclaimers to articles on the website. 
Some articles especially the React comparison are out of date. While it would make sense to write new articles/comparisons these are published externally stand for their time. So adding disclaimer notes to make it clear they are not the most up to date.
> chore: add article disclaimers

- packages/marko/docs/server-side-rendering.md
Remove those old server library links for inactive projects.
> chore: remove dead doc links

- packages/marko/src/core-tags/core/__flush_here_and_after__.js
- packages/marko/test/render/fixtures/flush-here-and-after-async-after/expected.html
- packages/marko/test/render/fixtures/flush-here-and-after-async-after/template.marko
- packages/marko/test/render/fixtures/flush-here-and-after-async-after/test.js
- packages/marko/test/render/fixtures/flush-here-and-after-async-after/vdom-expected.html
- packages/marko/test/render/fixtures/flush-here-and-after-async-before/expected.html
- packages/marko/test/render/fixtures/flush-here-and-after-async-before/template.marko
- packages/marko/test/render/fixtures/flush-here-and-after-async-before/test.js
- packages/marko/test/render/fixtures/flush-here-and-after-async-before/vdom-expected.html
- packages/marko/test/render/fixtures/flush-here-and-after-async-reverse/expected.html
- packages/marko/test/render/fixtures/flush-here-and-after-async-reverse/template.marko
- packages/marko/test/render/fixtures/flush-here-and-after-async-reverse/test.js
- packages/marko/test/render/fixtures/flush-here-and-after-async-reverse/vdom-expected.html
- packages/marko/test/render/fixtures/flush-here-and-after-sync/expected.html
- packages/marko/test/render/fixtures/flush-here-and-after-sync/template.marko
- packages/marko/test/render/fixtures/flush-here-and-after-sync/test.js
- packages/marko/test/render/fixtures/flush-here-and-after-sync/vdom-expected.html
- packages/marko/test/taglib-lookup/fixtures/forEachTag/expected.json
- packages/marko/test/taglib-lookup/fixtures/getTagsSorted/expected.json
- packages/translator-default/src/taglib/core/marko.json
> feat: flush_here_and_after tag

- scripts/types-babel-types.mjs
> fix: typescript types

- packages/compiler/package.json
https://github.com/marko-js/marko/blob/main/packages/compiler/README.md 404's
> chore(compiler): update homepage url

- packages/marko/docs/10-awesome-marko-features.md
> fix: typo in article

- packages/marko/docs/10-awesome-marko-features.md
Leading underscores on two places, was probably not the intention of the previous writer.
> Markdown typo fix in 10-awesome-marko-features.md

- packages/translator-default/src/util/add-dependencies.js
This fixes adding hydration dependencies when components are used recursively.
> fix: cyclic hydration deps

- packages/marko/docs/conditionals-and-lists.md
> Fix spelling

- .changeset/fifty-pugs-end.md
- package-lock.json
- packages/compiler/package.json
- packages/compiler/src/babel-plugin/parser.js
- packages/translator-default/test/fixtures/error-unclosed-tag/snapshots/cjs-error-expected.txt
- packages/translator-default/test/fixtures/error-unclosed-tag/snapshots/generated-error-expected.txt
- packages/translator-default/test/fixtures/error-unclosed-tag/snapshots/html-error-expected.txt
- packages/translator-default/test/fixtures/error-unclosed-tag/snapshots/htmlProduction-error-expected.txt
- packages/translator-default/test/fixtures/error-unclosed-tag/snapshots/hydrate-error-expected.txt
- packages/translator-default/test/fixtures/error-unclosed-tag/snapshots/vdom-error-expected.txt
- packages/translator-default/test/fixtures/error-unclosed-tag/snapshots/vdomProduction-error-expected.txt
Improves source location information by upgrading htmljs-parser.
> chore: upgrade htmljs-parser

- packages/marko/docs/10-awesome-marko-features.md
- Works around the autoformatting bugs encountered by @Sebring (closes #1702)
- Also has stronger link text, which is good for accessibility, touchscreens, and semantics
> Improve cover image citation link

- .changeset/swift-rocks-lay.md
- packages/translator-default/src/util/optimize-vdom-create.js
- packages/translator-default/test/fixtures/declaration/snapshots/vdomProduction-expected.js
- packages/translator-default/test/fixtures/doctype/snapshots/vdomProduction-expected.js
- packages/translator-default/test/fixtures/white-space-test/snapshots/vdomProduction-expected.js
> fix: autokey all nodes under a static root

- packages/marko/docs/compiler.md
This might have to wait until “Better warning/tip/callout markup” in The Everything Project
Fixed typos, improved document flow, added clarifications
- [n/a] ~~I have added tests to cover my changes.~~
> Copyedit compiler docs

- packages/marko/docs/express.md
Closes #1867, fixes a dead link to available bundlers, and copyediting improvements.
- ~~N/A I have added tests to cover my changes.~~
> Update Express docs

- .github/workflows/ci.yml
- packages/marko/README.md
I have evaluated Marko against the criteria for OpenSSF Best Practices "passing" badge. The badge is good for marketing, and it helps improve security by bringing attention to potential improvements.
This PR is to integrate the badge into the homepage. It communicates the diligence that the Marko project has invested in security. 
The badge is also a useful framework for making continued improvements to security in the form of a Silver or Gold level.
> Add OpenSSF Best Practices badge

- .changeset/lemon-deers-stare.md
- packages/marko/tags-html.d.ts
- Resolves #1944 
Add missing directives `no-update-body` and `no-update-body-if`, and tweak a few comments
> fix(typescript): add no-update-body and no-update-body-if

- .changeset/quiet-bears-chew.md
- packages/marko/tags-html.d.ts
- add onToggle
- add onFormData
- move onSubmit into form
> fix(typescript): add missing event handlers

- .changeset/grumpy-mirrors-hug.md
- packages/marko/tags-html.d.ts
- Add camelCase properties to CSS properties
> fix(typescript): add css camelCase props

- packages/translator-tags/src/visitors/cdata.ts
- packages/translator-tags/src/visitors/comment.ts
- packages/translator-tags/src/visitors/declaration.ts
- packages/translator-tags/src/visitors/document-type.ts
- packages/translator-tags/src/visitors/scriptlet.ts
- packages/translator-tags/src/visitors/text.ts
- move node deletion to end of translate phase when possible
> refactor: move node deletion to end of translate phase when possible

- .sizes.json
- packages/runtime-tags/src/dom/control-flow.ts
- packages/runtime-tags/src/dom/renderer.ts
- packages/translator-tags/src/__tests__/fixtures/basic-nested-scope-if/__snapshots__/resume-sanitized.expected.md
- packages/translator-tags/src/__tests__/fixtures/basic-nested-scope-if/__snapshots__/resume.expected.md
- packages/translator-tags/src/__tests__/fixtures/basic-nested-scope-if/__snapshots__/ssr-sanitized.expected.md
- packages/translator-tags/src/__tests__/fixtures/basic-nested-scope-if/__snapshots__/ssr.expected.md
- packages/translator-tags/src/__tests__/fixtures/basic-nested-scope-if/test.ts
> fix: skip closures in inactive renderer branches

- packages/marko/src/runtime/vdom/morphdom/index.js
- packages/marko/test/components-browser/fixtures/diffpatch-existing-key-component-to-element/components/app-hello/index.marko
- packages/marko/test/components-browser/fixtures/diffpatch-existing-key-component-to-element/index.marko
- packages/marko/test/components-browser/fixtures/diffpatch-existing-key-component-to-element/test.js
- packages/marko/test/components-browser/fixtures/diffpatch-existing-key-component-to-fragment/components/app-hello/index.marko
- packages/marko/test/components-browser/fixtures/diffpatch-existing-key-component-to-fragment/index.marko
- packages/marko/test/components-browser/fixtures/diffpatch-existing-key-component-to-fragment/test.js
(cherry picked from commit a8267ec67c4ae04f6045253323efea0d4ef6b7ed)
> fix: diffing edge cases

- .changeset/two-pumpkins-tell.md
- packages/translator-default/src/index.js
- packages/translator-tags/src/index.ts
> fix: avoid prebundling interop code

- .github/workflows/ci.yml
- package.json
- packages/marko/docs/fastify.md
Our format github action was causing lots of grief. I've changed it here so that instead we just run a lint for the PR
and run the full format for the release commits.
> chore: update gh actions to format on release commits

- .changeset/fuzzy-shoes-wave.md
- .changeset/grumpy-shirts-cross.md
- packages/marko/src/runtime/html/AsyncStream.js
- packages/marko/src/runtime/html/helpers/data-marko.js
- packages/marko/test/components-browser/fixtures/preserve-dom-server-mismatch/test.js
- packages/translator-default/src/tag/native-tag[html]/index.js
- packages/translator-default/test/fixtures/for-tag/snapshots/cjs-expected.js
- packages/translator-default/test/fixtures/for-tag/snapshots/html-expected.js
- packages/translator-default/test/fixtures/for-tag/snapshots/htmlProduction-expected.js
- packages/translator-default/test/fixtures/no-update-directives/snapshots/cjs-expected.js
- packages/translator-default/test/fixtures/no-update-directives/snapshots/html-expected.js
- packages/translator-default/test/fixtures/no-update-directives/snapshots/htmlProduction-expected.js
I completely messed up the release of https://github.com/marko-js/marko/pull/2205, this fixes that. (It didn't push my changes 😓)
> fix: hydration native tag no-update issue

- .changeset/warm-lamps-matter.md
- packages/marko/index.d.ts
- Resolves marko-js/language-server#250
> fix: native tag return type

- .changeset/grumpy-garlics-cough.md
- .sizes.json
- packages/runtime-tags/src/dom/control-flow.ts
- packages/translator-tags/src/__tests__/fixtures/basic-inert-collapsible-tree/__snapshots__/dom.expected/components/comments.js
- packages/translator-tags/src/__tests__/fixtures/for-event-handler/__snapshots__/csr-sanitized.expected.md
- packages/translator-tags/src/__tests__/fixtures/for-event-handler/__snapshots__/csr.expected.md
- packages/translator-tags/src/__tests__/fixtures/for-event-handler/__snapshots__/dom.expected/template.hydrate.js
- packages/translator-tags/src/__tests__/fixtures/for-event-handler/__snapshots__/dom.expected/template.js
- packages/translator-tags/src/__tests__/fixtures/for-event-handler/__snapshots__/html.expected/components/hello/index.js
- packages/translator-tags/src/__tests__/fixtures/for-event-handler/__snapshots__/html.expected/template.js
- packages/translator-tags/src/__tests__/fixtures/for-event-handler/__snapshots__/resume-sanitized.expected.md
- packages/translator-tags/src/__tests__/fixtures/for-event-handler/__snapshots__/resume.expected.md
- packages/translator-tags/src/__tests__/fixtures/for-event-handler/__snapshots__/ssr-sanitized.expected.md
- packages/translator-tags/src/__tests__/fixtures/for-event-handler/__snapshots__/ssr.expected.md
- packages/translator-tags/src/__tests__/fixtures/for-event-handler/template.marko
- packages/translator-tags/src/__tests__/fixtures/for-event-handler/test.ts
- packages/translator-tags/src/core/for.ts
> Stale closure bug

- .changeset/silver-games-hide.md
- packages/babel-utils/src/loc.js
> fix: start of line source location issue

- .changeset/good-boats-march.md
- .changeset/nine-spies-mate.md
- packages/marko/src/runtime/vdom/VElement.js
- packages/marko/src/runtime/vdom/VNode.js
- packages/marko/src/runtime/vdom/is-text-only.js
- packages/marko/src/runtime/vdom/morphdom/index.js
- packages/marko/test/__util__/domToString.js
- packages/marko/test/__util__/toHTML.js
- packages/marko/test/render/fixtures/style-tag-dynamic-text/expected.html
- packages/marko/test/render/fixtures/style-tag-dynamic-text/template.marko
- packages/marko/test/render/fixtures/style-tag-dynamic-text/test.js
- packages/marko/test/render/fixtures/style-tag-dynamic-text/vdom-expected.html
- packages/marko/test/vdom-create/fixtures/textarea/index.js
- packages/translator-default/src/tag/native-tag[html]/index.js
- packages/translator-default/test/fixtures/dynamic-tag-name/snapshots/cjs-expected.js
- packages/translator-default/test/fixtures/dynamic-tag-name/snapshots/generated-expected.marko
- packages/translator-default/test/fixtures/dynamic-tag-name/snapshots/html-expected.js
- packages/translator-default/test/fixtures/dynamic-tag-name/snapshots/htmlProduction-expected.js
- packages/translator-default/test/fixtures/dynamic-tag-name/snapshots/vdom-expected.js
- packages/translator-default/test/fixtures/dynamic-tag-name/snapshots/vdomProduction-expected.js
- packages/translator-default/test/fixtures/dynamic-tag-name/template.marko
Fix regression from #2138 which caused nullable native dynamic tags with body contents to not output the end tag. 😱
> Dynamic tag regression

- .changeset/dull-turkeys-wonder.md
- packages/runtime-class/src/runtime/vdom/VElement.js
- Ensure that special attributes haven't changed when rerendering; if they have, revert to the state Marko expects.
> fix: reorder check for special attrs

- .changeset/crazy-comics-hunt.md
- .changeset/curvy-mirrors-divide.md
- .changeset/flat-teeth-return.md
- .changeset/funny-waves-take.md
- package-lock.json
- packages/runtime-tags/CHANGELOG.md
- packages/runtime-tags/package.json
- packages/runtime-tags/src/__tests__/fixtures/define-tag-render-closure/__snapshots__/html.expected/template.js
- packages/runtime-tags/src/__tests__/fixtures/define-tag-render-closure/__snapshots__/ssr.expected.md
- packages/runtime-tags/src/__tests__/fixtures/define-tag-render/__snapshots__/html.expected/template.js
- packages/runtime-tags/src/__tests__/fixtures/define-tag-render/__snapshots__/resume.expected.md
- packages/runtime-tags/src/__tests__/fixtures/define-tag-render/__snapshots__/ssr.expected.md
- packages/runtime-tags/src/__tests__/fixtures/unserializable-warning/__snapshots__/html.expected/template.js
- packages/runtime-tags/src/html/inlined-runtimes.ts
- packages/runtime-tags/src/translator/core/define.ts
- packages/translator-interop/CHANGELOG.md
- packages/translator-interop/package.json
Fixes an issue where the inline comment walking runtime is loaded _after_ the main runtime.
> [Tags API] fix: race condition with inline comment walking runtime

- .changeset/clever-games-tell.md
- packages/runtime-tags/tags-html.d.ts
> feat(ts): add svg

- .changeset/better-places-design.md
- .changeset/nine-groups-decide.md
- packages/compiler/src/babel-utils/parse.js
- packages/runtime-class/test/translator/fixtures/statement-comment-only/snapshots/cjs-expected.js
- packages/runtime-class/test/translator/fixtures/statement-comment-only/snapshots/generated-expected.marko
- packages/runtime-class/test/translator/fixtures/statement-comment-only/snapshots/html-expected.js
- packages/runtime-class/test/translator/fixtures/statement-comment-only/snapshots/htmlProduction-expected.js
- packages/runtime-class/test/translator/fixtures/statement-comment-only/snapshots/vdom-expected.js
- packages/runtime-class/test/translator/fixtures/statement-comment-only/snapshots/vdomProduction-expected.js
- packages/runtime-class/test/translator/fixtures/statement-comment-only/template.marko
- packages/runtime-tags/src/__tests__/fixtures/define-tag-render-attr-signal/__snapshots__/dom.expected/template.hydrate.js
- packages/runtime-tags/src/__tests__/fixtures/dynamic-tag-custom-tags/__snapshots__/dom.expected/template.hydrate.js
- packages/runtime-tags/src/__tests__/fixtures/hoist-custom-tag-var-from-dynamic/__snapshots__/dom.expected/template.hydrate.js
- packages/runtime-tags/src/__tests__/fixtures/hoist-dynamic-tag-var-from-dynamic/__snapshots__/dom.expected/template.hydrate.js
- packages/runtime-tags/src/__tests__/fixtures/hoist-native-tag-var-from-dynamic/__snapshots__/dom.expected/template.hydrate.js
- packages/runtime-tags/src/translator/util/get-root.ts
- packages/runtime-tags/src/translator/util/is-invoked-function.ts
- packages/runtime-tags/src/translator/util/signals.ts
> fix: treat optionalCallExpressions as callExpressions for analysis

- .changeset/ninety-melons-talk.md
- packages/runtime-tags/tags/id.d.marko
- packages/runtime-tags/tags/let.d.marko
- I forgot to update types in #2795
> fix(id, let): typescript
